/* file: msg.c, automatically generated by GENTMS470.EXE, Version: 3.10 */
/* from: F:\PROJECTS\ADR-PORSCHE\PORSCHE_ADR_DEVELOPMENT_TRUNK\MOD\MOD_OSEK_DYN\CFG\PAG_ADR.oil */
/* at  : Wed Feb 22 07:46:34 2012 */
/* License 2400100185 for S1nn GmbH u. Co. KG, Infotainment and Connectivity */
/* Implementation: TMS470R1 */
/* Version of general code: 3.54b */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 3
#define osdVrmGenMinRelNum 10
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "osekcom.h"
#else
 #include <osekcom.h>
#endif

#if osdLib
osqROM0 osqROM1 const osqROM2 uint16 osqROM3 oskNumberOfMsgsFlagNotifics= osdNumberOfMsgsFlagNotifics;
#endif
#if osdNumberOfMsgsFlagNotifics
osqTcbRAM1 osqTcbRAM2 FlagType osqTcbRAM3 osComFlags[osdNumberOfMsgsFlagNotifics];
#else
   #if osdLib
   osqTcbRAM1 osqTcbRAM2 FlagType osqTcbRAM3 osComFlags[1];
   #endif
#endif
/* unqueued user data */
PWMGR_enVoltageStates msgPwrmgrStateUsrData;   /* PRQA S 1504 */  /* might be accessed from extern */
static CanRequests_CSHDL_MsgType msgCshdl_RequestsUsrDataQ0[osdMsgQSizemsgCshdl_Requests];
APP_DIAG_ST_DIAG_RESPONSE msgAppDiagDiagnoseResponseUsrData;   /* PRQA S 1504 */  /* might be accessed from extern */
APP_DIAG_ST_DIAG_REQUEST msgAppDiagDiagnoseRequestUsrData;   /* PRQA S 1504 */  /* might be accessed from extern */
static CSHDL_enSystemStates msgAppTaskSystemStatesUsrDataQ0[osdMsgQSizemsgAppTaskSystemStates];
CSHDL_ENUM_REQUEST_TO_CAN msgCshdlRequestToCanUsrData;   /* PRQA S 1504 */  /* might be accessed from extern */
static CanResponses_INFO_MsgType msgInfo_ResponsesUsrDataQ0[osdMsgQSizemsgInfo_Responses];
static CanRequests_INFO_MsgType msgInfo_RequestsUsrDataQ0[osdMsgQSizemsgInfo_Requests];
static ApplRspMessageType msgApplResponseUsrDataQ0[osdMsgQSizemsgApplResponse];

/* queued user data */

/* queues with size >= 1 */

static osqTcbRAM1 osqTcbRAM2 osComMsgQueueRam osqTcbRAM3 osComQueueRam[osdNumberOfMsgsQueues];

static osqROM0 osqROM1 const osqROM2 osComMsgQueue osqROM3 oskComQueue[osdNumberOfMsgsQueues] =
{
{
   (DataRefType)msgCshdl_RequestsUsrDataQ0,  /* first element in queue */ /* PRQA S 3305 */  /* might be casted to other alignment */
   (DataRefType)&msgCshdl_RequestsUsrDataQ0[osdMsgQSizemsgCshdl_Requests-1],  /* last element in queue */ /* PRQA S 3305 */  /* might be casted to other alignment */
   &osComQueueRam[0]  /* RAM part */
},
{
   (DataRefType)msgAppTaskSystemStatesUsrDataQ0,  /* first element in queue */ /* PRQA S 3305 */  /* might be casted to other alignment */
   (DataRefType)&msgAppTaskSystemStatesUsrDataQ0[osdMsgQSizemsgAppTaskSystemStates-1],  /* last element in queue */ /* PRQA S 3305 */  /* might be casted to other alignment */
   &osComQueueRam[1]  /* RAM part */
},
{
   (DataRefType)msgInfo_ResponsesUsrDataQ0,  /* first element in queue */ /* PRQA S 3305 */  /* might be casted to other alignment */
   (DataRefType)&msgInfo_ResponsesUsrDataQ0[osdMsgQSizemsgInfo_Responses-1],  /* last element in queue */ /* PRQA S 3305 */  /* might be casted to other alignment */
   &osComQueueRam[2]  /* RAM part */
},
{
   (DataRefType)msgInfo_RequestsUsrDataQ0,  /* first element in queue */ /* PRQA S 3305 */  /* might be casted to other alignment */
   (DataRefType)&msgInfo_RequestsUsrDataQ0[osdMsgQSizemsgInfo_Requests-1],  /* last element in queue */ /* PRQA S 3305 */  /* might be casted to other alignment */
   &osComQueueRam[3]  /* RAM part */
},
{
   (DataRefType)msgApplResponseUsrDataQ0,  /* first element in queue */ /* PRQA S 3305 */  /* might be casted to other alignment */
   (DataRefType)&msgApplResponseUsrDataQ0[osdMsgQSizemsgApplResponse-1],  /* last element in queue */ /* PRQA S 3305 */  /* might be casted to other alignment */
   &osComQueueRam[4]  /* RAM part */
},
};

/* access names - global buffers for copies */

PWMGR_enVoltageStates RecPWMGR_enVoltageStates;
PWMGR_enVoltageStates SentPWMGR_enVoltageStates;
CanRequests_CSHDL_MsgType SentBSGmessageType;
CanRequests_CSHDL_MsgType CanRx_CSHDL_ReceivedMsgData;
APP_DIAG_ST_DIAG_RESPONSE RecAppDiagResp;
APP_DIAG_ST_DIAG_RESPONSE SetAppDiagReq;
APP_DIAG_ST_DIAG_REQUEST SentAppDiagReq;
APP_DIAG_ST_DIAG_REQUEST RecAppDiagReq;
CSHDL_enSystemStates RecCSHDL_enSystemStates;
CSHDL_enSystemStates SentCSHDL_enSystemStates;
CSHDL_ENUM_REQUEST_TO_CAN ReceivedMessage_Cshdl_To_Can;
CSHDL_ENUM_REQUEST_TO_CAN SentMessage_Cshdl_To_Can;
CanResponses_INFO_MsgType CanTx_INFO_ReceivedMsgData;
CanResponses_INFO_MsgType CanTx_INFO_SentMsgData;
CanRequests_INFO_MsgType CanRx_INFO_SentMsgData;
CanRequests_INFO_MsgType CanTx_INFO_ReceiveMsgData;
ApplRspMessageType RecvApplResponse;
ApplRspMessageType SentApplResponse;

/* receiving tasks */

static osqROM0 osqROM1 const osqROM2 osComTaskPtr osqROM3 oskRcvTasks[osdNumberOfMsgsRcvTasks] =
{
{
   OsSystemTask_event, /* task */
   0 /* WithoutCopy flag */
},
{
   OsHostTask_10ms, /* task */
   0 /* WithoutCopy flag */
},
{
   OsAppTask_event_100ms, /* task */
   0 /* WithoutCopy flag */
},
};

/* notifications */

static osqROM0 osqROM1 const osqROM2 osComNotification osqROM3 oskNotifications[osdNumberOfMsgsNotifications] =
{
{
   osdCOM_ACTION_EVENT,  /* action */
   OsSystemTask_event,  /* task to activate or post event to */
   evSystemTaskVoltageState,  /* event */
#if osdNumberOfMsgsCallbackNotifics
   (osComCbFct) 0,  /* callback */
#endif
#if osdNumberOfMsgsFlagNotifics
   0,  /* flag */
#endif
},
{
   osdCOM_ACTION_EVENT,  /* action */
   OsSystemTask_event,  /* task to activate or post event to */
   evSystemTask_CSHDL_Request,  /* event */
#if osdNumberOfMsgsCallbackNotifics
   (osComCbFct) 0,  /* callback */
#endif
#if osdNumberOfMsgsFlagNotifics
   0,  /* flag */
#endif
},
{
   osdCOM_ACTION_EVENT,  /* action */
   OsHostTask_10ms,  /* task to activate or post event to */
   evHostTaskDiagnoseResponse,  /* event */
#if osdNumberOfMsgsCallbackNotifics
   (osComCbFct) 0,  /* callback */
#endif
#if osdNumberOfMsgsFlagNotifics
   0,  /* flag */
#endif
},
{
   osdCOM_ACTION_EVENT,  /* action */
   OsAppTask_event_100ms,  /* task to activate or post event to */
   evAppTaskDiagnoseRequest,  /* event */
#if osdNumberOfMsgsCallbackNotifics
   (osComCbFct) 0,  /* callback */
#endif
#if osdNumberOfMsgsFlagNotifics
   0,  /* flag */
#endif
},
{
   osdCOM_ACTION_EVENT,  /* action */
   OsAppTask_event_100ms,  /* task to activate or post event to */
   evAppTaskSystemStates,  /* event */
#if osdNumberOfMsgsCallbackNotifics
   (osComCbFct) 0,  /* callback */
#endif
#if osdNumberOfMsgsFlagNotifics
   0,  /* flag */
#endif
},
{
   osdCOM_ACTION_EVENT,  /* action */
   OsHostTask_10ms,  /* task to activate or post event to */
   evHostTaskOnCshdlRequestToCan,  /* event */
#if osdNumberOfMsgsCallbackNotifics
   (osComCbFct) 0,  /* callback */
#endif
#if osdNumberOfMsgsFlagNotifics
   0,  /* flag */
#endif
},
{
   osdCOM_ACTION_EVENT,  /* action */
   OsHostTask_10ms,  /* task to activate or post event to */
   evHostTask_INFO_Response,  /* event */
#if osdNumberOfMsgsCallbackNotifics
   (osComCbFct) 0,  /* callback */
#endif
#if osdNumberOfMsgsFlagNotifics
   0,  /* flag */
#endif
},
{
   osdCOM_ACTION_EVENT,  /* action */
   OsAppTask_event_100ms,  /* task to activate or post event to */
   evAppTask_INFO_Request,  /* event */
#if osdNumberOfMsgsCallbackNotifics
   (osComCbFct) 0,  /* callback */
#endif
#if osdNumberOfMsgsFlagNotifics
   0,  /* flag */
#endif
},
{
   osdCOM_ACTION_EVENT,  /* action */
   OsAppTask_event_100ms,  /* task to activate or post event to */
   evAppTaskApplResponse,  /* event */
#if osdNumberOfMsgsCallbackNotifics
   (osComCbFct) 0,  /* callback */
#endif
#if osdNumberOfMsgsFlagNotifics
   0,  /* flag */
#endif
},
};

/* generic RAM part */
#if osdUseMessageResource
static osqTcbRAM1 osqTcbRAM2 osComMsgRamGeneric osqTcbRAM3 osMsgRamGeneric[osdNumberOfMsgs];
#endif

/* ROM parts of all messages */

static osqROM0 osqROM1 const osqROM2 osComMsgRom osqROM3 oskMsgRom[osdNumberOfMsgs] =
{
{
   sizeof(PWMGR_enVoltageStates),  /* message length */
   0,  /* fifo size - also used to distinguisch queued and unqueued msgs */
   1,  /* number of receivers */
   #if osdUseMessageResource
   &osMsgRamGeneric[0],  /* pointer to generic RAM part */
   #endif
   {(osqPROM1 osqPROM2 osComMsgQueue osqPROM3*)(&msgPwrmgrStateUsrData)},  /* pointer to data part - message can either be queued or unqueued */ /* PRQA S 3305 */  /* might be casted to other alignment */
   #if STATUS_LEVEL == EXTENDED_STATUS
   osdMAGIC_MSG,  /* magic number */
   #endif
   #if (osdGHSDebugSupport==1)
   "msgPwrmgrState",  /* name of the message */
   #endif
   &oskRcvTasks[0], /* pointer to list of receiving tasks */
   &oskNotifications[0],  /* pointer to list of notifications */
   1,  /* number of notifications */
   0  /* send message without copying data */
},
{
   sizeof(CanRequests_CSHDL_MsgType),  /* message length */
   osdMsgQSizemsgCshdl_Requests,  /* fifo size - also used to distinguisch queued and unqueued msgs */
   1,  /* number of receivers */
   #if osdUseMessageResource
   &osMsgRamGeneric[1],  /* pointer to generic RAM part */
   #endif
   {(osqPROM1 osqPROM2 osComMsgQueue osqPROM3*)(&oskComQueue[0])},  /* pointer to data part - message can either be queued or unqueued */ /* PRQA S 0311 */  /* const might be casted to var */
   #if STATUS_LEVEL == EXTENDED_STATUS
   osdMAGIC_MSG,  /* magic number */
   #endif
   #if (osdGHSDebugSupport==1)
   "msgCshdl_Requests",  /* name of the message */
   #endif
   &oskRcvTasks[0], /* pointer to list of receiving tasks */
   &oskNotifications[1],  /* pointer to list of notifications */
   1,  /* number of notifications */
   0  /* send message without copying data */
},
{
   sizeof(APP_DIAG_ST_DIAG_RESPONSE),  /* message length */
   0,  /* fifo size - also used to distinguisch queued and unqueued msgs */
   1,  /* number of receivers */
   #if osdUseMessageResource
   &osMsgRamGeneric[2],  /* pointer to generic RAM part */
   #endif
   {(osqPROM1 osqPROM2 osComMsgQueue osqPROM3*)(&msgAppDiagDiagnoseResponseUsrData)},  /* pointer to data part - message can either be queued or unqueued */ /* PRQA S 3305 */  /* might be casted to other alignment */
   #if STATUS_LEVEL == EXTENDED_STATUS
   osdMAGIC_MSG,  /* magic number */
   #endif
   #if (osdGHSDebugSupport==1)
   "msgAppDiagDiagnoseResponse",  /* name of the message */
   #endif
   &oskRcvTasks[1], /* pointer to list of receiving tasks */
   &oskNotifications[2],  /* pointer to list of notifications */
   1,  /* number of notifications */
   0  /* send message without copying data */
},
{
   sizeof(APP_DIAG_ST_DIAG_REQUEST),  /* message length */
   0,  /* fifo size - also used to distinguisch queued and unqueued msgs */
   1,  /* number of receivers */
   #if osdUseMessageResource
   &osMsgRamGeneric[3],  /* pointer to generic RAM part */
   #endif
   {(osqPROM1 osqPROM2 osComMsgQueue osqPROM3*)(&msgAppDiagDiagnoseRequestUsrData)},  /* pointer to data part - message can either be queued or unqueued */ /* PRQA S 3305 */  /* might be casted to other alignment */
   #if STATUS_LEVEL == EXTENDED_STATUS
   osdMAGIC_MSG,  /* magic number */
   #endif
   #if (osdGHSDebugSupport==1)
   "msgAppDiagDiagnoseRequest",  /* name of the message */
   #endif
   &oskRcvTasks[2], /* pointer to list of receiving tasks */
   &oskNotifications[3],  /* pointer to list of notifications */
   1,  /* number of notifications */
   0  /* send message without copying data */
},
{
   sizeof(CSHDL_enSystemStates),  /* message length */
   osdMsgQSizemsgAppTaskSystemStates,  /* fifo size - also used to distinguisch queued and unqueued msgs */
   1,  /* number of receivers */
   #if osdUseMessageResource
   &osMsgRamGeneric[4],  /* pointer to generic RAM part */
   #endif
   {(osqPROM1 osqPROM2 osComMsgQueue osqPROM3*)(&oskComQueue[1])},  /* pointer to data part - message can either be queued or unqueued */ /* PRQA S 0311 */  /* const might be casted to var */
   #if STATUS_LEVEL == EXTENDED_STATUS
   osdMAGIC_MSG,  /* magic number */
   #endif
   #if (osdGHSDebugSupport==1)
   "msgAppTaskSystemStates",  /* name of the message */
   #endif
   &oskRcvTasks[2], /* pointer to list of receiving tasks */
   &oskNotifications[4],  /* pointer to list of notifications */
   1,  /* number of notifications */
   0  /* send message without copying data */
},
{
   sizeof(CSHDL_ENUM_REQUEST_TO_CAN),  /* message length */
   0,  /* fifo size - also used to distinguisch queued and unqueued msgs */
   1,  /* number of receivers */
   #if osdUseMessageResource
   &osMsgRamGeneric[5],  /* pointer to generic RAM part */
   #endif
   {(osqPROM1 osqPROM2 osComMsgQueue osqPROM3*)(&msgCshdlRequestToCanUsrData)},  /* pointer to data part - message can either be queued or unqueued */ /* PRQA S 3305 */  /* might be casted to other alignment */
   #if STATUS_LEVEL == EXTENDED_STATUS
   osdMAGIC_MSG,  /* magic number */
   #endif
   #if (osdGHSDebugSupport==1)
   "msgCshdlRequestToCan",  /* name of the message */
   #endif
   &oskRcvTasks[1], /* pointer to list of receiving tasks */
   &oskNotifications[5],  /* pointer to list of notifications */
   1,  /* number of notifications */
   0  /* send message without copying data */
},
{
   sizeof(CanResponses_INFO_MsgType),  /* message length */
   osdMsgQSizemsgInfo_Responses,  /* fifo size - also used to distinguisch queued and unqueued msgs */
   1,  /* number of receivers */
   #if osdUseMessageResource
   &osMsgRamGeneric[6],  /* pointer to generic RAM part */
   #endif
   {(osqPROM1 osqPROM2 osComMsgQueue osqPROM3*)(&oskComQueue[2])},  /* pointer to data part - message can either be queued or unqueued */ /* PRQA S 0311 */  /* const might be casted to var */
   #if STATUS_LEVEL == EXTENDED_STATUS
   osdMAGIC_MSG,  /* magic number */
   #endif
   #if (osdGHSDebugSupport==1)
   "msgInfo_Responses",  /* name of the message */
   #endif
   &oskRcvTasks[1], /* pointer to list of receiving tasks */
   &oskNotifications[6],  /* pointer to list of notifications */
   1,  /* number of notifications */
   0  /* send message without copying data */
},
{
   sizeof(CanRequests_INFO_MsgType),  /* message length */
   osdMsgQSizemsgInfo_Requests,  /* fifo size - also used to distinguisch queued and unqueued msgs */
   1,  /* number of receivers */
   #if osdUseMessageResource
   &osMsgRamGeneric[7],  /* pointer to generic RAM part */
   #endif
   {(osqPROM1 osqPROM2 osComMsgQueue osqPROM3*)(&oskComQueue[3])},  /* pointer to data part - message can either be queued or unqueued */ /* PRQA S 0311 */  /* const might be casted to var */
   #if STATUS_LEVEL == EXTENDED_STATUS
   osdMAGIC_MSG,  /* magic number */
   #endif
   #if (osdGHSDebugSupport==1)
   "msgInfo_Requests",  /* name of the message */
   #endif
   &oskRcvTasks[2], /* pointer to list of receiving tasks */
   &oskNotifications[7],  /* pointer to list of notifications */
   1,  /* number of notifications */
   0  /* send message without copying data */
},
{
   sizeof(ApplRspMessageType),  /* message length */
   osdMsgQSizemsgApplResponse,  /* fifo size - also used to distinguisch queued and unqueued msgs */
   1,  /* number of receivers */
   #if osdUseMessageResource
   &osMsgRamGeneric[8],  /* pointer to generic RAM part */
   #endif
   {(osqPROM1 osqPROM2 osComMsgQueue osqPROM3*)(&oskComQueue[4])},  /* pointer to data part - message can either be queued or unqueued */ /* PRQA S 0311 */  /* const might be casted to var */
   #if STATUS_LEVEL == EXTENDED_STATUS
   osdMAGIC_MSG,  /* magic number */
   #endif
   #if (osdGHSDebugSupport==1)
   "msgApplResponse",  /* name of the message */
   #endif
   &oskRcvTasks[2], /* pointer to list of receiving tasks */
   &oskNotifications[8],  /* pointer to list of notifications */
   1,  /* number of notifications */
   0  /* send message without copying data */
},
};

/* references to the messages used */

osqROM0 osqROM1 const osqROM2 osComMsg osqROM3 msgPwrmgrState = (osComMsg)(&(oskMsgRom[0]));
osqROM0 osqROM1 const osqROM2 osComMsg osqROM3 msgCshdl_Requests = (osComMsg)(&(oskMsgRom[1]));
osqROM0 osqROM1 const osqROM2 osComMsg osqROM3 msgAppDiagDiagnoseResponse = (osComMsg)(&(oskMsgRom[2]));
osqROM0 osqROM1 const osqROM2 osComMsg osqROM3 msgAppDiagDiagnoseRequest = (osComMsg)(&(oskMsgRom[3]));
osqROM0 osqROM1 const osqROM2 osComMsg osqROM3 msgAppTaskSystemStates = (osComMsg)(&(oskMsgRom[4]));
osqROM0 osqROM1 const osqROM2 osComMsg osqROM3 msgCshdlRequestToCan = (osComMsg)(&(oskMsgRom[5]));
osqROM0 osqROM1 const osqROM2 osComMsg osqROM3 msgInfo_Responses = (osComMsg)(&(oskMsgRom[6]));
osqROM0 osqROM1 const osqROM2 osComMsg osqROM3 msgInfo_Requests = (osComMsg)(&(oskMsgRom[7]));
osqROM0 osqROM1 const osqROM2 osComMsg osqROM3 msgApplResponse = (osComMsg)(&(oskMsgRom[8]));

#if osdNumberOfMsgs > 0

osqFunc1 void osqFunc2 osInternalStartCOM(void)
{
   /* some auxiliary variables */
   uint16 i;

   /* initialise unqueued messages */
   #if osdUseMessageResource
   for(i=0;i<osdNumberOfMsgs;i++)
   {
      osMsgRamGeneric[i].resource=0;
   }

   #endif
   /* initialise queues with size >= 1 */
   for(i=0;i<osdNumberOfMsgsQueues;i++)
   {
      osComQueueRam[i].w=oskComQueue[i].first;
      osComQueueRam[i].r=oskComQueue[i].first;
      osComQueueRam[i].msgCount=0;
      osComQueueRam[i].status=E_COM_NOMSG;
   }

}

#if osdCCC==osdCCCB
#if osdUseMessageResource
osqFunc1 uint8 osqFunc2 osComResourcesAreTaken(void)
{
   uint16 i;
   for(i=0;i<osdNumberOfMsgs;i++)
   {
      if(osMsgRamGeneric[i].resource!=0)
      {return 1;}
   }
    return 0;
}
#endif
#endif

#endif /* osdNumberOfMsgs */


/* END OF F:\PROJECTS\ADR-PORSCHE\PORSCHE_ADR_DEVELOPMENT_TRUNK\MOD\MOD_OSEK_DYN\CFG\tcb\msg.c */

