/* file: proctask.c, automatically generated by GENTMS470.EXE, Version: 3.10 */
/* from: F:\PROJECTS\ADR-PORSCHE\PORSCHE_ADR_DEVELOPMENT_TRUNK\MOD\MOD_OSEK_DYN\CFG\PAG_ADR.oil */
/* at  : Wed Feb 22 07:46:34 2012 */
/* License 2400100185 for S1nn GmbH u. Co. KG, Infotainment and Connectivity */
/* Implementation: TMS470R1 */
/* Version of general code: 3.54b */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 3
#define osdVrmGenMinRelNum 10
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "osek.h"
#else
 #include <osek.h>
#endif
#if defined USE_QUOTE_INCLUDES
 #include "osekext.h"
#else
 #include <osekext.h>
#endif

#define osdProcSupportNone 0
#define osdProcSupportC    1
#define osdProcSupportAsm  2
#define osdProcSupport     osdProcSupportNone


/* variables for assertions */
#if osdEnableProcedures
#if osdEnableAssertions
#if (osdNumberOfAllTasks>0)
   osqBOOL1 osqBOOL2 osBoolArrayBaseType osqBOOL3 osIsInProcedure[osdNumberOfAllTasks];
#else
   osqBOOL1 osqBOOL2 osBoolArrayBaseType osqBOOL3 osIsInProcedure[1];
#endif
#endif
#endif
/*** full preemptive tasks (have C part only) ***/

/*** non preemptive task or task with internal resource (can have C or Asm part) ***/


/* END OF F:\PROJECTS\ADR-PORSCHE\PORSCHE_ADR_DEVELOPMENT_TRUNK\MOD\MOD_OSEK_DYN\CFG\tcb\proctask.c */

