/* file: tcb.c, automatically generated by GENTMS470.EXE, Version: 3.10 */
/* from: F:\PROJECTS\ADR-PORSCHE\PORSCHE_ADR_DEVELOPMENT_TRUNK\MOD\MOD_OSEK_DYN\CFG\PAG_ADR.oil */
/* at  : Wed Feb 22 07:46:34 2012 */
/* License 2400100185 for S1nn GmbH u. Co. KG, Infotainment and Connectivity */
/* Implementation: TMS470R1 */
/* Version of general code: 3.54b */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 3
#define osdVrmGenMinRelNum 10
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

/* Start of invariant part */
#if defined USE_QUOTE_INCLUDES
 #include "osek.h"
#else
 #include <osek.h>
#endif
#if defined USE_QUOTE_INCLUDES
 #include "osekext.h"
#else
 #include <osekext.h>
#endif

   /* structure for standard counter (derived from system clock) */
   osqROM0 osqROM1 const osqROM2 AlarmBaseType osqROM3 oskAlarmDefinitions=
   {
      OSMAXALLOWEDVALUE,
      OSTICKSPERBASE,
      OSMINCYCLE
   };

   osqTcbRAM1 osqTcbRAM2 TickType osqTcbRAM3 osAlarmTime[osdNumberOfAlarms];
   #ifndef osdUseGeneratedFastAlarm
      osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osAlarmActivated[osdNumberOfAlarms];
      osqTcbRAM1 osqTcbRAM2 osHeapType osqTcbRAM3 osAlarmHeap[osdNumberOfAlarms+1];    /* Minimum Heap */
   #endif

   #if (osdNumberOfVarAlarms > 0)
   osqTcbRAM1 osqTcbRAM2 TickType osqTcbRAM3 osAlarmCycleTime[osdNumberOfVarAlarms];
   #endif

#if (CC==BCC2) || (CC==ECC2)
   #if (osdNumberOfPriorities > 0)
      osqTcbRAM1 osqTcbRAM2 osQEntryCountType osqTcbRAM3 osQReadyTaskHead[osdNumberOfPriorities];
      osqTcbRAM1 osqTcbRAM2 osQEntryCountType osqTcbRAM3 osQReadyTaskTail[osdNumberOfPriorities];
   #else
      osqTcbRAM1 osqTcbRAM2 osQEntryCountType osqTcbRAM3 osQReadyTaskHead[1];
      osqTcbRAM1 osqTcbRAM2 osQEntryCountType osqTcbRAM3 osQReadyTaskTail[1];
   #endif
#else
   #if (osdNumberOfPriorities > 0)
      osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQReadyTask[osdNumberOfPriorities];
   #else
      osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQReadyTask[1];
   #endif
#endif

#if ((CC == BCC2) || (CC == ECC2))
   #if (osdNumberOfAllTasks > 0)
      osqTcbRAM1 osqTcbRAM2 osActivationCountType osqTcbRAM3 osTcbActivationCount[osdNumberOfAllTasks];
   #else
      osqTcbRAM1 osqTcbRAM2 osActivationCountType osqTcbRAM3 osTcbActivationCount[1];
   #endif
#endif

#if (osdRTSize > 1)
   osqRAM1 osqRAM2 osPrioFlagType osqRAM3 osQReadyPrios[osdRTSize];
#else
   osqRAM1 osqRAM2 osPrioFlagType osqRAM3 osQReadyPrios;
#endif

#if (osdNumberOfAllTasks > 0)
   osqTcbRAM1 osqTcbRAM2 osTaskStateType osqTcbRAM3 osTcbTaskState[osdNumberOfAllTasks];
   osStackPtrType osqTcbRAM1 osqTcbRAM2 osqTcbRAM3 osTcbSP[osdNumberOfAllTasks];
   #if osdORTIDebug
   osqTcbRAM1 osqTcbRAM2 osPrioType osqTcbRAM3 osTcbActualPrio[osdNumberOfAllTasks];
   osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbORTIServiceId[osdNumberOfAllTasks];
   #endif
   #if STATUS_LEVEL == EXTENDED_STATUS
    #if (osdNumberOfInternalResources > 0) || (osdNumberOfInterruptResources > 0)
     osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbResourceCounter[osdNumberOfAllTasks];
    #else
     #if osdLib
      osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbResourceCounter[osdNumberOfAllTasks];
     #endif
    #endif
   #endif
   #if osdEnableContextOverlay
   osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbReturnAddressState[osdNumberOfAllTasks];
   #endif
#else
   osqTcbRAM1 osqTcbRAM2 osTaskStateType osqTcbRAM3 osTcbTaskState[1];
   osStackPtrType osqTcbRAM1 osqTcbRAM2 osqTcbRAM3 osTcbSP[1];
   #if osdORTIDebug
   osqTcbRAM1 osqTcbRAM2 osPrioType osqTcbRAM3 osTcbActualPrio[1];
   osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbORTIServiceId[1];
   #endif
   #if STATUS_LEVEL == EXTENDED_STATUS
   #if (osdNumberOfInternalResources > 0) || (osdNumberOfInterruptResources > 0)
   osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbResourceCounter[1];
    #else
     #if osdLib
      osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbResourceCounter[1];
     #endif
   #endif
   #endif
   #if osdEnableContextOverlay
   osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbReturnAddressState[1];
   #endif
#endif


   osqTcbRAM1 osqTcbRAM2 osPrioType osqTcbRAM3 osResSavedPrio[osdNumberOfAllResources];
   #if STATUS_LEVEL == EXTENDED_STATUS
      osqTcbRAM1 osqTcbRAM2 osResCounterType osqTcbRAM3 osResOccupationCounter[osdNumberOfAllResources];
   #endif
   #if ((STATUS_LEVEL == EXTENDED_STATUS) && osdEnableAssertions) || osdORTIDebug
      osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osResActualTask[osdNumberOfAllResources];
   #endif


   osqTcbRAM1 osqTcbRAM2 EventMaskType osqTcbRAM3 osTcbWaitEventMask[osdNumberOfExtendedTasks];

#if (osdNumberOfExtendedTasks > 0) || osdLib
   #if (osdNumberOfExtendedTasks == 0) && osdLib
   osqTcbRAM1 osqTcbRAM2 EventMaskType osqTcbRAM3 osTcbSetEventMask[1];
   #else
   osqTcbRAM1 osqTcbRAM2 EventMaskType osqTcbRAM3 osTcbSetEventMask[osdNumberOfExtendedTasks];
   #endif
#endif

#if (osdNumberOfSemaphores > 0)
   osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osSemaphoreState[osdNumberOfSemaphores];
   #if (osdNumberOfExtendedTasks == 0) && osdLib
   osqTcbRAM1 osqTcbRAM2 SemaphoreType osqTcbRAM3 osTcbWaitForSemaphore[1];
   #else
   osqTcbRAM1 osqTcbRAM2 SemaphoreType osqTcbRAM3 osTcbWaitForSemaphore[osdNumberOfExtendedTasks];
   #endif
#endif

#if osdLib
   osqROM0 osqROM1 const osqROM2 osRTSizeType    osqROM3 oskRTSize= osdRTSize;
   osqROM0 osqROM1 const osqROM2 osTaskIndexType osqROM3 oskNumberOfAllTasks=      osdNumberOfAllTasks;
   osqROM0 osqROM1 const osqROM2 osTaskIndexType osqROM3 oskNumberOfExtendedTasks= osdNumberOfExtendedTasks;
   osqROM0 osqROM1 const osqROM2 osPrioType      osqROM3 oskNumberOfPriorities=    osdNumberOfPriorities;

   osqROM0 osqROM1 const osqROM2 osResourceIndexType osqROM3 oskNumberOfAllResources= osdNumberOfAllResources;
   osqROM0 osqROM1 const osqROM2 osResourceIndexType osqROM3 oskNumberOfTaskResources= osdNumberOfTaskResources;
   osqROM0 osqROM1 const osqROM2 osResourceIndexType osqROM3 oskNumberOfInterruptResources= osdNumberOfInterruptResources;
   osqROM0 osqROM1 const osqROM2 osResourceIndexType osqROM3 oskNumberOfInternalResources= osdNumberOfInternalResources;

   osqROM0 osqROM1 const osqROM2 osAlarmIndexType osqROM3 oskNumberOfAlarms=         osdNumberOfAlarms;
   osqROM0 osqROM1 const osqROM2 osAlarmIndexType osqROM3 oskNumberOfVarAlarms=      osdNumberOfVarAlarms;
   osqROM0 osqROM1 const osqROM2 osAlarmIndexType osqROM3 oskNumberOfVarHeapAlarms=  osdNumberOfVarHeapAlarms;
   osqROM0 osqROM1 const osqROM2 osAlarmIndexType osqROM3 oskNumberOfStatHeapAlarms= osdNumberOfStatHeapAlarms;
   
   osqROM0 osqROM1 const osqROM2 TickType         osqROM3 oskMaxAllowedValue=        OSMAXALLOWEDVALUE;
   osqROM0 osqROM1 const osqROM2 TickType         osqROM3 oskMinCycle=               OSMINCYCLE;
   osqROM0 osqROM1 const osqROM2 TickType         osqROM3 oskTicksPerBase=           OSTICKSPERBASE;

#endif
/* End of invariant part */
#if defined osdUseGeneratedFastAlarm
osqFunc1 void osqFunc2 osCheckAlarms(void)  /* PRQA S 1505 */  /* might be called intern or extern */
{
   osqPRAM1 osqPRAM2 TickType osqPRAM3 *aPtr = osAlarmTime;
   if ((*aPtr) != 0)    /* CTA_HOST */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_HOST is expired */
         (*aPtr) = osAlarmCycleTime[CTA_HOST];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_HOST] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsHostTask_10ms,evActivateHostTask_10ms);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_MONITOR */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_MONITOR is expired */
         (*aPtr) = osAlarmCycleTime[CTA_MONITOR];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_MONITOR] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsMonitorTask_50ms,evActivateMonitorTask_50ms);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_DRIVER */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_DRIVER is expired */
         (*aPtr) = osAlarmCycleTime[CTA_DRIVER];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_DRIVER] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsDriverTask_1ms,evActivateDriverTask_1ms);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_DATABASE_EEPROM_WRITE */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_DATABASE_EEPROM_WRITE is expired */
         (*aPtr) = osAlarmCycleTime[CTA_DATABASE_EEPROM_WRITE];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_DATABASE_EEPROM_WRITE] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsDatabaseTask_event,evDatabaseCyclicEepromWrite);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evActivateAppTask_event_100ms);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_SYSTEM */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_SYSTEM is expired */
         (*aPtr) = osAlarmCycleTime[CTA_SYSTEM];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_SYSTEM] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsSystemTask_event,evActivateSystemTask_event);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_ERM_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_ERM_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_ERM_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_ERM_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskERMPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_WD */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_WD is expired */
         (*aPtr) = osAlarmCycleTime[CTA_WD];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_WD] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsDatabaseTask_event,evTriggerWD);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_MONITOR_AUDIO */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_MONITOR_AUDIO is expired */
         (*aPtr) = osAlarmCycleTime[CTA_MONITOR_AUDIO];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_MONITOR_AUDIO] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsMonitorTask_50ms,evMonitorTask_MonitorAudio_for_DTC);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_ONE_HOUR_MODE */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_ONE_HOUR_MODE is expired */
         (*aPtr) = osAlarmCycleTime[CTA_ONE_HOUR_MODE];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_ONE_HOUR_MODE] = 0;
         }
#endif /*osdUseHeapAlarm*/
         CSHDL_cbAlarmCallbackOneHourModeOver();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_DIAG_WAIT_FOR_APP_CB */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_DIAG_WAIT_FOR_APP_CB is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_DIAG_WAIT_FOR_APP_CB];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_DIAG_WAIT_FOR_APP_CB] = 0;
         }
#endif /*osdUseHeapAlarm*/
         APP_DIAG_vHandlePendingResponseFromApplication();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_DIAG_RETRY_BUSY */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_DIAG_RETRY_BUSY is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_DIAG_RETRY_BUSY];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_DIAG_RETRY_BUSY] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskDiagnoseRequest);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_HOST_HANDLE_DIAG_REQ */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_HOST_HANDLE_DIAG_REQ is expired */
         (*aPtr) = osAlarmCycleTime[CTA_HOST_HANDLE_DIAG_REQ];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_HOST_HANDLE_DIAG_REQ] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsHostTask_10ms,evHostTaskHandleDiagReq);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_HOST_SELF_DIAG_TIMER */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_HOST_SELF_DIAG_TIMER is expired */
         (*aPtr) = osAlarmCycleTime[CTA_HOST_SELF_DIAG_TIMER];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_HOST_SELF_DIAG_TIMER] = 0;
         }
#endif /*osdUseHeapAlarm*/
         APP_CAN_cbHostSelfDiagnosisTimer();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }
} /* END OF alarm checking function */
#endif /*osdUseGeneratedFastAlarm*/



osStackDataType osSystemStack[75];
osStackDataType osSupervisorStack[50];
osStackDataType osIrqStack[osdIrqStackSize/4]; /* PRQA S 1504 */  /* PRQA S 3408 */ /* stack might be accessed from assembler code */

/* Task stacks generated in dependence on the stack model: */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack0 [150];  /* PRQA S 1504 */  /* PRQA S 3408 */ /* stack might be accessed from assembler code */ 
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack1 [150];  /* PRQA S 1504 */  /* PRQA S 3408 */ /* stack might be accessed from assembler code */ 
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack2 [60];  /* PRQA S 1504 */  /* PRQA S 3408 */ /* stack might be accessed from assembler code */ 
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack3 [95];  /* PRQA S 1504 */  /* PRQA S 3408 */ /* stack might be accessed from assembler code */ 
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack4 [65];  /* PRQA S 1504 */  /* PRQA S 3408 */ /* stack might be accessed from assembler code */ 
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack5 [50];  /* PRQA S 1504 */  /* PRQA S 3408 */ /* stack might be accessed from assembler code */ 

osqROM0 osStackPtrType osqROM1 const osqROM2 osqROM3 oskTcbStackTop[osdNumberOfAllTasks]=
{
   osAssignStack(osTaskStack0),
   osAssignStack(osTaskStack1),
   osAssignStack(osTaskStack2),
   osAssignStack(osTaskStack3),
   osAssignStack(osTaskStack4),
   osAssignStack(osTaskStack5),
};

#if osdStackCheck
osqROM0 osStackPtrType osqROM1 const osqROM2 osqROM3 oskTcbStackBottom[osdNumberOfAllTasks]=
{
   osBottomOfStack(osTaskStack0),
   osBottomOfStack(osTaskStack1),
   osBottomOfStack(osTaskStack2),
   osBottomOfStack(osTaskStack3),
   osBottomOfStack(osTaskStack4),
   osBottomOfStack(osTaskStack5),
};

#endif

#if (CC == BCC2) || (CC == ECC2)
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_0[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_1[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_2[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_3[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_4[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_5[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_6[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_7[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_8[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_9[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_10[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_11[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_12[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_13[2];

osqROM0 osqPTcbRAM1 osqPTcbRAM2 TaskType osqPTcbRAM3 * osqROM1 const osqROM2 osqROM3 oskQActivationQueues[osdNumberOfPriorities]=
{
   osQTaskActivation_0,
   osQTaskActivation_1,
   osQTaskActivation_2,
   osQTaskActivation_3,
   osQTaskActivation_4,
   osQTaskActivation_5,
   osQTaskActivation_6,
   osQTaskActivation_7,
   osQTaskActivation_8,
   osQTaskActivation_9,
   osQTaskActivation_10,
   osQTaskActivation_11,
   osQTaskActivation_12,
   osQTaskActivation_13,
};

osqROM0 osqROM1 const osqROM2 osQEntryCountType osqROM3 oskQMaxActivations[osdNumberOfPriorities]=
{
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
};

#endif

osqROM0 osTaskFctType osqROM1 const osqROM2 osqROM3 oskTcbTaskStartAddress[osdNumberOfAllTasks] = {
   OsHostTask_10msfunc,
   OsAppTask_event_100msfunc,
   OsSystemTask_eventfunc,
   OsDriverTask_1msfunc,
   OsMonitorTask_50msfunc,
   OsDatabaseTask_eventfunc,
};

#if osdMixedPreempt
osqROM0 osqROM1 const osqROM2 osTaskPreemptionType osqROM3 oskTcbTaskPreemption[osdNumberOfAllTasks] = {
   osdTaskTypeNonPreempt,
   osdTaskTypePreempt,
   osdTaskTypeNonPreempt,
   osdTaskTypePreempt,
   osdTaskTypePreempt,
   osdTaskTypePreempt,
};
#endif /* osdMixedPreempt */

osqROM0 osqROM1 const osqROM2 osTaskFlagType osqROM3 oskTcbTaskFlags[osdNumberOfAllTasks] = {
 osdTaskFlagScheduleAllowed,
 osdTaskFlagScheduleAllowed,
 osdTaskFlagScheduleAllowed,
 osdTaskFlagScheduleAllowed,
 osdTaskFlagScheduleAllowed,
 osdTaskFlagScheduleAllowed,
};

osqROM0 osqROM1 const osqROM2 uint8 osqROM3 oskTcbAutoStart[osdNumberOfAllTasks] = {
   0x01, /* OsHostTask_10ms*/
   0x00, /* OsAppTask_event_100ms */
   0x00, /* OsSystemTask_event */
   0x00, /* OsDriverTask_1ms */
   0x00, /* OsMonitorTask_50ms */
   0x00, /* OsDatabaseTask_event */
};

osqROM0 osqROM1 const osqROM2 osPrioFlagType osqROM3 oskTcbReadyPrioMask[osdNumberOfAllTasks] = {
   0x02000000U,
   0x00800000U,
   0x00400000U,
   0x00200000U,
   0x00080000U,
   0x00040000U,
};

#if (osdRTSize > 1)
osqROM0 osqROM1 const osqROM2 osPrioOffsetType osqROM3 oskTcbReadyPrioOffset[osdNumberOfAllTasks] = {
   0x00,
   0x00,
   0x00,
   0x00,
   0x00,
   0x00,
};
#endif

osqROM0 osqROM1 const osqROM2 osPrioType osqROM3 oskTcbHomePrio[osdNumberOfAllTasks]=
{
   6,
   8,
   9,
   10,
   12,
   13,
};

#if (CC == BCC2) || (CC == ECC2)
osqROM0 osqROM1 const osqROM2 osActivationCountType osqROM3 oskTcbAllowedActivations[osdNumberOfAllTasks]=
{
   1,
   1,
   1,
   1,
   1,
   1,
};
#endif

#if (osdGHSDebugSupport==1)
osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 * osqROM1 const osqROM2 osqROM3 oskTcbTaskName[osdNumberOfAllTasks]=
{
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"OsHostTask_10ms",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"OsAppTask_event_100ms",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"OsSystemTask_event",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"OsDriverTask_1ms",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"OsMonitorTask_50ms",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"OsDatabaseTask_event",
};
osqROM0 osqROM1 const osqROM2 uint16 osqROM3 oskTcbOILPrio[osdNumberOfAllTasks]=
{
   10,
   8,
   7,
   4,
   2,
   1,
};
#endif

#if osdEnableProcedures
osqROM0 osqROM1 const osqROM2 osContextOverlayType osqROM3 oskTcbContextOverlay[osdNumberOfAllTasks] = {
   0,
   0,
   0,
   0,
   0,
   0,
};
#endif /* osdEnableProcedures */

/* Resources */

#if ((!defined(osdGetResourceNotUsed)) || (!defined(osdReleaseResourceNotUsed)))
#if (osdGHSDebugSupport==1)
osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 * osqROM1 const osqROM2 osqROM3 oskResName[osdNumberOfAllResources]=
{
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CK5050_WRITE_Resource",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"EEPROM_LockResource",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"UART_LockResource",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CRC_LockResource",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"POOL_LockResource",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"DEH_LockResource",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"EEPROM_LAYOUT_LockResource",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"RES_SCHEDULER",
};

#endif

#if (STATUS_LEVEL == EXTENDED_STATUS) && osdEnableAssertions
osqROM0 osqROM1 const osqROM2 osResAccessMaskType osqROM3 oskResAccessMask[osdNumberOfAllResources][1]={
/* sequence of taskNumbers (!not priorities) */
   {    0x40000000U,   } /* CK5050_WRITE_Resource*/
  ,{    0xfc000000U,   } /* EEPROM_LockResource*/
  ,{    0xfc000000U,   } /* UART_LockResource*/
  ,{    0x08000000U,   } /* CRC_LockResource*/
  ,{    0xd0000000U,   } /* POOL_LockResource*/
  ,{    0xfc000000U,   } /* DEH_LockResource*/
  ,{    0xfc000000U,   } /* EEPROM_LAYOUT_LockResource*/
  ,{    0xfc000000U,   } /* RES_SCHEDULER*/
};

#endif /* (STATUS_LEVEL == EXTENDED_STATUS) && osdEnableAssertions */

osqROM0 osqROM1 const osqROM2 osPrioType osqROM3 oskResCeilingPrio[osdNumberOfAllResources]=
{
   (osPrioType)7,
   (osPrioType)5,
   (osPrioType)4,
   (osPrioType)11,
   (osPrioType)3,
   (osPrioType)2,
   (osPrioType)1,
   (osPrioType)0,
};

osqROM0 osqROM1 const osqROM2 osPrioFlagType osqROM3 oskResCeilingPrioMask[osdNumberOfTaskResources]=
{
   0x01000000U,
   0x04000000U,
   0x08000000U,
   0x00100000U,
   0x10000000U,
   0x20000000U,
   0x40000000U,
   0x80000000U,
};

#if (osdRTSize > 1)
osqROM0 osqROM1 const osqROM2 osPrioOffsetType osqROM3 oskResCeilingPrioOffset[osdNumberOfTaskResources]=
{
   0x00,
   0x00,
   0x00,
   0x00,
   0x00,
   0x00,
   0x00,
   0x00,
};
#endif

#endif /*((!defined(osdGetResourceNotUsed)) || (!defined(osdReleaseResourceNotUsed))) */

#if (osdNumberOfAllTasks>0)
#if ((osdNumberOfInternalResources > 0)||(osdLib==1))
osqROM0 osqROM1 const osqROM2 osPrioType osqROM3 oskResInternalCeilingPrio[osdNumberOfAllTasks]=
{
   (osPrioType) 0,
   (osPrioType) 0,
   (osPrioType) 0,
   (osPrioType) 0,
   (osPrioType) 0,
   (osPrioType) 0,
};

osqROM0 osqROM1 const osqROM2 osPrioFlagType osqROM3 oskResInternalCeilingPrioMask[osdNumberOfAllTasks]=
{
   0,
   0,
   0,
   0,
   0,
   0,
};

 #if ((osdRTSize > 1)||(osdLib==1))
osqROM0 osqROM1 const osqROM2 osPrioOffsetType osqROM3 oskResInternalCeilingPrioOffset[osdNumberOfAllTasks]=
{
   0,
   0,
   0,
   0,
   0,
   0,
};

#endif
#endif

#else
osqROM0 osqROM1 const osqROM2 osPrioType osqROM3 oskResInternalCeilingPrio[1]={0};
osqROM0 osqROM1 const osqROM2 osPrioFlagType osqROM3 oskResInternalCeilingPrioMask[1]={0};
osqROM0 osqROM1 const osqROM2 osPrioOffsetType osqROM3 oskResInternalCeilingPrioOffset[1]={0};
#endif
/* Counters */

/* Alarms */

#if (osdNumberOfAlarmActivateTask > 0) || (osdNumberOfAlarmSetEvent > 0)
/* task to activate or to event */
osqROM0 osqROM1 const osqROM2 TaskType osqROM3 oskAlarmTask[osdNumberOfAlarms]={
   OsHostTask_10ms, /* CTA_HOST*/
   OsMonitorTask_50ms, /* CTA_MONITOR*/
   OsDriverTask_1ms, /* CTA_DRIVER*/
   OsDatabaseTask_event, /* CTA_DATABASE_EEPROM_WRITE*/
   OsAppTask_event_100ms, /* CTA_APP*/
   OsSystemTask_event, /* CTA_SYSTEM*/
   OsAppTask_event_100ms, /* CTA_ERM_PENDING*/
   OsDatabaseTask_event, /* CTA_WD*/
   OsMonitorTask_50ms, /* CTA_MONITOR_AUDIO*/
   0, /* 0 for ALARMCALLBACK */
   0, /* 0 for ALARMCALLBACK */
   OsAppTask_event_100ms, /* CTA_APP_DIAG_RETRY_BUSY*/
   OsHostTask_10ms, /* CTA_HOST_HANDLE_DIAG_REQ*/
   0, /* 0 for ALARMCALLBACK */
};
#else
 #if osdLib
 osqROM0 osqROM1 const osqROM2 TaskType osqROM3 oskAlarmTask[1]={0};
 #endif
#endif

#if osdNumberOfAlarmSetEvent > 0
osqROM0 osqROM1 const osqROM2 EventMaskType osqROM3 oskAlarmEvent[osdNumberOfAlarms]={
   evActivateHostTask_10ms, /* CTA_HOST*/
   evActivateMonitorTask_50ms, /* CTA_MONITOR*/
   evActivateDriverTask_1ms, /* CTA_DRIVER*/
   evDatabaseCyclicEepromWrite, /* CTA_DATABASE_EEPROM_WRITE*/
   evActivateAppTask_event_100ms, /* CTA_APP*/
   evActivateSystemTask_event, /* CTA_SYSTEM*/
   evAppTaskERMPending, /* CTA_ERM_PENDING*/
   evTriggerWD, /* CTA_WD*/
   evMonitorTask_MonitorAudio_for_DTC, /* CTA_MONITOR_AUDIO*/
   0, /* 0 for ActivateTask or ALARMCALLBACK */
   0, /* 0 for ActivateTask or ALARMCALLBACK */
   evAppTaskDiagnoseRequest, /* CTA_APP_DIAG_RETRY_BUSY*/
   evHostTaskHandleDiagReq, /* CTA_HOST_HANDLE_DIAG_REQ*/
   0, /* 0 for ActivateTask or ALARMCALLBACK */
};
#else
 #if osdLib
 osqROM0 osqROM1 const osqROM2 EventMaskType osqROM3 oskAlarmEvent[1]={0};
 #endif
#endif

#if osdNumberOfAlarmCallback > 0
/* alarm callback function */
osqROM0 osAlarmCallbackType osqROM1 const osqROM2 osqROM3 oskAlarmCallback[osdNumberOfAlarms]={
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   CSHDL_cbAlarmCallbackOneHourModeOver, /* CTA_ONE_HOUR_MODE*/
   APP_DIAG_vHandlePendingResponseFromApplication, /* CTA_APP_DIAG_WAIT_FOR_APP_CB*/
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   APP_CAN_cbHostSelfDiagnosisTimer, /* CTA_HOST_SELF_DIAG_TIMER*/
};
#else
 #if osdLib
 osqROM0 osAlarmCallbackType osqROM1 const osqROM2 osqROM3 oskAlarmCallback[1]={(osAlarmCallbackType)0};
 #endif
#endif

#if (osdNumberOfAlarmCallback > 0) || (osdNumberOfAlarmSetEvent > 0)
osqROM0 osqROM1 const osqROM2 uint8 osqROM3 oskAlarmAction[osdNumberOfAlarms]={
   osdAlarmActionSetEvent, /* CTA_HOST*/
   osdAlarmActionSetEvent, /* CTA_MONITOR*/
   osdAlarmActionSetEvent, /* CTA_DRIVER*/
   osdAlarmActionSetEvent, /* CTA_DATABASE_EEPROM_WRITE*/
   osdAlarmActionSetEvent, /* CTA_APP*/
   osdAlarmActionSetEvent, /* CTA_SYSTEM*/
   osdAlarmActionSetEvent, /* CTA_ERM_PENDING*/
   osdAlarmActionSetEvent, /* CTA_WD*/
   osdAlarmActionSetEvent, /* CTA_MONITOR_AUDIO*/
   osdAlarmActionCallback, /* CTA_ONE_HOUR_MODE*/
   osdAlarmActionCallback, /* CTA_APP_DIAG_WAIT_FOR_APP_CB*/
   osdAlarmActionSetEvent, /* CTA_APP_DIAG_RETRY_BUSY*/
   osdAlarmActionSetEvent, /* CTA_HOST_HANDLE_DIAG_REQ*/
   osdAlarmActionCallback, /* CTA_HOST_SELF_DIAG_TIMER*/
};
#else
 #if (osdNumberOfAlarms == 0) || osdLib
  osqROM0 osqROM1 const osqROM2 uint8 osqROM3 oskAlarmAction[1]={0};
 #endif
#endif

/* static alarm time */
osqROM0 osqROM1 const osqROM2 TickType osqROM3 oskStaticAlarmTime[osdNumberOfAlarms]={
   0, /* no static alarm: CTA_HOST*/
   0, /* no static alarm: CTA_MONITOR*/
   0, /* no static alarm: CTA_DRIVER*/
   0, /* no static alarm: CTA_DATABASE_EEPROM_WRITE*/
   0, /* no static alarm: CTA_APP*/
   0, /* no static alarm: CTA_SYSTEM*/
   0, /* no static alarm: CTA_ERM_PENDING*/
   0, /* no static alarm: CTA_WD*/
   0, /* no static alarm: CTA_MONITOR_AUDIO*/
   0, /* no static alarm: CTA_ONE_HOUR_MODE*/
   0, /* no static alarm: CTA_APP_DIAG_WAIT_FOR_APP_CB*/
   0, /* no static alarm: CTA_APP_DIAG_RETRY_BUSY*/
   0, /* no static alarm: CTA_HOST_HANDLE_DIAG_REQ*/
   0, /* no static alarm: CTA_HOST_SELF_DIAG_TIMER*/
};

/* static cycle time */
osqROM0 osqROM1 const osqROM2 TickType osqROM3 oskStaticAlarmCycleTime[osdNumberOfAlarms]={
   0, /* no static alarm: CTA_HOST */
   0, /* no static alarm: CTA_MONITOR */
   0, /* no static alarm: CTA_DRIVER */
   0, /* no static alarm: CTA_DATABASE_EEPROM_WRITE */
   0, /* no static alarm: CTA_APP */
   0, /* no static alarm: CTA_SYSTEM */
   0, /* no static alarm: CTA_ERM_PENDING */
   0, /* no static alarm: CTA_WD */
   0, /* no static alarm: CTA_MONITOR_AUDIO */
   0, /* no static alarm: CTA_ONE_HOUR_MODE */
   0, /* no static alarm: CTA_APP_DIAG_WAIT_FOR_APP_CB */
   0, /* no static alarm: CTA_APP_DIAG_RETRY_BUSY */
   0, /* no static alarm: CTA_HOST_HANDLE_DIAG_REQ */
   0, /* no static alarm: CTA_HOST_SELF_DIAG_TIMER */
};

/* Autostart */
osqROM0 osqROM1 const osqROM2 uint8 osqROM3 oskAlarmAutoStart[osdNumberOfAlarms]={
   0x00, /* CTA_HOST */
   0x00, /* CTA_MONITOR */
   0x00, /* CTA_DRIVER */
   0x00, /* CTA_DATABASE_EEPROM_WRITE */
   0x00, /* CTA_APP */
   0x00, /* CTA_SYSTEM */
   0x00, /* CTA_ERM_PENDING */
   0x00, /* CTA_WD */
   0x00, /* CTA_MONITOR_AUDIO */
   0x00, /* CTA_ONE_HOUR_MODE */
   0x00, /* CTA_APP_DIAG_WAIT_FOR_APP_CB */
   0x00, /* CTA_APP_DIAG_RETRY_BUSY */
   0x00, /* CTA_HOST_HANDLE_DIAG_REQ */
   0x00, /* CTA_HOST_SELF_DIAG_TIMER */
};


#if (osdGHSDebugSupport==1)
osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 * osqROM1 const osqROM2 osqROM3 oskAlarmName[osdNumberOfAlarms]=
{
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_HOST",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_MONITOR",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_DRIVER",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_DATABASE_EEPROM_WRITE",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_SYSTEM",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_ERM_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_WD",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_MONITOR_AUDIO",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_ONE_HOUR_MODE",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_DIAG_WAIT_FOR_APP_CB",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_DIAG_RETRY_BUSY",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_HOST_HANDLE_DIAG_REQ",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_HOST_SELF_DIAG_TIMER",
};

#endif

osqFunc1 void osqFunc2 osInitTimer(void)
{

   *((volatile uint32*)osdRTICINT) &=~osdRTICmpENA;				/* disable compare interrupt */
   *((volatile uint32*)osdREQMASK) &=~osdRTIIntFlag;   /* disable interrupt */
   *((volatile uint32*)osdFIRQPR)  &=~osdRTIIntFlag;   			/* interrupt is IRQ */
   *((volatile uint32*)osdRTIPCTL)  = (*((volatile uint32*)osdRTIPCTL) & 0xfffff800) | osdClockDividerReg;   /* set prescaler */
   *((volatile uint32*)osdRTICMP)   = (*((volatile uint32*)osdRTICNTR) >> 11) + osdClockReloadReg;   /* RTICMPx */
   *((volatile uint32*)osdRTICINT) &=~osdRTICmpFlag;   			/* clear compare flag */
   *((volatile uint32*)osdINTREQ)  &=~osdRTIIntFlag;   			/* clear pending flag */
   *((volatile uint32*)osdREQMASK) |= osdRTIIntFlag;   /* enable interrupt  */
   *((volatile uint32*)osdRTICINT) |= osdRTICmpENA;   			/* enable compare interrupt */
   *((volatile uint32*)osdRTICNTEN) = 0;						/* count enable */
}/*ENDOF osInitTimer*/



ISR(osTimerInt) /* PRQA S 1503 */  /* called from assembler code */
{

   OS_TI_ENTRY();

   *((volatile uint32*)osdREQMASK) &=~osdRTIIntFlag;   /* disable interrupt */
   *((volatile uint32*)osdRTICMP) = (*((volatile uint32*)osdRTICMP) & 0x1fffff) + osdClockReloadReg;   /* RTICMPx */
   *((volatile uint32*)osdRTICINT) &= ~osdRTICmpFlag;   		/* clear compare flag */
#if osdUseCounterAPI
   osCounter[SystemTimer]++;
#else
   osSystemCounter++;
#endif
#if (osdNumberOfAlarms > 0)
#ifndef osdUseGeneratedFastAlarm
 #if (osdEnableIntNesting==0)
   osEnableLevel();
 #endif
   osWorkAlarms();
 #if (osdEnableIntNesting==0)
   osDisableLevel();
 #endif
#else
 #if (osdEnableIntNesting==1)
   osDisableLevel();
 #endif
   osCheckAlarms();
 #if (osdEnableIntNesting==1)
   osSetAlarmLevel();
 #endif
#endif
#endif
   *((volatile uint32*)osdREQMASK) |= osdRTIIntFlag;   /* enable interrupt  */
   OS_TI_EXIT();
}/*ENDOF osTimerInt*/


osqFunc1 void osqFunc2 osInitISRprios(void)
{
}

/* END OF F:\PROJECTS\ADR-PORSCHE\PORSCHE_ADR_DEVELOPMENT_TRUNK\MOD\MOD_OSEK_DYN\CFG\tcb\tcb.c */

