/* -----------------------------------------------------------------------------
  Filename:    appdesc.c
  Description: Implementation example for the proper usage with CANdesc.
                
                Manufacturer: Porsche AG
                EcuDocFile:   C:\DOKUME~1\rammelt\LOKALE~1\Temp\CANdescBasic1.desc
                Variant:      CommonDiagnostics

  Generated by CANdelaGen, Wed Feb 15 08:51:04 2012
 
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2010 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ History
 ----------------------------------------------------------------------------- */

/* ----------------------------------------------------------------------------
  Please note, that the demo and example programs only show special aspects of 
  the software. With regard to the fact that these programs are meant for 
  demonstration purposes only, Vector Informatik´s liability shall be expressly 
  excluded in cases of ordinary negligence, to the extent admissible by law or 
  statute.
  ---------------------------------------------------------------------------- */

/* 
------------------------------------------------------------------------------------------------------------------------
                                             A U T H O R   I D E N T I T Y                                              
------------------------------------------------------------------------------------------------------------------------
Initials   Name                  Company                                                                                
---------- --------------------- ---------------------------------------------------------------------------------------
Ktw        Katrin Thurow         Vector Informatik GmbH                                                                 
Mhe        Matthias Heil         Vector Informatik GmbH                                                                 
Sa         Mishel Shishmanyan    Vector Informatik GmbH                                                                 
------------------------------------------------------------------------------------------------------------------------
                                            R E V I S I O N   H I S T O R Y                                             
------------------------------------------------------------------------------------------------------------------------
Date       Version  Author Modification type Issue Id      Affects                        Description                    
---------- -------- ------ ----------------- ------------- ------------------------------ -------------------------------
2006-10-20 05.00.00
                    Sa     Modified          ESCAN00016884 UDS                            ComControl service compliance with the latest ISO-UDS (2005-05-29).
                    Sa     Modified          ESCAN00018098 All                            Unified security access management and API.
                    Sa     Added             ESCAN00017752 All                            OBD II compliance with regard to the NRC usage and response behavior.
                    Sa     Added             ESCAN00018099 All                            Add support for CANdela format 5.0.
2007-02-16 05.01.00
                    Sa     Fixed             ESCAN00018114 Porsche AG(UDS)                CANdesc not compilable if permanent repeated call is turned on.
                    Sa     Fixed             ESCAN00018916 Porsche AG(UDS)                Compile error on multi-channel system and service $28 support.
                    Sa     Modified          ESCAN00019645 Porsche AG(UDS)                API DescSendPosRespFBL can send wrong response if illegal parameter value used.
                    Sa     Fixed             ESCAN00018576 All                            Service instance linear look-up routine fails finding a requested service.
                    Sa     Fixed             ESCAN00019220 All                            Compile error for wrong syntax after preprocesing defines: DescUsdtNetStateTask and DescUsdtNetTimerTask.
                    Sa     Fixed             ESCAN00019334 All                            Generator: Unable to generate CANdesc with multi channel TP and CANgen newer than 4.30.03.
                    Sa     Modified          ESCAN00018872 All                            Wrong main-handler comment for constants names kDescReqTypePhys (-Func).
                    Sa     Modified          ESCAN00019321 All                            Remove file-path from the #include "node.h"
                    Sa     Modified          ESCAN00019735 All                            Use CPU type optimized data definition types (uintx_least).
                    Sa     Added             ESCAN00018320 All                            Generate P2 and P2* task-call constants with a justification of one task call less.
                    Sa     Added             ESCAN00018592 All                            DescRingBufferCancel API added.
2007-04-13 05.02.00
                    Sa     Modified          ESCAN00020245 Porsche AG(UDS)                Unusable API DescTransmitSingleFrame declared.
                    Sa     Added             ESCAN00020069 UDS                            Support for unified PID application handling.
2007-05-30 05.03.00
                    Sa     Fixed             ESCAN00020975 Porsche AG(UDS)                Rapid shut-down left on service $11 $04
                    Sa     Fixed             ESCAN00020760 UDS                            Service $22 responds with wrong NRC $13 instead of $31 in case single DID mode has been selected
                    Sa     Modified          ESCAN00020840 All                            Compiler error message on local variable pointer to ROM using V_MEMROM0 define
                    Sa     Modified          ESCAN00019437 All                            Compiler error in desc.c with mem-model huge
2007-07-23 05.04.00
                    Sa     Added             ESCAN00021530 UDS                            Support for custom rx communication path handling on service $28
                    Sa     Fixed             ESCAN00021336 All                            use lower case characters for names of generated files (AppDesc.h => appdesc.h)
                    Sa     Modified          ESCAN00021523 All                            Removed the first frame length dependency on Vector TP for for ring-buffer usage
                    Sa     Added             ESCAN00021528 All                            Stopping RepeatedServiceCall in RingBufferCancel
                    Sa     Added             ESCAN00021567 All                            Use case catch on RingBuffer usage with SPRMIB=1
2007-09-07 05.05.00
                    Sa     Added             ESCAN00022078 Porsche AG(UDS)                Compliance to PAG specification version 1.5
                    Sa     Fixed             ESCAN00021610 UDS                            Incorrect NRC on an invalidly formatted writeDataByIdentifier ($2e) request for non-writeable DID
                    Sa     Fixed             ESCAN00021615 UDS                            Incorrect NRC on service with parameter identifier not supported in active session
                    Sa     Fixed             ESCAN00021800 UDS                            Wrong response lenght on service $22 in single DID mode
                    Sa     Added             ESCAN00022074 UDS                            Unified PID support on service $2E
                    Sa     Added             ESCAN00022075 UDS                            Unified PID support on service $22 in single PID mode
                    Sa     Fixed             ESCAN00022068 All                            Include appDesc.h changed to appdesc.h
                    Sa     Modified          ESCAN00021654 All                            Explicit suppression of NRC $11 on functional request
                    Sa     Modified          ESCAN00021252 All                            Compiler warnings for unreferenced variable and function declaration
                    Sa     Modified          ESCAN00022254 All                            Adaptions for the interrupt support of the latest VStdLib version
                    Sa     Added             ESCAN00021847 All                            Access to the current communication parameters
2007-10-22 05.05.01
                    Sa     Modified          ESCAN00022853 UDS                            Allow for service $10 the P2 time report not to be present
2007-10-26 05.05.02
                    -      -                 -             -                              No relevant changes available in this version.
2007-11-15 05.05.03
                    Sa     Added             ESCAN00023231 All                            Support multiple ECU numbers   
2007-12-17 05.05.04
                    -      -                 -             -                              No relevant changes available in this version.
2007-12-20 05.06.00
                    Sa     Modified          ESCAN00022853 UDS                            Allow for service $10 the P2 time report not to be present
                    Sa     Modified          ESCAN00022868 UDS                            Consider CDD files having only SID based information (CANdescBasic like)
                    Sa     Added             ESCAN00023231 All                            Support multiple ECU numbers   
2008-01-22 05.06.01
                    Sa     Modified          ESCAN00024147 UDS                            Specify suppressPosRes DescMsgContext member as read-only item and not read-write
                    Sa     Fixed             ESCAN00026046 All                            CANdesc responds on wrong CAN Id
                    Mhe    Added             ESCAN00024011 All                            Support dynamic normal addressing
                    Mhe    Added             ESCAN00024019 All                            Support far RAM Tp API         
2008-02-04 05.06.02
                    -      -                 -             -                              No relevant changes available in this version.
2008-01-11 05.06.03
                    -      -                 -             -                              No relevant changes available in this version.
2008-03-14 05.06.04
                    Mhe    Added             ESCAN00024951 UDS                            Internal support for read/write memory by address
                    Sa     Added             ESCAN00024929 UDS                            Allow unified PID handling for service $22 without multiple PID support
2008-04-03 05.06.05
                    Sa     Fixed             ESCAN00025393 Porsche AG(UDS)                Compile error on function call 'DescSendSpontaneousResponse'
                    Sa     Fixed             ESCAN00025753 UDS                            Supported PIDs will not be recognized if service $2F is also available in the system
2008-04-21 05.06.06
                    Sa     Fixed             ESCAN00026335 All                            Compile error with DynamicTP   
2008-05-23 05.06.07
                    Sa     Fixed             ESCAN00027058 UDS                            Compile error on generated main-handler with ring-buffer access an single PID mode
                    Sa     Fixed             ESCAN00026907 All                            On TMS320 wrong vstdlib memcopy API used
                    Sa     Fixed             ESCAN00027059 All                            Array out of boundary access error on generated main-handler with ring-buffer access
                    Sa     Modified          ESCAN00027061 All                            Minor DescICN driver optimization
                    Sa     Modified          ESCAN00027063 All                            MainHandler req-/resDataLen has misleading description for CANdescBasic
                    Ktw    Modified          ESCAN00027057 All                            Compile error on missing semicolon for DescSetNpmOnCanChannelActive macro expansion
                    Mhe    Added             ESCAN00026452 All                            Posthandler support for generated $23
2008-05-26 05.06.08
                    Sa     Fixed             ESCAN00027060 UDS                            Wrong assertion in case of negative response on service 0x22 and multiple PID mode
                    Sa     Fixed             ESCAN00027085 UDS                            Compile error on configurations without service $2A or $2C
                    Sa     Fixed             ESCAN00027084 All                            Compile error on non TMS320 platforms
2008-06-05 05.06.09
                    -      -                 -             -                              No relevant changes available in this version.
2008-06-16 05.06.10
                    -      -                 -             -                              No relevant changes available in this version.
2008-06-27 05.07.00
                    Sa     Fixed             ESCAN00027058 UDS                            Compile error on generated main-handler with ring-buffer access an single PID mode
                    Sa     Fixed             ESCAN00027060 UDS                            Wrong assertion in case of negative response on service 0x22 and multiple PID mode
                    Sa     Modified          ESCAN00024147 UDS                            Specify suppressPosRes DescMsgContext member as read-only item and not read-write
                    Sa     Added             ESCAN00024929 UDS                            Allow unified PID handling for service $22 without multiple PID support
                    Mhe    Added             ESCAN00024951 UDS                            Internal support for read/write memory by address
                    Sa     Fixed             ESCAN00026046 All                            CANdesc responds on wrong CAN Id
                    Sa     Fixed             ESCAN00026907 All                            On TMS320 wrong vstdlib memcopy API used
                    Sa     Fixed             ESCAN00027059 All                            Array out of boundary access error on generated main-handler with ring-buffer access
                    Sa     Modified          ESCAN00027061 All                            Minor DescICN driver optimization
                    Sa     Modified          ESCAN00027063 All                            MainHandler req-/resDataLen has misleading description for CANdescBasic
                    Sa     Modified          ESCAN00027057 All                            Compile error on missing semicolon for DescSetNpmOnCanChannelActive macro expansion
                    Mhe    Added             ESCAN00024011 All                            Support dynamic normal addressing
                    Mhe    Added             ESCAN00024019 All                            Support far RAM Tp API         
                    Mhe    Added             ESCAN00026452 All                            Posthandler support for generated $23
2008-07-11 05.07.01
                    -      -                 -             -                              No relevant changes available in this version.
2008-08-08 05.07.02
                    Sa     Fixed             ESCAN00028409 All                            No response on request         
2008-10-02 05.07.03
                    Ktw    Modified          ESCAN00030418 Porsche AG(UDS)                Positive response of FBL is not sent in certain use cases
                    Sa     Modified          ESCAN00029770 All                            Compiler warning for enumeration item with value 0xFF on enum-type = char
                    Sa     Added             ESCAN00030116 All                            Provide IsoTp-Callback prototypes in desc.h/danisisotp.h
                    Sa     Added             ESCAN00030087 All                            Support of internal diagnostic requests over IsoTP
2008-10-30 05.07.04
                    Sa     Fixed             ESCAN00030759 All                            Generator stops with internal error during processing 'MainHandlerOnProtocolService' that contains muxed component
                    Sa     Fixed             ESCAN00030981 All                            Switch to surpress multitiple addressing check
                    Sa     Fixed             ESCAN00029915 All                            CANdesc files can not be written
                    Sa     Modified          ESCAN00031158 All                            Ring-buffer feature enabled for non-ISO-TP DANIS drivers
                    Sa     Added             ESCAN00031156 All                            Added DANIS abstraction for testerId and comChannel
2008-11-26 05.07.05
                    -      -                 -             -                              No relevant changes available in this version.
2008-12-15 05.07.06
                    Ktw    Fixed             ESCAN00031533 All                            Compiler Warning: Unused variable tpTxChannel
2009-02-02 05.07.07
                    Sa     Fixed             ESCAN00027182 All                            Compiler Warning: variable "svcInstFailedBytePosMask" is possibly uninitialized
2009-02-17 05.07.08
                    -      -                 -             -                              No relevant changes available in this version.
2009-03-09 05.07.09
                    -      -                 -             -                              No relevant changes available in this version.
2009-03-12 05.07.10
                    -      -                 -             -                              No relevant changes available in this version.
2009-03-16 05.07.11
                    -      -                 -             -                              No relevant changes available in this version.
2009-03-16 05.07.12
                    -      -                 -             -                              No relevant changes available in this version.
2009-04-15 05.07.13
                    -      -                 -             -                              No relevant changes available in this version.
2009-05-06 05.07.14
                    Sa     Modified          ESCAN00034880 UDS                            Disable call of DescStateTask() in DescTask() if HIGH_PERFOMANCE_MODE is active
                    Sa     Added             ESCAN00035198 UDS                            New API DescIsSuppressPosResBitSet
                    Sa     Fixed             ESCAN00034934 All                            Wrong null-terminated and leading size byte string data object total length calculation
2009-06-19 05.07.15
                    Ktw    Fixed             ESCAN00035554 All                            Null pointer access in DanisBoschTp
2009-07-01 05.07.16
                    -      -                 -             -                              No relevant changes available in this version.
2009-07-13 05.07.17
                    -      -                 -             -                              No relevant changes available in this version.
2009-08-11 05.07.18
                    Sa     Fixed             ESCAN00036995 All                            Compile warning on redeclaration of function DescGetBuffer
                    Sa     Fixed             ESCAN00036138 All                            Compiler warning on redundant declaration of DescGetBuffer
                    Sa     Modified          ESCAN00036996 All                            Switching between ANSI C and hardware optimized bit-type
                    Sa     Modified          ESCAN00037096 All                            Undo ESCAN00036465             
2009-08-31 05.07.19
                    -      -                 -             -                              No relevant changes available in this version.
2009-10-14 05.07.20
                    -      -                 -             -                              No relevant changes available in this version.
2009-11-17 05.07.21
                    Sa     Fixed             ESCAN00039237 All                            Compiler Warning: possible redundant expression / useless assignment
                    Sa     Modified          ESCAN00040135 All                            CanChannelIdentityAssignment is generated in RAM section
2010-02-02 05.07.22
                    -      -                 -             -                              No relevant changes available in this version.
2010-02-12 05.07.23
                    -      -                 -             -                              No relevant changes available in this version.
2010-05-12 05.07.24
                    Sa     Fixed             ESCAN00042963 All                            DescCopyToCan API does not support CAN message buffers located in the gpage
2010-05-31 05.07.25
                    Sa     Fixed             ESCAN00043021 Porsche AG(UDS)                Compile error for wrong pointer types used in API DescSendSPontaneousResponse
                    Sa     Fixed             ESCAN00041576 All                            Compiler warning for constant expression in DescDispatcher
                    Sa     Fixed             ESCAN00043240 All                            Compiler error for missing data types DescDynDidMemBlockAddress and DescDynDidMemBlockSize
2010-07-16 05.07.26
                    Sa     Fixed             ESCAN00037465 UDS                            Compiler warning: parameter "pMsgContext" not used
                    Sa     Fixed             ESCAN00044189 UDS                            Valid service 0x28 request rejected with negative response
                    Sa     Fixed             ESCAN00044049 UDS                            Compiler warning: condition is always false
                    Sa     Fixed             ESCAN00044050 All                            Compiler warning: condition is always false
                    Sa     Fixed             ESCAN00044197 All                            Not all buffers used in DANIS can be located in far RAM
                    Sa     Added             ESCAN00044127 All                            Support for DANIS adapter specific available buffer size information to the application
2010-08-10 05.07.27
                    Sa     Fixed             ESCAN00044371 All                            v_inc.h is not included in the generated DANIS adapter template
                    Sa     Fixed             ESCAN00044528 All                            Compile errors in DanisIsoTp communication adapter
2010-10-14 05.07.28
                    Ktw    Fixed             ESCAN00045932 All                            Compile error on each usage of DescInterruptDisable/-Restore internal API
2010-10-08 05.07.29
                    Mhe    Fixed             ESCAN00046410 All                            After ECU reset the diagnostic response is not transmitted after the function DescSendPosRespFBL has been called
2010-12-18 05.07.30
                    Sa     Fixed             ESCAN00047355 All                            Memory mapping of FAR buffer support use incomplete description for paged memory µC
                    Ktw    Added             ESCAN00047741 All                            Adapt CANdesc TMS320 support for GENy enabled CANdriver
2011-01-04 05.07.31
                    Ktw    Fixed             ESCAN00047884 All                            ROM data used as function parameter
2011-01-21 05.07.32
                    Ktw    Added             ESCAN00048157 All                            Add Danis adapter for LinTp    
2011-03-07 05.07.33
                    -      -                 -             -                              No relevant changes available in this version.
2011-03-28 05.07.34
                    Sa     Fixed             ESCAN00049396 UDS                            No positive response sent if SPRMIB=TRUE and API DescForceRcrRpResponse is used
                    Sa     Modified          ESCAN00047821 All                            Missing protection of undefined V_MEMRAM3_FAR
                    Sa     Modified          ESCAN00048636 All                            Error message references non-existent file "ApplDesc.h"
2011-05-13 05.07.35
                    Sa     Fixed             ESCAN00050204 UDS                            CANdesc does not reject requested service 0x2C 0x02 with ALFID==0x00
2011-05-31 05.07.36
                    Ktw    Fixed             ESCAN00051088 UDS                            Service 0x2A 0x04 ends up with endless RCR-RP responses on asynchronously read periodic DIDs
                    Ktw    Added             ESCAN00051315 UDS                            API DescGetCurrentBusInfo should be usable for periodic transmission 
2011-09-14 05.07.37
                    -      -                 -             -                              No relevant changes available in this version.
------------------------------------------------------------------------------------------------------------------------
 */


/* -----------------------------------------------------------------------------
    &&&~ Includes
 ----------------------------------------------------------------------------- */

/* Physical layer specific API */
#include "v_inc.h"
/* Check if CCL is available and take into account its configuration */
#if defined (VGEN_ENABLE_CCL)
# include "ccl_cfg.h"
#endif

/* Check if CCLcom is available and take into account its configuration */
#if defined (VGEN_ENABLE_CCLCOM)
# include "cclcom_cfg.h"
#endif

/* Make all CANdesc specific typedefs available */
#include "desc.h"
/* Include the implementation prototypes for prototype checks */
#include "appdesc.h"

/* Required for the implementation of ApplDescInitPosResFblBusInfo */
#include "tpmc.h"




/* -----------------------------------------------------------------------------
    &&&~ Implementation
 ----------------------------------------------------------------------------- */

#if defined (DESC_ENABLE_DEBUG_USER ) || defined (DESC_ENABLE_DEBUG_INTERNAL)
# if defined (CCL_ENABLE_ERROR_HOOK) || defined (CCLCOM_ENABLE_ERROR_HOOK)
/* CCL takes care about this function */
# else
/* ********************************************************************************
 * Function name:ApplDescFatalError
 * Description: This function will be called each time while the debug mode is active a
 * CANdesc fault has been detected. If you reach this function it makes no sence to continue the tests since CANdesc
 * will not operate properly until next start of the ECU.
 * Returns:  nothing
 * Parameter(s):
 *   - errorCode:
 *       - The assert code text equivalent can be found in desc.h (kDescAssert....).
 *       - Access type: read
 *   - lineNumber:
 *       - Since the same fault could be cales on many places the line number shows where exactly it occured.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - Set a break point at this place to know during the ECU development if you ran onto it.
 ******************************************************************************** */
void DESC_API_CALLBACK_TYPE ApplDescFatalError(vuint8 errorCode, vuint16 lineNumber)
{
  /*<<TBD>> Remove this comment once you have completely implemented this function!!!*/
  /* Avoid warnings */
  DESC_IGNORE_UNREF_PARAM(errorCode);
  DESC_IGNORE_UNREF_PARAM(lineNumber);

  /* When fatal error occurs, cause an ECU hang up at this point.
   * Please set break point at this line to investigate both parameter values. */
  for(;;);
}
# endif
#endif

/*******************************************************************************
* NAME:              ApplDescInitPosResFblBusInfo
*
* CALLED BY:         CANdesc
* PRECONDITIONS:     
*
* DESCRIPTION:       Initializes the busInfo with the concrete response address information
*                    (e.g. sourceAddr,TargetAddr, COM channel, etc.).
*******************************************************************************/
vuint8 DESC_API_CALL_TYPE ApplDescInitPosResFblBusInfo(t_descUsdtNetBus* pBusInfo)
{
  /* Init the bus-info structure as shown below */
  pBusInfo->busType = kDescUsdtNetBusTypeIsoTp;/* on other bus systems use the apropriate bus-type */
  /*On multi channel systems */
  pBusInfo->comChannel = 0; /* set the CAN (FlexRay or other) channel on which to send */
  /* If the addressing scheme uses source/target addresses put here the tester addres to respond to */
  pBusInfo->testerId = 0xF1; /* set the CAN (FlexRay or other) channel on which to send */

#if defined(DESC_USDTNET_ENABLE_DYNAMIC_BUFFER_LENGTH)
  /* If dynamic length is used, please use the correct buffer size of the corresponding DANIS driver!!! */
  pBusInfo->availBufferLength = kDescPrimBufferLen;
#endif

#if ( defined (TP_ENABLE_DYNAMIC_CHANNELS) && \
    (defined(TP_ENABLE_MIXED_11_ADDRESSING) || \
    defined(TP_ENABLE_NORMAL_ADDRESSING)) )
  /* ********** for these use cases additional TPMC initalization is required ********** */
  {
    vuintx tpChannel = kTpTxChannelCount;
    while (tpChannel != 0)
    {
      tpChannel--;
      if (kDescDiagConnection == TpTxGetConnectionNumber(tpChannel))
      {
# if defined(TP_ENABLE_MULTIPLE_ADDRESSING)
        tpTxInfoStruct[tpChannel].assignedDestination = kTpRequestDiagPhysical;
        tpTxInfoStruct[tpChannel].addressingFormat = kTpNormalAddressing; /*... respectively: kTpMixed11Addressing */
# endif
# error "Replace the <DIAG_NORMAL_ADD_RES_ID> and <DIAG_NORMAL_ADD_REQ_ID> below with the real CANids and uncomment the line!"
        /* TpTxSetChannelID(tpChannel, <DIAG_NORMAL_ADD_RES_ID>, <DIAG_NORMAL_ADD_REQ_ID>); */
# if (kTpNumberOfCanChannels > 1)
        TpTxSetCanChannel(tpChannel, pBusInfo->comChannel);
# endif
        break;
      }
    }
  }
#endif
  return kDescOk;
}

/*  ********************************************************************************
 * Function name:ApplDescOnTransitionSession
 * Description:Notification function for state change of the given state group, defined by
 * CANdelaStudio.
 * Returns:  nothing
 * Parameter(s):
 *   - newState:
 *       - The state which will be set.
 *       - Access type: read
 *   - formerState:
 *       - The current state of this state group.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" may not be called.
 *   - The function "DescSetNegResponse" may not be called.
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescOnTransitionSession(DescStateGroup newState, DescStateGroup formerState)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
   /* This is only a notification function. Using the "formerState" and the "newState" 
   * parameter you can distinguish the different transitions for this state group.
   */
  /* Avoids warnings */
  DESC_IGNORE_UNREF_PARAM(newState);
  DESC_IGNORE_UNREF_PARAM(formerState);
;
}


/* ********************************************************************************
 * Function name:ApplDescGlobalServicePreHandler
 * Description: Notification function that the a valid service has been received 
 *              (except for service $3E - TesterPresent).
 * Returns:  none
 * Parameter(s):
 *   - iContext - CANdesc instance handle (if multi instanced CANdesc is used)
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" may not be called.
 *   - The function "DescSetNegResponse" can be called.
 ******************************************************************************** */
void DESC_API_CALLBACK_TYPE ApplDescGlobalServicePreHandler(DESC_CONTEXT_FORMAL_PARAM_DEF_ONLY)
{
  /* Use this function to disable the rapid-shut-down state. */
}

/*  ********************************************************************************
 * Function name:ApplDescProcessEcuReset (Service request header:$11 )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessEcuReset(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Dummy example of how to write the response data. */
      pMsgContext->resData[0] = 0xFF;
      /* Always set the correct length of the response data. */
      pMsgContext->resDataLen = 1;
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/*  ********************************************************************************
 * Function name:ApplDescProcessClearDiagnosticInformation (Service request header:$14 )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessClearDiagnosticInformation(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Contains no response data */
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/*  ********************************************************************************
 * Function name:ApplDescProcessReadDtcInformation (Service request header:$19 )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessReadDtcInformation(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Dummy example of how to write the response data. */
      pMsgContext->resData[0] = 0xFF;
      /* Always set the correct length of the response data. */
      pMsgContext->resDataLen = 1;
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/*  ********************************************************************************
 * Function name:ApplDescProcessReadDataByIdentifier (Service request header:$22 )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessReadDataByIdentifier(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Dummy example of how to write the response data. */
      pMsgContext->resData[0] = 0xFF;
      /* Always set the correct length of the response data. */
      pMsgContext->resDataLen = 1;
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/*  ********************************************************************************
 * Function name:ApplDescProcessReadMemoryByAddress (Service request header:$23 )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessReadMemoryByAddress(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Dummy example of how to write the response data. */
      pMsgContext->resData[0] = 0xFF;
      /* Always set the correct length of the response data. */
      pMsgContext->resDataLen = 1;
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/*  ********************************************************************************
 * Function name:ApplDescProcessSecurityAccess (Service request header:$27 )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessSecurityAccess(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Dummy example of how to write the response data. */
      pMsgContext->resData[0] = 0xFF;
      /* Always set the correct length of the response data. */
      pMsgContext->resDataLen = 1;
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/*  ********************************************************************************
 * Function name:ApplDescProcessWriteDataByIdentifier (Service request header:$2E )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessWriteDataByIdentifier(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Dummy example of how to write the response data. */
      pMsgContext->resData[0] = 0xFF;
      /* Always set the correct length of the response data. */
      pMsgContext->resDataLen = 1;
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/*  ********************************************************************************
 * Function name:ApplDescProcessInputOutputControlByIdentifier (Service request header:$2F )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessInputOutputControlByIdentifier(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Dummy example of how to write the response data. */
      pMsgContext->resData[0] = 0xFF;
      /* Always set the correct length of the response data. */
      pMsgContext->resDataLen = 1;
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/*  ********************************************************************************
 * Function name:ApplDescProcessRoutineControl (Service request header:$31 )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessRoutineControl(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Dummy example of how to write the response data. */
      pMsgContext->resData[0] = 0xFF;
      /* Always set the correct length of the response data. */
      pMsgContext->resDataLen = 1;
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/*  ********************************************************************************
 * Function name:ApplDescProcessRequestDownload (Service request header:$34 )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessRequestDownload(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Dummy example of how to write the response data. */
      pMsgContext->resData[0] = 0xFF;
      /* Always set the correct length of the response data. */
      pMsgContext->resDataLen = 1;
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/*  ********************************************************************************
 * Function name:ApplDescProcessRequestUpload (Service request header:$35 )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessRequestUpload(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Dummy example of how to write the response data. */
      pMsgContext->resData[0] = 0xFF;
      /* Always set the correct length of the response data. */
      pMsgContext->resDataLen = 1;
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/*  ********************************************************************************
 * Function name:ApplDescProcessTransferData (Service request header:$36 )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessTransferData(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Contains no response data */
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/*  ********************************************************************************
 * Function name:ApplDescProcessRequestTransferExit (Service request header:$37 )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessRequestTransferExit(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Contains no response data */
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/*  ********************************************************************************
 * Function name:ApplDescProcessWriteMemoryByAddress (Service request header:$3D )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessWriteMemoryByAddress(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Dummy example of how to write the response data. */
      pMsgContext->resData[0] = 0xFF;
      /* Always set the correct length of the response data. */
      pMsgContext->resDataLen = 1;
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/*  ********************************************************************************
 * Function name:ApplDescProcessControlDTCSetting (Service request header:$85 )
 * Description: not available 
 * Returns:  nothing
 * Parameter(s):
 *   - pMsgContext->reqData:
 *       - Points to the first service request data byte.
 *       - Access type: read
 *   - pMsgContext->resData:
 *       - Points to the first writeable byte for the service response data.
 *       - Access type: read/write
 *   - pMsgContext->reqDataLen:
 *       - Contains the count of the service request data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read
 *   - pMsgContext->resDataLen:
 *       - Must be initialized with the count of the service response data bytes (Sid and sub-parameters are excluded).
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.reqType:
 *       - Shows the addressing type of the request (kDescPhysReq or kDescFuncReq).
 *       - Access type: read
 *   - pMsgContext->msgAddInfo.resOnReq:
 *       - Indicates if there will be response. Allowed only to write only 0 !!!
 *       - Access type: read/write
 *   - pMsgContext->msgAddInfo.suppPosRes:
 *       - UDS only!If set no positive response will be sent on this request.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" must be called from now on (within this
 * main-handler or later).
 *   - The function "DescSetNegResponse" can be called within this main-handler or later
 * but before calling "DescProcessingDone".
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescProcessControlDTCSetting(DescMsgContext* pMsgContext)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
  /* The application must check the requested data length. */
  if(pMsgContext->reqDataLen <= (DescMsgLen)0x0FFF)
  {
    /* Dummy example how to access the request data. */
    /* Assumming the FIRST DATA byte contains important data which has to be less than a constant value. */
    if(pMsgContext->reqData[0] < 0xFF)
    {
      /* Received data is in range process further. */
      /* Dummy example of how to write the response data. */
      pMsgContext->resData[0] = 0xFF;
      /* Always set the correct length of the response data. */
      pMsgContext->resDataLen = 1;
    }
    else
    {
      /* Request contains invalid data - send negative response! */
      DescSetNegResponse(kDescNrcRequestOutOfRange);
    }
  }
  else
  {
    /* Request length invalid - send negative response! */
    DescSetNegResponse(kDescNrcInvalidFormat);
  }
  /* User service processing finished. */
  DescProcessingDone();
}


/* ********************************************************************************
 * Function name:ApplDescOnCommunicationDisable
 * Description: Notification function that the communication has been disabled.
 * Returns:  none
 * Parameter(s):none
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" may not be called.
 *   - The function "DescSetNegResponse" may not be called.
 ******************************************************************************** */
void DESC_API_CALLBACK_TYPE ApplDescOnCommunicationDisable(void)
{
  /*<<TBD>> Remove this comment once you have completely implemented this function!!!*/
  /* The requested group of messages will no more be sent onto the communication bus. */
}

/* ********************************************************************************
 * Function name:ApplDescOnCommunicationEnable
 * Description: Notification function that the communication has been restored.
 * Returns:  none
 * Parameter(s):none
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" may not be called.
 *   - The function "DescSetNegResponse" may not be called.
 ******************************************************************************** */
void DESC_API_CALLBACK_TYPE ApplDescOnCommunicationEnable(void)
{
  /*<<TBD>> Remove this comment once you have completely implemented this function!!!*/
  /* The requested group of messages will be able to be sent onto the communication bus. */
}

/* Check the communication control activity */
/* ********************************************************************************
 * Function name:ApplDescCheckCommCtrl
 * Description:Check if the requested communication manipulation is possible to be performed by the ECU.
 * Returns:  nothing
 * Parameter(s):
 *   - iContext:
 *       - Diagnostic request handle used only in multi-context system (kDescNumContexts > 1).
 *       - Access type: read
 *   - commControlInfo->subNetTxNumber:
 *       - The application shall use this parameter to decied on which physical channels the communiaction will be manipulated.
 *       - Access type: read
 *   - commControlInfo->commCtrlChannel:
 *       - The application determines on which channel the communication will be manipulated (kDescCommControlCanCh01 - kDescCommControlCanCh14).
 *       - Access type: write
 *   - commControlInfo->rxPathState:
 *       - Activity type: kDescCommControlStateEnable - enables the communication; kDescCommControlStateDisable - disables it.
 *       - Access type: read
 *   - commControlInfo->txPathState:
 *       - Activity type: kDescCommControlStateEnable - enables the communication; kDescCommControlStateDisable - disables it.
 *       - Access type: read
 *   - commControlInfo->msgTypes:
 *       - Message group: kDescCommControlMsgAppl - application; kDescCommControlMsgNm - NM; 
 *       - Access type: read
 *   - commControlInfo->reqCommChannel:
 *       - The current CAN channel on which the CommControl request is received.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - Call "DescCommCtrlChecked" (here or later) to confirm the check.
 *   - Call "DescSetNegResponse" to reject the service.
 ******************************************************************************** */
void DESC_API_CALLBACK_TYPE ApplDescCheckCommCtrl(DESC_CONTEXT_FORMAL_PARAM_DEF_FIRST DescOemCommControlInfo *commControlInfo)
{
  /*<<TBD>> Remove this comment once you have completely implemented this function!!!*/

#if defined (DESC_ENABLE_COMM_CTRL_SUBNET_SUPPORT)
  switch(commControlInfo->subNetNumber)
  {
    case kDescCommControlSubNetNumAll:/* Enable/Disable all comm channels (CAN, LIN, etc.)*/
      /* Nothing to do - later the ApplDescSetCommMode will enable/disbale the LIN channels if needed. */
      break;
    case kDescCommControlSubNetNumRx:/* Enable/Disable only the request RX comm channel (CAN)*/
      /* Nothing to do - CANdesc handles the CAN channels */
      break;
    default:
      /* Dispatch subnetworks */
      /* Assumed subnet to CAN mapping: 
       * SubNet 1: LIN 
       * SubNet 2: CAN1 
       * SubNet 3: CAN2 
       */
      switch(commControlInfo->subNetNumber)
      {
        case kDescCommControlSubNetNum01:
          /* LIN network */
          commControlInfo->commCtrlChannel = kDescCommControlCanChNone;
          break;
/* The part is only needed if a multi CAN system is designed !!! */
# if defined(DESC_ENABLE_MULTI_CHANNEL_SUPPORT)
        case kDescCommControlSubNetNum02:
          /* CAN1 */
          commControlInfo->commCtrlChannel = kDescCommControlCanCh01;
          break;
        case kDescCommControlSubNetNum03:
          /* CAN2 */
          commControlInfo->commCtrlChannel = kDescCommControlCanCh02;
          break;
# endif
        default:
          /* Subnet numbers out of range */
          DescSetNegResponse(DESC_CONTEXT_PARAM_FIRST kDescNrcRequestOutOfRange);
          break;
      }
  }
#endif
  /* Confirm the communication status will be accepted. 
   * This can be done later by storing the iContext parameter (if exists) globaly to be able to give the correct acknowledgment.
   */
  DescCommCtrlChecked(DESC_CONTEXT_PARAM_ONLY);
}

#if defined (DESC_ENABLE_COMM_CTRL_SUBNET_SUPPORT)
/* ********************************************************************************
 * Function name:ApplDescSetCommMode
 * Description:Manipulate application specific channels (LIN, MOST, etc.)
 * Returns:  nothing
 * Parameter(s):
 *   - commControlInfo->subNetTxNumber:
 *       - The application shall use this parameter to decied on which physical channels the communiaction will be manipulated.
 *       - Access type: read
 *   - commControlInfo->commCtrlChannel:
 *       - The application determines on which channel the communication will be manipulated (kDescCommControlCanCh01 - kDescCommControlCanCh14).
 *       - Access type: write
 *   - commControlInfo->rxPathState:
 *       - Activity type: kDescCommControlStateEnable - enables the communication; kDescCommControlStateDisable - disables it.
 *       - Access type: read
 *   - commControlInfo->txPathState:
 *       - Activity type: kDescCommControlStateEnable - enables the communication; kDescCommControlStateDisable - disables it.
 *       - Access type: read
 *   - commControlInfo->msgTypes:
 *       - Message group: kDescCommControlMsgAppl - application; kDescCommControlMsgNm - NM; 
 *       - Access type: read
 *   - commControlInfo->reqCommChannel:
 *       - The current CAN channel on which the CommControl request is received.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" may not be called.
 *   - The function "DescSetNegResponse" may not be called.
 ******************************************************************************** */
void DESC_API_CALLBACK_TYPE ApplDescSetCommMode(DescOemCommControlInfo *commControlInfo)
{
  switch(commControlInfo->subNetNumber)
  {
    case kDescCommControlSubNetNumAll:/* Enable/Disable all comm channels (CAN, LIN, etc.)*/
      /* !!! Process application specific channels (e.g. LIN) CAN are already enabled/disabled by CANdesc */
      break;
    case kDescCommControlSubNetNumRx:/* Enable/Disable only the request RX comm channel (CAN)*/
      /* Nothing to do - CANdesc handles the CAN channels */
      break;
    default:
      /* Dispatch subnetworks */
      /* Assumed subnet to CAN mapping: 
       * SubNet 1: LIN 
       * SubNet 2: CAN1 
       * SubNet 3: CAN2 
       */
      switch(commControlInfo->subNetNumber)
      {
        case kDescCommControlSubNetNum01:
          /* LIN network */
          /* !!! Process application specific channels (e.g. LIN)*/
          break;
        case kDescCommControlSubNetNum02:          /* CAN1 */
        case kDescCommControlSubNetNum03:          /* CAN2 */
          /* Nothing to do - CANdesc handles all CANs */
          break;
        default:break;
      }
  }
}
#endif

#if defined (DESC_ENABLE_RX_COMM_CONTROL)
/* ********************************************************************************
 * Function name:ApplDescSetCommModeOnRxPath
 * Description: Manipulates only the RX path on CAN. For the other networks (if any) such LIN, MOST, etc. reffer to the
 *              ApplDescSetCommMode API.
 * Returns:  nothing
 * Parameter(s):
 *   - commControlInfo->subNetTxNumber:
 *       - The application shall use this parameter to decied on which physical channels the communiaction will be manipulated.
 *       - Access type: read
 *   - commControlInfo->commCtrlChannel:
 *       - The application determines on which channel the communication will be manipulated (kDescCommControlCanCh01 - kDescCommControlCanCh14).
 *       - Access type: write
 *   - commControlInfo->rxPathState:
 *       - Activity type: kDescCommControlStateEnable - enables the communication; kDescCommControlStateDisable - disables it.
 *       - Access type: read
*   - commControlInfo->rxPathState: - irrelevant for this API since it processes only the RX path!!!
 *       - Activity type: kDescCommControlStateEnable - enables the communication; kDescCommControlStateDisable - disables it.
 *       - Access type: read
 *   - commControlInfo->msgTypes:
 *       - Message group: kDescCommControlMsgAppl - application; kDescCommControlMsgNm - NM; 
 *       - Access type: read
 *   - commControlInfo->reqCommChannel:
 *       - The current CAN channel on which the CommControl request is received.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescProcessingDone" may not be called.
 *   - The function "DescSetNegResponse" may not be called.
 ******************************************************************************** */
void DESC_API_CALLBACK_TYPE ApplDescSetCommModeOnRxPath(DescOemCommControlInfo *commControlInfo)
{
  if((commControlInfo->rxPathState & kDescCommControlStateEnable) != 0)
  {
    /* _DrvCanSetRxOnlineMode(commControlInfo.commCtrlChannel, g_descCommControlInfo.msgTypes); */
  }
  else
  {
    /* _DrvCanSetRxOfflineMode(commControlInfo.commCtrlChannel, g_descCommControlInfo.msgTypes); */
  }
}
#endif

/*  ********************************************************************************
 * Function name:ApplDescCheckSessionTransition
 * Description:Check if the given session transition is allowed or your ECU is currently not
 * able to perform it.
 * Returns:  nothing
 * Parameter(s):
 *   - newState:
 *       - Contains the new state in which the state group will be set.
 *       - Access type: read
 *   - formerState:
 *       - Contains the current state of the state group.
 *       - Access type: read
 * Particularitie(s) and limitation(s):
 *   - The function "DescSessionTransitionChecked" may be called.
 *   - The function "DescSetNegResponse" may be called.
 ********************************************************************************  */
void DESC_API_CALLBACK_TYPE ApplDescCheckSessionTransition(DescStateGroup newState, DescStateGroup formerState)
{
  /* <<TBD>> Remove this comment once you have completely implemented this function!!! */
     /* Avoids warnings */
  DESC_IGNORE_UNREF_PARAM(newState);
  DESC_IGNORE_UNREF_PARAM(formerState);
  /* Just showing how to reject session transition if necessary. 
   * The negative response code may be other depending on the rejection reason.
   * This can be done later, but just store the iContext parameter (if exists) globaly to be able to give the correct acknowledgment. 
   */
  DescSetNegResponse(DESC_CONTEXT_PARAM_FIRST kDescNrcConditionsNotCorrect);
  /* Confirm the session will be accepted. 
   * This can be done later, but just store the iContext parameter (if exists) globaly to be able to give the correct acknowledgment.
   */
  DescSessionTransitionChecked(DESC_CONTEXT_PARAM_ONLY);
;
}




