/* -----------------------------------------------------------------------------
  Filename:    can_par.c
  Description: Toolversion: 03.20.21.01.10.02.79.00.00.00
               
               Serial Number: CBD1100279
               Customer Info: Dr. Ing. h. c. F. Porsche AG
                              CBD / Porsche 2007+
                              Texas Instruments TMS470 / TMS470 R1SF55
                              Texas Instruments 4.6.6 Compiler
               
               
               Generator Fwk   : GENy 
               Generator Module: DrvCan__base
               
               Configuration   : F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\cfg\Porsche_ADR.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470Cpu
                       Compiler:     TexasInstruments
                       Derivates:    TMS470R1
               
               Channel "Channel0":
                       Databasefile: F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\cfg\CAN_Matrix_Dashboard_2_11_0_X2_Release.dbc
                       Bussystem:    CAN
                       Manufacturer: Porsche AG
                       Node:         ADR_PAG_X2

  Generated by , 2012-02-15  08:51:07
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2010 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#define C_DRV_INTERNAL
#include "can_inc.h"
#include "can_par.h"
#include "v_inc.h"

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 tCanTxId0 V_MEMROM2 CanTxId0[kCanNumberOfTxObjects] = 
{
  MK_STDID0(0x7DD) /* ID: 0x000007dd, Handle: 0, ISO_Info_El_Resp [BC] */, 
  MK_STDID0(0x6D3) /* ID: 0x000006d3, Handle: 1, NMH_CDR_PCM [BC] */, 
  MK_STDID0(0x6AB) /* ID: 0x000006ab, Handle: 2, PCM_CDR_01_PAG [BC] */, 
  MK_STDID0(0x6A8) /* ID: 0x000006a8, Handle: 3, Mem_Kombi_01_PAG [BC] */, 
  MK_STDID0(0x666) /* ID: 0x00000666, Handle: 4, Kombi_09_PAG [BC] */, 
  MK_STDID0(0x643) /* ID: 0x00000643, Handle: 5, Einheiten_01 [BC] */, 
  MK_STDID0(0x5FE) /* ID: 0x000005fe, Handle: 6, Kombi_18_PAG [BC] */, 
  MK_STDID0(0x5FA) /* ID: 0x000005fa, Handle: 7, PCM_04_PAG [BC] */, 
  MK_STDID0(0x539) /* ID: 0x00000539, Handle: 8, PCM_02_PAG [BC] */, 
  MK_STDID0(0x0C2) /* ID: 0x000000c2, Handle: 9, ADR_02_PAG [BC] */, 
  MK_STDID0(0x0C0) /* ID: 0x000000c0, Handle: 10, ADR_01_PAG [BC] */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanTxDLC[kCanNumberOfTxObjects] = 
{
  MK_TX_DLC(8) /* ID: 0x000007dd, Handle: 0, ISO_Info_El_Resp [BC] */, 
  MK_TX_DLC(7) /* ID: 0x000006d3, Handle: 1, NMH_CDR_PCM [BC] */, 
  MK_TX_DLC(8) /* ID: 0x000006ab, Handle: 2, PCM_CDR_01_PAG [BC] */, 
  MK_TX_DLC(8) /* ID: 0x000006a8, Handle: 3, Mem_Kombi_01_PAG [BC] */, 
  MK_TX_DLC(8) /* ID: 0x00000666, Handle: 4, Kombi_09_PAG [BC] */, 
  MK_TX_DLC(3) /* ID: 0x00000643, Handle: 5, Einheiten_01 [BC] */, 
  MK_TX_DLC(8) /* ID: 0x000005fe, Handle: 6, Kombi_18_PAG [BC] */, 
  MK_TX_DLC(8) /* ID: 0x000005fa, Handle: 7, PCM_04_PAG [BC] */, 
  MK_TX_DLC(8) /* ID: 0x00000539, Handle: 8, PCM_02_PAG [BC] */, 
  MK_TX_DLC(8) /* ID: 0x000000c2, Handle: 9, ADR_02_PAG [BC] */, 
  MK_TX_DLC(8) /* ID: 0x000000c0, Handle: 10, ADR_01_PAG [BC] */
};
/* ROM CATEGORY 1 END */


#ifdef C_ENABLE_COPY_TX_DATA
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 TxDataPtr V_MEMROM2 CanTxDataPtr[kCanNumberOfTxObjects] = 
{
  (TxDataPtr) ISO_Info_El_Resp._c /* ID: 0x000007dd, Handle: 0, ISO_Info_El_Resp [BC] */, 
  (TxDataPtr) NMH_CDR_PCM._c /* ID: 0x000006d3, Handle: 1, NMH_CDR_PCM [BC] */, 
  (TxDataPtr) PCM_CDR_01_PAG._c /* ID: 0x000006ab, Handle: 2, PCM_CDR_01_PAG [BC] */, 
  (TxDataPtr) Mem_Kombi_01_PAG._c /* ID: 0x000006a8, Handle: 3, Mem_Kombi_01_PAG [BC] */, 
  (TxDataPtr) Kombi_09_PAG._c /* ID: 0x00000666, Handle: 4, Kombi_09_PAG [BC] */, 
  (TxDataPtr) Einheiten_01._c /* ID: 0x00000643, Handle: 5, Einheiten_01 [BC] */, 
  (TxDataPtr) Kombi_18_PAG._c /* ID: 0x000005fe, Handle: 6, Kombi_18_PAG [BC] */, 
  (TxDataPtr) PCM_04_PAG._c /* ID: 0x000005fa, Handle: 7, PCM_04_PAG [BC] */, 
  (TxDataPtr) PCM_02_PAG._c /* ID: 0x00000539, Handle: 8, PCM_02_PAG [BC] */, 
  (TxDataPtr) ADR_02_PAG._c /* ID: 0x000000c2, Handle: 9, ADR_02_PAG [BC] */, 
  (TxDataPtr) ADR_01_PAG._c /* ID: 0x000000c0, Handle: 10, ADR_01_PAG [BC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_PRETRANSMIT_FCT
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 ApplPreTransmitFct V_MEMROM2 CanTxApplPreTransmitPtr[kCanNumberOfTxObjects] = 
{
  V_NULL /* ID: 0x000007dd, Handle: 0, ISO_Info_El_Resp [BC] */, 
  V_NULL /* ID: 0x000006d3, Handle: 1, NMH_CDR_PCM [BC] */, 
  V_NULL /* ID: 0x000006ab, Handle: 2, PCM_CDR_01_PAG [BC] */, 
  V_NULL /* ID: 0x000006a8, Handle: 3, Mem_Kombi_01_PAG [BC] */, 
  V_NULL /* ID: 0x00000666, Handle: 4, Kombi_09_PAG [BC] */, 
  V_NULL /* ID: 0x00000643, Handle: 5, Einheiten_01 [BC] */, 
  V_NULL /* ID: 0x000005fe, Handle: 6, Kombi_18_PAG [BC] */, 
  V_NULL /* ID: 0x000005fa, Handle: 7, PCM_04_PAG [BC] */, 
  V_NULL /* ID: 0x00000539, Handle: 8, PCM_02_PAG [BC] */, 
  PreTransmitFunctionADR_02_PAG /* ID: 0x000000c2, Handle: 9, ADR_02_PAG [BC] */, 
  PreTransmitFunctionADR_01_PAG /* ID: 0x000000c0, Handle: 10, ADR_01_PAG [BC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_CONFIRMATION_FCT
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 ApplConfirmationFct V_MEMROM2 CanTxApplConfirmationPtr[kCanNumberOfTxObjects] = 
{
  TpDrvConfirmation /* ID: 0x000007dd, Handle: 0, ISO_Info_El_Resp [BC] */, 
  NmhCanMsgConfirmation /* ID: 0x000006d3, Handle: 1, NMH_CDR_PCM [BC] */, 
  V_NULL /* ID: 0x000006ab, Handle: 2, PCM_CDR_01_PAG [BC] */, 
  V_NULL /* ID: 0x000006a8, Handle: 3, Mem_Kombi_01_PAG [BC] */, 
  V_NULL /* ID: 0x00000666, Handle: 4, Kombi_09_PAG [BC] */, 
  V_NULL /* ID: 0x00000643, Handle: 5, Einheiten_01 [BC] */, 
  V_NULL /* ID: 0x000005fe, Handle: 6, Kombi_18_PAG [BC] */, 
  V_NULL /* ID: 0x000005fa, Handle: 7, PCM_04_PAG [BC] */, 
  V_NULL /* ID: 0x00000539, Handle: 8, PCM_02_PAG [BC] */, 
  V_NULL /* ID: 0x000000c2, Handle: 9, ADR_02_PAG [BC] */, 
  V_NULL /* ID: 0x000000c0, Handle: 10, ADR_01_PAG [BC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_PART_OFFLINE
/* ROM CATEGORY 2 START */

V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanTxSendMask[kCanNumberOfTxObjects] = 
{
  (vuint8) C_SEND_GRP_NONE /* ID: 0x000007dd, Handle: 0, ISO_Info_El_Resp [BC] */, 
  (vuint8) C_SEND_GRP_NONE /* ID: 0x000006d3, Handle: 1, NMH_CDR_PCM [BC] */, 
  (vuint8) C_SEND_GRP_APPL /* ID: 0x000006ab, Handle: 2, PCM_CDR_01_PAG [BC] */, 
  (vuint8) C_SEND_GRP_APPL /* ID: 0x000006a8, Handle: 3, Mem_Kombi_01_PAG [BC] */, 
  (vuint8) C_SEND_GRP_APPL /* ID: 0x00000666, Handle: 4, Kombi_09_PAG [BC] */, 
  (vuint8) C_SEND_GRP_APPL /* ID: 0x00000643, Handle: 5, Einheiten_01 [BC] */, 
  (vuint8) C_SEND_GRP_APPL /* ID: 0x000005fe, Handle: 6, Kombi_18_PAG [BC] */, 
  (vuint8) C_SEND_GRP_APPL /* ID: 0x000005fa, Handle: 7, PCM_04_PAG [BC] */, 
  (vuint8) C_SEND_GRP_APPL /* ID: 0x00000539, Handle: 8, PCM_02_PAG [BC] */, 
  (vuint8) C_SEND_GRP_APPL /* ID: 0x000000c2, Handle: 9, ADR_02_PAG [BC] */, 
  (vuint8) C_SEND_GRP_APPL /* ID: 0x000000c0, Handle: 10, ADR_01_PAG [BC] */
};

/* ROM CATEGORY 2 END */

#endif


#ifdef C_ENABLE_CONFIRMATION_FLAG
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanConfirmationOffset[kCanNumberOfTxObjects] = 
{
  0 /* ID: 0x000007dd, Handle: 0, ISO_Info_El_Resp [BC] */, 
  0 /* ID: 0x000006d3, Handle: 1, NMH_CDR_PCM [BC] */, 
  0 /* ID: 0x000006ab, Handle: 2, PCM_CDR_01_PAG [BC] */, 
  0 /* ID: 0x000006a8, Handle: 3, Mem_Kombi_01_PAG [BC] */, 
  0 /* ID: 0x00000666, Handle: 4, Kombi_09_PAG [BC] */, 
  0 /* ID: 0x00000643, Handle: 5, Einheiten_01 [BC] */, 
  0 /* ID: 0x000005fe, Handle: 6, Kombi_18_PAG [BC] */, 
  0 /* ID: 0x000005fa, Handle: 7, PCM_04_PAG [BC] */, 
  0 /* ID: 0x00000539, Handle: 8, PCM_02_PAG [BC] */, 
  0 /* ID: 0x000000c2, Handle: 9, ADR_02_PAG [BC] */, 
  1 /* ID: 0x000000c0, Handle: 10, ADR_01_PAG [BC] */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanConfirmationMask[kCanNumberOfTxObjects] = 
{
  0x00 /* ID: 0x000007dd, Handle: 0, ISO_Info_El_Resp [BC] */, 
  0x00 /* ID: 0x000006d3, Handle: 1, NMH_CDR_PCM [BC] */, 
  0x01 /* ID: 0x000006ab, Handle: 2, PCM_CDR_01_PAG [BC] */, 
  0x02 /* ID: 0x000006a8, Handle: 3, Mem_Kombi_01_PAG [BC] */, 
  0x04 /* ID: 0x00000666, Handle: 4, Kombi_09_PAG [BC] */, 
  0x08 /* ID: 0x00000643, Handle: 5, Einheiten_01 [BC] */, 
  0x10 /* ID: 0x000005fe, Handle: 6, Kombi_18_PAG [BC] */, 
  0x20 /* ID: 0x000005fa, Handle: 7, PCM_04_PAG [BC] */, 
  0x40 /* ID: 0x00000539, Handle: 8, PCM_02_PAG [BC] */, 
  0x80 /* ID: 0x000000c2, Handle: 9, ADR_02_PAG [BC] */, 
  0x01 /* ID: 0x000000c0, Handle: 10, ADR_01_PAG [BC] */
};
/* ROM CATEGORY 1 END */


#endif




/* Id table depending on search algorithm */
/* Linear search */
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 tCanRxId0 V_MEMROM2 CanRxId0[kCanNumberOfRxObjects] = 
{
  MK_STDID0(0x6B4) /* ID: 0x000006b4, Handle: 2, VIN_01 [BC] */, 
  MK_STDID0(0x67E) /* ID: 0x0000067e, Handle: 4, LAD_02 [BC] */, 
  MK_STDID0(0x674) /* ID: 0x00000674, Handle: 5, RDK_02_PAG [BC] */, 
  MK_STDID0(0x5FF) /* ID: 0x000005ff, Handle: 11, Kombi_19_PAG [BC] */, 
  MK_STDID0(0x5BF) /* ID: 0x000005bf, Handle: 14, MFL_Tasten_Kon_01 [BC] */, 
  MK_STDID0(0x585) /* ID: 0x00000585, Handle: 16, Systeminfo_01 [BC] */, 
  MK_STDID0(0x575) /* ID: 0x00000575, Handle: 17, HVLM_07_PAG [BC] */, 
  MK_STDID0(0x53F) /* ID: 0x0000053f, Handle: 18, Kombi_EV_01_PAG [BC] */, 
  MK_STDID0(0x529) /* ID: 0x00000529, Handle: 20, Lift_01 [BC] */, 
  MK_STDID0(0x484) /* ID: 0x00000484, Handle: 21, NPM_01_PAG [BC] */, 
  MK_STDID0(0x440) /* ID: 0x00000440, Handle: 23, Motor_06 [BC] */, 
  MK_STDID0(0x3A5) /* ID: 0x000003a5, Handle: 26, Motor_15_PAG [BC] */, 
  MK_STDID0(0x3A3) /* ID: 0x000003a3, Handle: 27, Motor_K_02 [BC] */, 
  MK_STDID0(0x37F) /* ID: 0x0000037f, Handle: 33, Klima_13_PAG [BC] */, 
  MK_STDID0(0x0C1) /* ID: 0x000000c1, Handle: 41, Miko_01_PAG [BC] */, 
  MK_STDID0(0x07E) /* ID: 0x0000007e, Handle: 42, Motor_02_sek [BC] */, 
  MK_STDID0(0x773) /* ID: 0x00000773, Handle: 43, ISO_Info_El_Req [FC] */, 
  MK_STDID0(0x700) /* ID: 0x00000700, Handle: 44, ISO_Funktionaler_Req_All [FC] */, 
  MK_STDID0(0x6BD) /* ID: 0x000006bd, Handle: 0, Kombi_11_PAG [FC] */, 
  MK_STDID0(0x6B7) /* ID: 0x000006b7, Handle: 1, Kombi_02 [FC] */, 
  MK_STDID0(0x6B2) /* ID: 0x000006b2, Handle: 3, Diagnose_01 [FC] */, 
  MK_STDID0(0x66E) /* ID: 0x0000066e, Handle: 6, Klima_03 [FC] */, 
  MK_STDID0(0x66B) /* ID: 0x0000066b, Handle: 7, Gateway_03 [FC] */, 
  MK_STDID0(0x664) /* ID: 0x00000664, Handle: 8, Klima_02 [FC] */, 
  MK_STDID0(0x663) /* ID: 0x00000663, Handle: 9, BEM_02 [FC] */, 
  MK_STDID0(0x662) /* ID: 0x00000662, Handle: 10, BCM1_02 [FC] */, 
  MK_STDID0(0x5EC) /* ID: 0x000005ec, Handle: 12, GW_Mmi_07_PAG [FC] */, 
  MK_STDID0(0x5EB) /* ID: 0x000005eb, Handle: 13, GW_Mmi_06_PAG [FC] */, 
  MK_STDID0(0x594) /* ID: 0x00000594, Handle: 15, HVLM_05 [FC] */, 
  MK_STDID0(0x533) /* ID: 0x00000533, Handle: 19, Kombi_14_PAG [FC] */, 
  MK_STDID0(0x444) /* ID: 0x00000444, Handle: 22, GW_Mmi_10_PAG [FC] */, 
  MK_STDID0(0x3C3) /* ID: 0x000003c3, Handle: 24, Gateway_01 [FC] */, 
  MK_STDID0(0x3C0) /* ID: 0x000003c0, Handle: 25, Klemmen_Status_01 [FC] */, 
  MK_STDID0(0x39B) /* ID: 0x0000039b, Handle: 28, Kombi_17_PAG [FC] */, 
  MK_STDID0(0x39A) /* ID: 0x0000039a, Handle: 29, Kombi_16_PAG [FC] */, 
  MK_STDID0(0x38D) /* ID: 0x0000038d, Handle: 30, GW_Mmi_01_PAG [FC] */, 
  MK_STDID0(0x38C) /* ID: 0x0000038c, Handle: 31, GW_Mmi_05_PAG [FC] */, 
  MK_STDID0(0x384) /* ID: 0x00000384, Handle: 32, BCM2_03_PAG [FC] */, 
  MK_STDID0(0x31C) /* ID: 0x0000031c, Handle: 34, GW_Mmi_04_PAG [FC] */, 
  MK_STDID0(0x31A) /* ID: 0x0000031a, Handle: 35, Kombi_10_PAG [FC] */, 
  MK_STDID0(0x11A) /* ID: 0x0000011a, Handle: 36, Kombi_13_PAG [FC] */, 
  MK_STDID0(0x116) /* ID: 0x00000116, Handle: 37, ESP_10 [FC] */, 
  MK_STDID0(0x102) /* ID: 0x00000102, Handle: 38, Getriebe_03 [FC] */, 
  MK_STDID0(0x101) /* ID: 0x00000101, Handle: 39, ESP_02 [FC] */, 
  MK_STDID0(0x100) /* ID: 0x00000100, Handle: 40, ESP_01 [FC] */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanReceiveHandle V_MEMROM2 CanRxMsgIndirection[kCanNumberOfRxObjects] = 
{
  2 /* ID: 0x000006b4, Handle: 2, VIN_01 */, 
  4 /* ID: 0x0000067e, Handle: 4, LAD_02 */, 
  5 /* ID: 0x00000674, Handle: 5, RDK_02_PAG */, 
  11 /* ID: 0x000005ff, Handle: 11, Kombi_19_PAG */, 
  14 /* ID: 0x000005bf, Handle: 14, MFL_Tasten_Kon_01 */, 
  16 /* ID: 0x00000585, Handle: 16, Systeminfo_01 */, 
  17 /* ID: 0x00000575, Handle: 17, HVLM_07_PAG */, 
  18 /* ID: 0x0000053f, Handle: 18, Kombi_EV_01_PAG */, 
  20 /* ID: 0x00000529, Handle: 20, Lift_01 */, 
  21 /* ID: 0x00000484, Handle: 21, NPM_01_PAG */, 
  23 /* ID: 0x00000440, Handle: 23, Motor_06 */, 
  26 /* ID: 0x000003a5, Handle: 26, Motor_15_PAG */, 
  27 /* ID: 0x000003a3, Handle: 27, Motor_K_02 */, 
  33 /* ID: 0x0000037f, Handle: 33, Klima_13_PAG */, 
  41 /* ID: 0x000000c1, Handle: 41, Miko_01_PAG */, 
  42 /* ID: 0x0000007e, Handle: 42, Motor_02_sek */, 
  43 /* ID: 0x00000773, Handle: 43, ISO_Info_El_Req */, 
  44 /* ID: 0x00000700, Handle: 44, ISO_Funktionaler_Req_All */, 
  0 /* ID: 0x000006bd, Handle: 0, Kombi_11_PAG */, 
  1 /* ID: 0x000006b7, Handle: 1, Kombi_02 */, 
  3 /* ID: 0x000006b2, Handle: 3, Diagnose_01 */, 
  6 /* ID: 0x0000066e, Handle: 6, Klima_03 */, 
  7 /* ID: 0x0000066b, Handle: 7, Gateway_03 */, 
  8 /* ID: 0x00000664, Handle: 8, Klima_02 */, 
  9 /* ID: 0x00000663, Handle: 9, BEM_02 */, 
  10 /* ID: 0x00000662, Handle: 10, BCM1_02 */, 
  12 /* ID: 0x000005ec, Handle: 12, GW_Mmi_07_PAG */, 
  13 /* ID: 0x000005eb, Handle: 13, GW_Mmi_06_PAG */, 
  15 /* ID: 0x00000594, Handle: 15, HVLM_05 */, 
  19 /* ID: 0x00000533, Handle: 19, Kombi_14_PAG */, 
  22 /* ID: 0x00000444, Handle: 22, GW_Mmi_10_PAG */, 
  24 /* ID: 0x000003c3, Handle: 24, Gateway_01 */, 
  25 /* ID: 0x000003c0, Handle: 25, Klemmen_Status_01 */, 
  28 /* ID: 0x0000039b, Handle: 28, Kombi_17_PAG */, 
  29 /* ID: 0x0000039a, Handle: 29, Kombi_16_PAG */, 
  30 /* ID: 0x0000038d, Handle: 30, GW_Mmi_01_PAG */, 
  31 /* ID: 0x0000038c, Handle: 31, GW_Mmi_05_PAG */, 
  32 /* ID: 0x00000384, Handle: 32, BCM2_03_PAG */, 
  34 /* ID: 0x0000031c, Handle: 34, GW_Mmi_04_PAG */, 
  35 /* ID: 0x0000031a, Handle: 35, Kombi_10_PAG */, 
  36 /* ID: 0x0000011a, Handle: 36, Kombi_13_PAG */, 
  37 /* ID: 0x00000116, Handle: 37, ESP_10 */, 
  38 /* ID: 0x00000102, Handle: 38, Getriebe_03 */, 
  39 /* ID: 0x00000101, Handle: 39, ESP_02 */, 
  40 /* ID: 0x00000100, Handle: 40, ESP_01 */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanRxDataLen[kCanNumberOfRxObjects] = 
{
  6 /* ID: 0x000006bd, Handle: 0, Kombi_11_PAG [FC] */, 
  8 /* ID: 0x000006b7, Handle: 1, Kombi_02 [FC] */, 
  8 /* ID: 0x000006b4, Handle: 2, VIN_01 [BC] */, 
  8 /* ID: 0x000006b2, Handle: 3, Diagnose_01 [FC] */, 
  8 /* ID: 0x0000067e, Handle: 4, LAD_02 [BC] */, 
  2 /* ID: 0x00000674, Handle: 5, RDK_02_PAG [BC] */, 
  6 /* ID: 0x0000066e, Handle: 6, Klima_03 [FC] */, 
  7 /* ID: 0x0000066b, Handle: 7, Gateway_03 [FC] */, 
  5 /* ID: 0x00000664, Handle: 8, Klima_02 [FC] */, 
  1 /* ID: 0x00000663, Handle: 9, BEM_02 [FC] */, 
  3 /* ID: 0x00000662, Handle: 10, BCM1_02 [FC] */, 
  3 /* ID: 0x000005ff, Handle: 11, Kombi_19_PAG [BC] */, 
  8 /* ID: 0x000005ec, Handle: 12, GW_Mmi_07_PAG [FC] */, 
  8 /* ID: 0x000005eb, Handle: 13, GW_Mmi_06_PAG [FC] */, 
  4 /* ID: 0x000005bf, Handle: 14, MFL_Tasten_Kon_01 [BC] */, 
  7 /* ID: 0x00000594, Handle: 15, HVLM_05 [FC] */, 
  2 /* ID: 0x00000585, Handle: 16, Systeminfo_01 [BC] */, 
  5 /* ID: 0x00000575, Handle: 17, HVLM_07_PAG [BC] */, 
  8 /* ID: 0x0000053f, Handle: 18, Kombi_EV_01_PAG [BC] */, 
  8 /* ID: 0x00000533, Handle: 19, Kombi_14_PAG [FC] */, 
  2 /* ID: 0x00000529, Handle: 20, Lift_01 [BC] */, 
  8 /* ID: 0x00000484, Handle: 21, NPM_01_PAG [BC] */, 
  8 /* ID: 0x00000444, Handle: 22, GW_Mmi_10_PAG [FC] */, 
  4 /* ID: 0x00000440, Handle: 23, Motor_06 [BC] */, 
  7 /* ID: 0x000003c3, Handle: 24, Gateway_01 [FC] */, 
  3 /* ID: 0x000003c0, Handle: 25, Klemmen_Status_01 [FC] */, 
  2 /* ID: 0x000003a5, Handle: 26, Motor_15_PAG [BC] */, 
  6 /* ID: 0x000003a3, Handle: 27, Motor_K_02 [BC] */, 
  8 /* ID: 0x0000039b, Handle: 28, Kombi_17_PAG [FC] */, 
  8 /* ID: 0x0000039a, Handle: 29, Kombi_16_PAG [FC] */, 
  8 /* ID: 0x0000038d, Handle: 30, GW_Mmi_01_PAG [FC] */, 
  8 /* ID: 0x0000038c, Handle: 31, GW_Mmi_05_PAG [FC] */, 
  4 /* ID: 0x00000384, Handle: 32, BCM2_03_PAG [FC] */, 
  3 /* ID: 0x0000037f, Handle: 33, Klima_13_PAG [BC] */, 
  8 /* ID: 0x0000031c, Handle: 34, GW_Mmi_04_PAG [FC] */, 
  5 /* ID: 0x0000031a, Handle: 35, Kombi_10_PAG [FC] */, 
  7 /* ID: 0x0000011a, Handle: 36, Kombi_13_PAG [FC] */, 
  8 /* ID: 0x00000116, Handle: 37, ESP_10 [FC] */, 
  4 /* ID: 0x00000102, Handle: 38, Getriebe_03 [FC] */, 
  5 /* ID: 0x00000101, Handle: 39, ESP_02 [FC] */, 
  7 /* ID: 0x00000100, Handle: 40, ESP_01 [FC] */, 
  6 /* ID: 0x000000c1, Handle: 41, Miko_01_PAG [BC] */, 
  3 /* ID: 0x0000007e, Handle: 42, Motor_02_sek [BC] */, 
  8 /* ID: 0x00000773, Handle: 43, ISO_Info_El_Req [FC] */, 
  8 /* ID: 0x00000700, Handle: 44, ISO_Funktionaler_Req_All [FC] */
};
/* ROM CATEGORY 1 END */


#ifdef C_ENABLE_COPY_RX_DATA
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 RxDataPtr V_MEMROM2 CanRxDataPtr[kCanNumberOfRxObjects] = 
{
  (RxDataPtr) Kombi_11_PAG._c /* ID: 0x000006bd, Handle: 0, Kombi_11_PAG [FC] */, 
  (RxDataPtr) Kombi_02._c /* ID: 0x000006b7, Handle: 1, Kombi_02 [FC] */, 
  (RxDataPtr) VIN_01._c /* ID: 0x000006b4, Handle: 2, VIN_01 [BC] */, 
  (RxDataPtr) Diagnose_01._c /* ID: 0x000006b2, Handle: 3, Diagnose_01 [FC] */, 
  (RxDataPtr) LAD_02._c /* ID: 0x0000067e, Handle: 4, LAD_02 [BC] */, 
  (RxDataPtr) RDK_02_PAG._c /* ID: 0x00000674, Handle: 5, RDK_02_PAG [BC] */, 
  (RxDataPtr) Klima_03._c /* ID: 0x0000066e, Handle: 6, Klima_03 [FC] */, 
  (RxDataPtr) Gateway_03._c /* ID: 0x0000066b, Handle: 7, Gateway_03 [FC] */, 
  (RxDataPtr) Klima_02._c /* ID: 0x00000664, Handle: 8, Klima_02 [FC] */, 
  (RxDataPtr) BEM_02._c /* ID: 0x00000663, Handle: 9, BEM_02 [FC] */, 
  (RxDataPtr) BCM1_02._c /* ID: 0x00000662, Handle: 10, BCM1_02 [FC] */, 
  (RxDataPtr) Kombi_19_PAG._c /* ID: 0x000005ff, Handle: 11, Kombi_19_PAG [BC] */, 
  (RxDataPtr) GW_Mmi_07_PAG._c /* ID: 0x000005ec, Handle: 12, GW_Mmi_07_PAG [FC] */, 
  (RxDataPtr) GW_Mmi_06_PAG._c /* ID: 0x000005eb, Handle: 13, GW_Mmi_06_PAG [FC] */, 
  (RxDataPtr) MFL_Tasten_Kon_01._c /* ID: 0x000005bf, Handle: 14, MFL_Tasten_Kon_01 [BC] */, 
  (RxDataPtr) HVLM_05._c /* ID: 0x00000594, Handle: 15, HVLM_05 [FC] */, 
  (RxDataPtr) Systeminfo_01._c /* ID: 0x00000585, Handle: 16, Systeminfo_01 [BC] */, 
  (RxDataPtr) HVLM_07_PAG._c /* ID: 0x00000575, Handle: 17, HVLM_07_PAG [BC] */, 
  (RxDataPtr) Kombi_EV_01_PAG._c /* ID: 0x0000053f, Handle: 18, Kombi_EV_01_PAG [BC] */, 
  (RxDataPtr) Kombi_14_PAG._c /* ID: 0x00000533, Handle: 19, Kombi_14_PAG [FC] */, 
  (RxDataPtr) Lift_01._c /* ID: 0x00000529, Handle: 20, Lift_01 [BC] */, 
  (RxDataPtr) NPM_01_PAG._c /* ID: 0x00000484, Handle: 21, NPM_01_PAG [BC] */, 
  (RxDataPtr) GW_Mmi_10_PAG._c /* ID: 0x00000444, Handle: 22, GW_Mmi_10_PAG [FC] */, 
  (RxDataPtr) Motor_06._c /* ID: 0x00000440, Handle: 23, Motor_06 [BC] */, 
  (RxDataPtr) Gateway_01._c /* ID: 0x000003c3, Handle: 24, Gateway_01 [FC] */, 
  (RxDataPtr) Klemmen_Status_01._c /* ID: 0x000003c0, Handle: 25, Klemmen_Status_01 [FC] */, 
  (RxDataPtr) Motor_15_PAG._c /* ID: 0x000003a5, Handle: 26, Motor_15_PAG [BC] */, 
  (RxDataPtr) Motor_K_02._c /* ID: 0x000003a3, Handle: 27, Motor_K_02 [BC] */, 
  (RxDataPtr) Kombi_17_PAG._c /* ID: 0x0000039b, Handle: 28, Kombi_17_PAG [FC] */, 
  (RxDataPtr) Kombi_16_PAG._c /* ID: 0x0000039a, Handle: 29, Kombi_16_PAG [FC] */, 
  (RxDataPtr) GW_Mmi_01_PAG._c /* ID: 0x0000038d, Handle: 30, GW_Mmi_01_PAG [FC] */, 
  (RxDataPtr) GW_Mmi_05_PAG._c /* ID: 0x0000038c, Handle: 31, GW_Mmi_05_PAG [FC] */, 
  (RxDataPtr) BCM2_03_PAG._c /* ID: 0x00000384, Handle: 32, BCM2_03_PAG [FC] */, 
  (RxDataPtr) Klima_13_PAG._c /* ID: 0x0000037f, Handle: 33, Klima_13_PAG [BC] */, 
  (RxDataPtr) GW_Mmi_04_PAG._c /* ID: 0x0000031c, Handle: 34, GW_Mmi_04_PAG [FC] */, 
  (RxDataPtr) Kombi_10_PAG._c /* ID: 0x0000031a, Handle: 35, Kombi_10_PAG [FC] */, 
  (RxDataPtr) Kombi_13_PAG._c /* ID: 0x0000011a, Handle: 36, Kombi_13_PAG [FC] */, 
  (RxDataPtr) ESP_10._c /* ID: 0x00000116, Handle: 37, ESP_10 [FC] */, 
  (RxDataPtr) Getriebe_03._c /* ID: 0x00000102, Handle: 38, Getriebe_03 [FC] */, 
  (RxDataPtr) ESP_02._c /* ID: 0x00000101, Handle: 39, ESP_02 [FC] */, 
  (RxDataPtr) ESP_01._c /* ID: 0x00000100, Handle: 40, ESP_01 [FC] */, 
  (RxDataPtr) Miko_01_PAG._c /* ID: 0x000000c1, Handle: 41, Miko_01_PAG [BC] */, 
  (RxDataPtr) Motor_02_sek._c /* ID: 0x0000007e, Handle: 42, Motor_02_sek [BC] */, 
  (RxDataPtr) 0 /* ID: 0x00000773, Handle: 43, ISO_Info_El_Req [FC] */, 
  (RxDataPtr) 0 /* ID: 0x00000700, Handle: 44, ISO_Funktionaler_Req_All [FC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_PRECOPY_FCT
/* CODE CATEGORY 1 START */
vuint8 CanRxNPM_01_PAGPrecopyFct(CanRxInfoStructPtr rxStruct)
{
  vuint8 ret = kCanNoCopyData;
  ret |= IlMsgNPM_01_PAGPreCopy(rxStruct);
  ret |= ApplCclNpmPrecopy(rxStruct);
  return ret;
}



/* CODE CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 ApplPrecopyFct V_MEMROM2 CanRxApplPrecopyPtr[kCanNumberOfRxObjects] = 
{
  IlMsgKombi_11_PAGPreCopy /* ID: 0x000006bd, Handle: 0, Kombi_11_PAG [FC] */, 
  IlMsgKombi_02PreCopy /* ID: 0x000006b7, Handle: 1, Kombi_02 [FC] */, 
  IlMsgVIN_01PreCopy /* ID: 0x000006b4, Handle: 2, VIN_01 [BC] */, 
  IlMsgDiagnose_01PreCopy /* ID: 0x000006b2, Handle: 3, Diagnose_01 [FC] */, 
  IlMsgLAD_02PreCopy /* ID: 0x0000067e, Handle: 4, LAD_02 [BC] */, 
  IlMsgRDK_02_PAGPreCopy /* ID: 0x00000674, Handle: 5, RDK_02_PAG [BC] */, 
  IlMsgKlima_03PreCopy /* ID: 0x0000066e, Handle: 6, Klima_03 [FC] */, 
  IlMsgGateway_03PreCopy /* ID: 0x0000066b, Handle: 7, Gateway_03 [FC] */, 
  IlMsgKlima_02PreCopy /* ID: 0x00000664, Handle: 8, Klima_02 [FC] */, 
  IlMsgBEM_02PreCopy /* ID: 0x00000663, Handle: 9, BEM_02 [FC] */, 
  IlMsgBCM1_02PreCopy /* ID: 0x00000662, Handle: 10, BCM1_02 [FC] */, 
  IlMsgKombi_19_PAGPreCopy /* ID: 0x000005ff, Handle: 11, Kombi_19_PAG [BC] */, 
  IlMsgGW_Mmi_07_PAGPreCopy /* ID: 0x000005ec, Handle: 12, GW_Mmi_07_PAG [FC] */, 
  IlMsgGW_Mmi_06_PAGPreCopy /* ID: 0x000005eb, Handle: 13, GW_Mmi_06_PAG [FC] */, 
  IlMsgMFL_Tasten_Kon_01PreCopy /* ID: 0x000005bf, Handle: 14, MFL_Tasten_Kon_01 [BC] */, 
  IlMsgHVLM_05PreCopy /* ID: 0x00000594, Handle: 15, HVLM_05 [FC] */, 
  IlMsgSysteminfo_01PreCopy /* ID: 0x00000585, Handle: 16, Systeminfo_01 [BC] */, 
  IlMsgHVLM_07_PAGPreCopy /* ID: 0x00000575, Handle: 17, HVLM_07_PAG [BC] */, 
  IlMsgKombi_EV_01_PAGPreCopy /* ID: 0x0000053f, Handle: 18, Kombi_EV_01_PAG [BC] */, 
  IlMsgKombi_14_PAGPreCopy /* ID: 0x00000533, Handle: 19, Kombi_14_PAG [FC] */, 
  IlMsgLift_01PreCopy /* ID: 0x00000529, Handle: 20, Lift_01 [BC] */, 
  CanRxNPM_01_PAGPrecopyFct /* ID: 0x00000484, Handle: 21, NPM_01_PAG [BC] */, 
  IlMsgGW_Mmi_10_PAGPreCopy /* ID: 0x00000444, Handle: 22, GW_Mmi_10_PAG [FC] */, 
  IlMsgMotor_06PreCopy /* ID: 0x00000440, Handle: 23, Motor_06 [BC] */, 
  IlMsgGateway_01PreCopy /* ID: 0x000003c3, Handle: 24, Gateway_01 [FC] */, 
  IlMsgKlemmen_Status_01PreCopy /* ID: 0x000003c0, Handle: 25, Klemmen_Status_01 [FC] */, 
  IlMsgMotor_15_PAGPreCopy /* ID: 0x000003a5, Handle: 26, Motor_15_PAG [BC] */, 
  IlMsgMotor_K_02PreCopy /* ID: 0x000003a3, Handle: 27, Motor_K_02 [BC] */, 
  IlMsgKombi_17_PAGPreCopy /* ID: 0x0000039b, Handle: 28, Kombi_17_PAG [FC] */, 
  IlMsgKombi_16_PAGPreCopy /* ID: 0x0000039a, Handle: 29, Kombi_16_PAG [FC] */, 
  IlMsgGW_Mmi_01_PAGPreCopy /* ID: 0x0000038d, Handle: 30, GW_Mmi_01_PAG [FC] */, 
  IlMsgGW_Mmi_05_PAGPreCopy /* ID: 0x0000038c, Handle: 31, GW_Mmi_05_PAG [FC] */, 
  IlMsgBCM2_03_PAGPreCopy /* ID: 0x00000384, Handle: 32, BCM2_03_PAG [FC] */, 
  IlMsgKlima_13_PAGPreCopy /* ID: 0x0000037f, Handle: 33, Klima_13_PAG [BC] */, 
  IlMsgGW_Mmi_04_PAGPreCopy /* ID: 0x0000031c, Handle: 34, GW_Mmi_04_PAG [FC] */, 
  IlMsgKombi_10_PAGPreCopy /* ID: 0x0000031a, Handle: 35, Kombi_10_PAG [FC] */, 
  IlMsgKombi_13_PAGPreCopy /* ID: 0x0000011a, Handle: 36, Kombi_13_PAG [FC] */, 
  IlMsgESP_10PreCopy /* ID: 0x00000116, Handle: 37, ESP_10 [FC] */, 
  IlMsgGetriebe_03PreCopy /* ID: 0x00000102, Handle: 38, Getriebe_03 [FC] */, 
  IlMsgESP_02PreCopy /* ID: 0x00000101, Handle: 39, ESP_02 [FC] */, 
  IlMsgESP_01PreCopy /* ID: 0x00000100, Handle: 40, ESP_01 [FC] */, 
  IlMsgMiko_01_PAGPreCopy /* ID: 0x000000c1, Handle: 41, Miko_01_PAG [BC] */, 
  IlMsgMotor_02_sekPreCopy /* ID: 0x0000007e, Handle: 42, Motor_02_sek [BC] */, 
  TpPrecopy /* ID: 0x00000773, Handle: 43, ISO_Info_El_Req [FC] */, 
  TpFuncPrecopy /* ID: 0x00000700, Handle: 44, ISO_Funktionaler_Req_All [FC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_INDICATION_FCT
void CanRxDiagnose_01IndicationFct(CanReceiveHandle rcvObject)
{
  Diagnose_01_RxMsg(rcvObject);
  IlMsgDiagnose_01Indication(rcvObject);
}


void CanRxGateway_03IndicationFct(CanReceiveHandle rcvObject)
{
  Gateway_03_RxMsg(rcvObject);
  IlMsgGateway_03Indication(rcvObject);
}


void CanRxGW_Mmi_07_PAGIndicationFct(CanReceiveHandle rcvObject)
{
  GW_Mmi_07_PAG_RxMsg(rcvObject);
  IlMsgGW_Mmi_07_PAGIndication(rcvObject);
}


void CanRxGW_Mmi_06_PAGIndicationFct(CanReceiveHandle rcvObject)
{
  GW_Mmi_06_PAG_RxMsg(rcvObject);
  IlMsgGW_Mmi_06_PAGIndication(rcvObject);
}


void CanRxSysteminfo_01IndicationFct(CanReceiveHandle rcvObject)
{
  Systeminfo_01_RxMsg(rcvObject);
  IlMsgSysteminfo_01Indication(rcvObject);
}


void CanRxHVLM_07_PAGIndicationFct(CanReceiveHandle rcvObject)
{
  HVLM_07_PAG_RxMsg(rcvObject);
  IlMsgHVLM_07_PAGIndication(rcvObject);
}


void CanRxGW_Mmi_10_PAGIndicationFct(CanReceiveHandle rcvObject)
{
  GW_Mmi_10_PAG_RxMsg(rcvObject);
  IlMsgGW_Mmi_10_PAGIndication(rcvObject);
}


void CanRxGateway_01IndicationFct(CanReceiveHandle rcvObject)
{
  Gateway_01_RxMsg(rcvObject);
  IlMsgGateway_01Indication(rcvObject);
}


void CanRxGW_Mmi_01_PAGIndicationFct(CanReceiveHandle rcvObject)
{
  GW_Mmi_01_PAG_RxMsg(rcvObject);
  IlMsgGW_Mmi_01_PAGIndication(rcvObject);
}


void CanRxGW_Mmi_05_PAGIndicationFct(CanReceiveHandle rcvObject)
{
  GW_Mmi_05_PAG_RxMsg(rcvObject);
  IlMsgGW_Mmi_05_PAGIndication(rcvObject);
}


void CanRxGW_Mmi_04_PAGIndicationFct(CanReceiveHandle rcvObject)
{
  GW_Mmi_04_PAG_RxMsg(rcvObject);
  IlMsgGW_Mmi_04_PAGIndication(rcvObject);
}


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 ApplIndicationFct V_MEMROM2 CanRxApplIndicationPtr[kCanNumberOfRxObjects] = 
{
  Kombi_11_PAG_RxMsg /* ID: 0x000006bd, Handle: 0, Kombi_11_PAG [FC] */, 
  Kombi_02_RxMsg /* ID: 0x000006b7, Handle: 1, Kombi_02 [FC] */, 
  VIN_01_RxMsg /* ID: 0x000006b4, Handle: 2, VIN_01 [BC] */, 
  CanRxDiagnose_01IndicationFct /* ID: 0x000006b2, Handle: 3, Diagnose_01 [FC] */, 
  LAD_02_RxMsg /* ID: 0x0000067e, Handle: 4, LAD_02 [BC] */, 
  RDK_02_PAG_RxMsg /* ID: 0x00000674, Handle: 5, RDK_02_PAG [BC] */, 
  Klima_03_RxMsg /* ID: 0x0000066e, Handle: 6, Klima_03 [FC] */, 
  CanRxGateway_03IndicationFct /* ID: 0x0000066b, Handle: 7, Gateway_03 [FC] */, 
  Klima_02_RxMsg /* ID: 0x00000664, Handle: 8, Klima_02 [FC] */, 
  BEM_02_RxMsg /* ID: 0x00000663, Handle: 9, BEM_02 [FC] */, 
  BCM1_02_RxMsg /* ID: 0x00000662, Handle: 10, BCM1_02 [FC] */, 
  Kombi_19_PAG_RxMsg /* ID: 0x000005ff, Handle: 11, Kombi_19_PAG [BC] */, 
  CanRxGW_Mmi_07_PAGIndicationFct /* ID: 0x000005ec, Handle: 12, GW_Mmi_07_PAG [FC] */, 
  CanRxGW_Mmi_06_PAGIndicationFct /* ID: 0x000005eb, Handle: 13, GW_Mmi_06_PAG [FC] */, 
  MFL_Tasten_Kon_01_RxMsg /* ID: 0x000005bf, Handle: 14, MFL_Tasten_Kon_01 [BC] */, 
  HVLM_05_RxMsg /* ID: 0x00000594, Handle: 15, HVLM_05 [FC] */, 
  CanRxSysteminfo_01IndicationFct /* ID: 0x00000585, Handle: 16, Systeminfo_01 [BC] */, 
  CanRxHVLM_07_PAGIndicationFct /* ID: 0x00000575, Handle: 17, HVLM_07_PAG [BC] */, 
  Kombi_EV_01_PAG_RxMsg /* ID: 0x0000053f, Handle: 18, Kombi_EV_01_PAG [BC] */, 
  Kombi_14_PAG_RxMsg /* ID: 0x00000533, Handle: 19, Kombi_14_PAG [FC] */, 
  Lift_01_RxMsg /* ID: 0x00000529, Handle: 20, Lift_01 [BC] */, 
  NPM_01_PAG_RxMsg /* ID: 0x00000484, Handle: 21, NPM_01_PAG [BC] */, 
  CanRxGW_Mmi_10_PAGIndicationFct /* ID: 0x00000444, Handle: 22, GW_Mmi_10_PAG [FC] */, 
  Motor_06_RxMsg /* ID: 0x00000440, Handle: 23, Motor_06 [BC] */, 
  CanRxGateway_01IndicationFct /* ID: 0x000003c3, Handle: 24, Gateway_01 [FC] */, 
  Klemmen_Status_01_RxMsg /* ID: 0x000003c0, Handle: 25, Klemmen_Status_01 [FC] */, 
  Motor_15_PAG_RxMsg /* ID: 0x000003a5, Handle: 26, Motor_15_PAG [BC] */, 
  Motor_K_02_RxMsg /* ID: 0x000003a3, Handle: 27, Motor_K_02 [BC] */, 
  Kombi_17_PAG_RxMsg /* ID: 0x0000039b, Handle: 28, Kombi_17_PAG [FC] */, 
  Kombi_16_PAG_RxMsg /* ID: 0x0000039a, Handle: 29, Kombi_16_PAG [FC] */, 
  CanRxGW_Mmi_01_PAGIndicationFct /* ID: 0x0000038d, Handle: 30, GW_Mmi_01_PAG [FC] */, 
  CanRxGW_Mmi_05_PAGIndicationFct /* ID: 0x0000038c, Handle: 31, GW_Mmi_05_PAG [FC] */, 
  BCM2_03_PAG_RxMsg /* ID: 0x00000384, Handle: 32, BCM2_03_PAG [FC] */, 
  Klima_13_PAG_RxMsg /* ID: 0x0000037f, Handle: 33, Klima_13_PAG [BC] */, 
  CanRxGW_Mmi_04_PAGIndicationFct /* ID: 0x0000031c, Handle: 34, GW_Mmi_04_PAG [FC] */, 
  Kombi_10_PAG_RxMsg /* ID: 0x0000031a, Handle: 35, Kombi_10_PAG [FC] */, 
  Kombi_13_PAG_RxMsg /* ID: 0x0000011a, Handle: 36, Kombi_13_PAG [FC] */, 
  ESP_10_RxMsg /* ID: 0x00000116, Handle: 37, ESP_10 [FC] */, 
  Getriebe_03_RxMsg /* ID: 0x00000102, Handle: 38, Getriebe_03 [FC] */, 
  ESP_02_RxMsg /* ID: 0x00000101, Handle: 39, ESP_02 [FC] */, 
  ESP_01_RxMsg /* ID: 0x00000100, Handle: 40, ESP_01 [FC] */, 
  Miko_01_PAG_RxMsg /* ID: 0x000000c1, Handle: 41, Miko_01_PAG [BC] */, 
  Motor_02_sek_RxMsg /* ID: 0x0000007e, Handle: 42, Motor_02_sek [BC] */, 
  V_NULL /* ID: 0x00000773, Handle: 43, ISO_Info_El_Req [FC] */, 
  V_NULL /* ID: 0x00000700, Handle: 44, ISO_Funktionaler_Req_All [FC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_INDICATION_FLAG
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanIndicationOffset[kCanNumberOfRxObjects] = 
{
  0 /* ID: 0x000006bd, Handle: 0, Kombi_11_PAG [FC] */, 
  0 /* ID: 0x000006b7, Handle: 1, Kombi_02 [FC] */, 
  0 /* ID: 0x000006b4, Handle: 2, VIN_01 [BC] */, 
  0 /* ID: 0x000006b2, Handle: 3, Diagnose_01 [FC] */, 
  0 /* ID: 0x0000067e, Handle: 4, LAD_02 [BC] */, 
  0 /* ID: 0x00000674, Handle: 5, RDK_02_PAG [BC] */, 
  0 /* ID: 0x0000066e, Handle: 6, Klima_03 [FC] */, 
  0 /* ID: 0x0000066b, Handle: 7, Gateway_03 [FC] */, 
  0 /* ID: 0x00000664, Handle: 8, Klima_02 [FC] */, 
  0 /* ID: 0x00000663, Handle: 9, BEM_02 [FC] */, 
  0 /* ID: 0x00000662, Handle: 10, BCM1_02 [FC] */, 
  0 /* ID: 0x000005ff, Handle: 11, Kombi_19_PAG [BC] */, 
  0 /* ID: 0x000005ec, Handle: 12, GW_Mmi_07_PAG [FC] */, 
  0 /* ID: 0x000005eb, Handle: 13, GW_Mmi_06_PAG [FC] */, 
  0 /* ID: 0x000005bf, Handle: 14, MFL_Tasten_Kon_01 [BC] */, 
  0 /* ID: 0x00000594, Handle: 15, HVLM_05 [FC] */, 
  0 /* ID: 0x00000585, Handle: 16, Systeminfo_01 [BC] */, 
  0 /* ID: 0x00000575, Handle: 17, HVLM_07_PAG [BC] */, 
  0 /* ID: 0x0000053f, Handle: 18, Kombi_EV_01_PAG [BC] */, 
  0 /* ID: 0x00000533, Handle: 19, Kombi_14_PAG [FC] */, 
  0 /* ID: 0x00000529, Handle: 20, Lift_01 [BC] */, 
  0 /* ID: 0x00000484, Handle: 21, NPM_01_PAG [BC] */, 
  0 /* ID: 0x00000444, Handle: 22, GW_Mmi_10_PAG [FC] */, 
  0 /* ID: 0x00000440, Handle: 23, Motor_06 [BC] */, 
  0 /* ID: 0x000003c3, Handle: 24, Gateway_01 [FC] */, 
  0 /* ID: 0x000003c0, Handle: 25, Klemmen_Status_01 [FC] */, 
  0 /* ID: 0x000003a5, Handle: 26, Motor_15_PAG [BC] */, 
  0 /* ID: 0x000003a3, Handle: 27, Motor_K_02 [BC] */, 
  0 /* ID: 0x0000039b, Handle: 28, Kombi_17_PAG [FC] */, 
  0 /* ID: 0x0000039a, Handle: 29, Kombi_16_PAG [FC] */, 
  0 /* ID: 0x0000038d, Handle: 30, GW_Mmi_01_PAG [FC] */, 
  0 /* ID: 0x0000038c, Handle: 31, GW_Mmi_05_PAG [FC] */, 
  0 /* ID: 0x00000384, Handle: 32, BCM2_03_PAG [FC] */, 
  0 /* ID: 0x0000037f, Handle: 33, Klima_13_PAG [BC] */, 
  0 /* ID: 0x0000031c, Handle: 34, GW_Mmi_04_PAG [FC] */, 
  0 /* ID: 0x0000031a, Handle: 35, Kombi_10_PAG [FC] */, 
  0 /* ID: 0x0000011a, Handle: 36, Kombi_13_PAG [FC] */, 
  0 /* ID: 0x00000116, Handle: 37, ESP_10 [FC] */, 
  0 /* ID: 0x00000102, Handle: 38, Getriebe_03 [FC] */, 
  0 /* ID: 0x00000101, Handle: 39, ESP_02 [FC] */, 
  0 /* ID: 0x00000100, Handle: 40, ESP_01 [FC] */, 
  0 /* ID: 0x000000c1, Handle: 41, Miko_01_PAG [BC] */, 
  0 /* ID: 0x0000007e, Handle: 42, Motor_02_sek [BC] */, 
  0 /* ID: 0x00000773, Handle: 43, ISO_Info_El_Req [FC] */, 
  0 /* ID: 0x00000700, Handle: 44, ISO_Funktionaler_Req_All [FC] */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanIndicationMask[kCanNumberOfRxObjects] = 
{
  0x00 /* ID: 0x000006bd, Handle: 0, Kombi_11_PAG [FC] */, 
  0x00 /* ID: 0x000006b7, Handle: 1, Kombi_02 [FC] */, 
  0x00 /* ID: 0x000006b4, Handle: 2, VIN_01 [BC] */, 
  0x00 /* ID: 0x000006b2, Handle: 3, Diagnose_01 [FC] */, 
  0x00 /* ID: 0x0000067e, Handle: 4, LAD_02 [BC] */, 
  0x00 /* ID: 0x00000674, Handle: 5, RDK_02_PAG [BC] */, 
  0x00 /* ID: 0x0000066e, Handle: 6, Klima_03 [FC] */, 
  0x00 /* ID: 0x0000066b, Handle: 7, Gateway_03 [FC] */, 
  0x00 /* ID: 0x00000664, Handle: 8, Klima_02 [FC] */, 
  0x00 /* ID: 0x00000663, Handle: 9, BEM_02 [FC] */, 
  0x00 /* ID: 0x00000662, Handle: 10, BCM1_02 [FC] */, 
  0x00 /* ID: 0x000005ff, Handle: 11, Kombi_19_PAG [BC] */, 
  0x00 /* ID: 0x000005ec, Handle: 12, GW_Mmi_07_PAG [FC] */, 
  0x00 /* ID: 0x000005eb, Handle: 13, GW_Mmi_06_PAG [FC] */, 
  0x00 /* ID: 0x000005bf, Handle: 14, MFL_Tasten_Kon_01 [BC] */, 
  0x00 /* ID: 0x00000594, Handle: 15, HVLM_05 [FC] */, 
  0x00 /* ID: 0x00000585, Handle: 16, Systeminfo_01 [BC] */, 
  0x00 /* ID: 0x00000575, Handle: 17, HVLM_07_PAG [BC] */, 
  0x00 /* ID: 0x0000053f, Handle: 18, Kombi_EV_01_PAG [BC] */, 
  0x00 /* ID: 0x00000533, Handle: 19, Kombi_14_PAG [FC] */, 
  0x00 /* ID: 0x00000529, Handle: 20, Lift_01 [BC] */, 
  0x00 /* ID: 0x00000484, Handle: 21, NPM_01_PAG [BC] */, 
  0x00 /* ID: 0x00000444, Handle: 22, GW_Mmi_10_PAG [FC] */, 
  0x00 /* ID: 0x00000440, Handle: 23, Motor_06 [BC] */, 
  0x00 /* ID: 0x000003c3, Handle: 24, Gateway_01 [FC] */, 
  0x00 /* ID: 0x000003c0, Handle: 25, Klemmen_Status_01 [FC] */, 
  0x00 /* ID: 0x000003a5, Handle: 26, Motor_15_PAG [BC] */, 
  0x00 /* ID: 0x000003a3, Handle: 27, Motor_K_02 [BC] */, 
  0x00 /* ID: 0x0000039b, Handle: 28, Kombi_17_PAG [FC] */, 
  0x00 /* ID: 0x0000039a, Handle: 29, Kombi_16_PAG [FC] */, 
  0x00 /* ID: 0x0000038d, Handle: 30, GW_Mmi_01_PAG [FC] */, 
  0x00 /* ID: 0x0000038c, Handle: 31, GW_Mmi_05_PAG [FC] */, 
  0x00 /* ID: 0x00000384, Handle: 32, BCM2_03_PAG [FC] */, 
  0x00 /* ID: 0x0000037f, Handle: 33, Klima_13_PAG [BC] */, 
  0x00 /* ID: 0x0000031c, Handle: 34, GW_Mmi_04_PAG [FC] */, 
  0x00 /* ID: 0x0000031a, Handle: 35, Kombi_10_PAG [FC] */, 
  0x00 /* ID: 0x0000011a, Handle: 36, Kombi_13_PAG [FC] */, 
  0x00 /* ID: 0x00000116, Handle: 37, ESP_10 [FC] */, 
  0x00 /* ID: 0x00000102, Handle: 38, Getriebe_03 [FC] */, 
  0x00 /* ID: 0x00000101, Handle: 39, ESP_02 [FC] */, 
  0x00 /* ID: 0x00000100, Handle: 40, ESP_01 [FC] */, 
  0x00 /* ID: 0x000000c1, Handle: 41, Miko_01_PAG [BC] */, 
  0x00 /* ID: 0x0000007e, Handle: 42, Motor_02_sek [BC] */, 
  0x00 /* ID: 0x00000773, Handle: 43, ISO_Info_El_Req [FC] */, 
  0x00 /* ID: 0x00000700, Handle: 44, ISO_Funktionaler_Req_All [FC] */
};
/* ROM CATEGORY 1 END */


#endif




/* -----------------------------------------------------------------------------
    &&&~ Init structures
 ----------------------------------------------------------------------------- */

/* ROM CATEGORY 4 START */
/* ROM CATEGORY 4 END */

/* ROM CATEGORY 4 START */
V_MEMROM0 V_MEMROM1 vuint32 V_MEMROM2 CanInitBTC[kCanNumberOfInitObjects] = 
{
  0x00010252
};
V_MEMROM0 V_MEMROM1 vuint32 V_MEMROM2 CanInitLAM0[kCanNumberOfInitObjects] = 
{
  0x1FFC0000
};
V_MEMROM0 V_MEMROM1 vuint32 V_MEMROM2 CanInitMID1[kCanNumberOfInitObjects] = 
{
  0x00000000
};
/* ROM CATEGORY 4 END */



#if defined(C_ENABLE_MULTI_ECU_CONFIG)
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanPhysToLogChannel[kVNumberOfIdentities][kCanNumberOfPhysChannels] = 
{
  
  {
    0
  }
};
/* ROM CATEGORY 1 END */

#endif

#if defined(C_ENABLE_MULTI_ECU_CONFIG)
/* ROM CATEGORY 2 START */

V_MEMROM0 V_MEMROM1 tVIdentityMsk V_MEMROM2 CanChannelIdentityAssignment[kCanNumberOfChannels] = 
{
  0x01
};

/* ROM CATEGORY 2 END */

#endif

#if defined(C_ENABLE_MULTI_ECU_PHYS)
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 tVIdentityMsk V_MEMROM2 CanRxIdentityAssignment[kCanNumberOfRxObjects] = 
{
  0x01 /* ID: 0x000006bd, Handle: 0, Kombi_11_PAG [FC] */, 
  0x01 /* ID: 0x000006b7, Handle: 1, Kombi_02 [FC] */, 
  0x01 /* ID: 0x000006b4, Handle: 2, VIN_01 [BC] */, 
  0x01 /* ID: 0x000006b2, Handle: 3, Diagnose_01 [FC] */, 
  0x01 /* ID: 0x0000067e, Handle: 4, LAD_02 [BC] */, 
  0x01 /* ID: 0x00000674, Handle: 5, RDK_02_PAG [BC] */, 
  0x01 /* ID: 0x0000066e, Handle: 6, Klima_03 [FC] */, 
  0x01 /* ID: 0x0000066b, Handle: 7, Gateway_03 [FC] */, 
  0x01 /* ID: 0x00000664, Handle: 8, Klima_02 [FC] */, 
  0x01 /* ID: 0x00000663, Handle: 9, BEM_02 [FC] */, 
  0x01 /* ID: 0x00000662, Handle: 10, BCM1_02 [FC] */, 
  0x01 /* ID: 0x000005ff, Handle: 11, Kombi_19_PAG [BC] */, 
  0x01 /* ID: 0x000005ec, Handle: 12, GW_Mmi_07_PAG [FC] */, 
  0x01 /* ID: 0x000005eb, Handle: 13, GW_Mmi_06_PAG [FC] */, 
  0x01 /* ID: 0x000005bf, Handle: 14, MFL_Tasten_Kon_01 [BC] */, 
  0x01 /* ID: 0x00000594, Handle: 15, HVLM_05 [FC] */, 
  0x01 /* ID: 0x00000585, Handle: 16, Systeminfo_01 [BC] */, 
  0x01 /* ID: 0x00000575, Handle: 17, HVLM_07_PAG [BC] */, 
  0x01 /* ID: 0x0000053f, Handle: 18, Kombi_EV_01_PAG [BC] */, 
  0x01 /* ID: 0x00000533, Handle: 19, Kombi_14_PAG [FC] */, 
  0x01 /* ID: 0x00000529, Handle: 20, Lift_01 [BC] */, 
  0x01 /* ID: 0x00000484, Handle: 21, NPM_01_PAG [BC] */, 
  0x01 /* ID: 0x00000444, Handle: 22, GW_Mmi_10_PAG [FC] */, 
  0x01 /* ID: 0x00000440, Handle: 23, Motor_06 [BC] */, 
  0x01 /* ID: 0x000003c3, Handle: 24, Gateway_01 [FC] */, 
  0x01 /* ID: 0x000003c0, Handle: 25, Klemmen_Status_01 [FC] */, 
  0x01 /* ID: 0x000003a5, Handle: 26, Motor_15_PAG [BC] */, 
  0x01 /* ID: 0x000003a3, Handle: 27, Motor_K_02 [BC] */, 
  0x01 /* ID: 0x0000039b, Handle: 28, Kombi_17_PAG [FC] */, 
  0x01 /* ID: 0x0000039a, Handle: 29, Kombi_16_PAG [FC] */, 
  0x01 /* ID: 0x0000038d, Handle: 30, GW_Mmi_01_PAG [FC] */, 
  0x01 /* ID: 0x0000038c, Handle: 31, GW_Mmi_05_PAG [FC] */, 
  0x01 /* ID: 0x00000384, Handle: 32, BCM2_03_PAG [FC] */, 
  0x01 /* ID: 0x0000037f, Handle: 33, Klima_13_PAG [BC] */, 
  0x01 /* ID: 0x0000031c, Handle: 34, GW_Mmi_04_PAG [FC] */, 
  0x01 /* ID: 0x0000031a, Handle: 35, Kombi_10_PAG [FC] */, 
  0x01 /* ID: 0x0000011a, Handle: 36, Kombi_13_PAG [FC] */, 
  0x01 /* ID: 0x00000116, Handle: 37, ESP_10 [FC] */, 
  0x01 /* ID: 0x00000102, Handle: 38, Getriebe_03 [FC] */, 
  0x01 /* ID: 0x00000101, Handle: 39, ESP_02 [FC] */, 
  0x01 /* ID: 0x00000100, Handle: 40, ESP_01 [FC] */, 
  0x01 /* ID: 0x000000c1, Handle: 41, Miko_01_PAG [BC] */, 
  0x01 /* ID: 0x0000007e, Handle: 42, Motor_02_sek [BC] */, 
  0x01 /* ID: 0x00000773, Handle: 43, ISO_Info_El_Req [FC] */, 
  0x01 /* ID: 0x00000700, Handle: 44, ISO_Funktionaler_Req_All [FC] */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 4 START */
V_MEMROM0 V_MEMROM1 tVIdentityMsk V_MEMROM2 CanTxIdentityAssignment[kCanNumberOfTxObjects] = 
{
  0x01 /* ID: 0x000007dd, Handle: 0, ISO_Info_El_Resp [BC] */, 
  0x01 /* ID: 0x000006d3, Handle: 1, NMH_CDR_PCM [BC] */, 
  0x01 /* ID: 0x000006ab, Handle: 2, PCM_CDR_01_PAG [BC] */, 
  0x01 /* ID: 0x000006a8, Handle: 3, Mem_Kombi_01_PAG [BC] */, 
  0x01 /* ID: 0x00000666, Handle: 4, Kombi_09_PAG [BC] */, 
  0x01 /* ID: 0x00000643, Handle: 5, Einheiten_01 [BC] */, 
  0x01 /* ID: 0x000005fe, Handle: 6, Kombi_18_PAG [BC] */, 
  0x01 /* ID: 0x000005fa, Handle: 7, PCM_04_PAG [BC] */, 
  0x01 /* ID: 0x00000539, Handle: 8, PCM_02_PAG [BC] */, 
  0x01 /* ID: 0x000000c2, Handle: 9, ADR_02_PAG [BC] */, 
  0x01 /* ID: 0x000000c0, Handle: 10, ADR_01_PAG [BC] */
};
/* ROM CATEGORY 4 END */

#endif


#ifdef C_ENABLE_TX_FULLCAN_OBJECTS
/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanTxHwObj[kCanNumberOfTxObjects] = 
{
  0x1F /* ID: 0x000007dd, Handle: 0, ISO_Info_El_Resp [BC] */, 
  0x1F /* ID: 0x000006d3, Handle: 1, NMH_CDR_PCM [BC] */, 
  0x1F /* ID: 0x000006ab, Handle: 2, PCM_CDR_01_PAG [BC] */, 
  0x1F /* ID: 0x000006a8, Handle: 3, Mem_Kombi_01_PAG [BC] */, 
  0x1F /* ID: 0x00000666, Handle: 4, Kombi_09_PAG [BC] */, 
  0x1F /* ID: 0x00000643, Handle: 5, Einheiten_01 [BC] */, 
  0x1F /* ID: 0x000005fe, Handle: 6, Kombi_18_PAG [BC] */, 
  0x1F /* ID: 0x000005fa, Handle: 7, PCM_04_PAG [BC] */, 
  0x1F /* ID: 0x00000539, Handle: 8, PCM_02_PAG [BC] */, 
  0x1F /* ID: 0x000000c2, Handle: 9, ADR_02_PAG [BC] */, 
  0x1F /* ID: 0x000000c0, Handle: 10, ADR_01_PAG [BC] */
};
/* ROM CATEGORY 2 END */

#endif





/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 88863978
      #error "The magic number of the generated file <F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\src\can_par.c> is different. Please check time and date of generated files!"
  #endif
#else
  #error "The magic number is not defined in the generated file <F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\src\can_par.c> "

#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

