/* -----------------------------------------------------------------------------
  Filename:    ccl_par.c
  Description: Toolversion: 03.20.21.01.10.02.79.00.00.00
               
               Serial Number: CBD1100279
               Customer Info: Dr. Ing. h. c. F. Porsche AG
                              CBD / Porsche 2007+
                              Texas Instruments TMS470 / TMS470 R1SF55
                              Texas Instruments 4.6.6 Compiler
               
               
               Generator Fwk   : GENy 
               Generator Module: Ccl__core
               
               Configuration   : F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\cfg\Porsche_ADR.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470Cpu
                       Compiler:     TexasInstruments
                       Derivates:    TMS470R1
               
               Channel "Channel0":
                       Databasefile: F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\cfg\CAN_Matrix_Dashboard_2_11_0_X2_Release.dbc
                       Bussystem:    CAN
                       Manufacturer: Porsche AG
                       Node:         ADR_PAG_X2

  Generated by , 2012-02-15  08:51:07
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2010 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#define CCL_PAR_MODULE
#include "ccl_inc.h"
#include "ccl_par.h"

/******************************************************************************/
/* internal declarations (ROM const)                                          */
/******************************************************************************/
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 cclNpmPwuLevel[1] = {
    0x2
};

V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 cclNpmFsLevel[1] = {
    0x2
};

V_MEMROM0 static V_MEMROM1 vuint8 V_MEMROM2 cclNpmPwuEcuAdrMask[1] = {
    0x10
};

V_MEMROM0 static V_MEMROM1 vuint8 V_MEMROM2 cclNpmPwuEcuOffset[1] = {
    7
};

V_MEMROM0 static V_MEMROM1 vuint8 V_MEMROM2 cclNpmFsEcuAdrMask[1] = {
    0x2
};

V_MEMROM0 static V_MEMROM1 vuint8 V_MEMROM2 cclNpmFsEcuOffset[1] = {
    4
};

V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 cclNpmEcuAddress[1] = {
    0x18
};
/******************************************************************************/
/* external declarations (ROM const)                                          */
/******************************************************************************/
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 cclNmWakeUpAble = 0x1;   /* The variable store the wake up able channels (one bit per channel). */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 cclNmType[1] = {
    kComponentNmHigh
 };
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 cclStartIndex[1] = {
    0
};

V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 cclStopIndex[1] = {
    0
};

V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 cclNpmMsgTimeoutValue[1] = {
    500
};

V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 cclNmStartupTimerValue[1] = {
    35
};
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 cclUserOffset[4] = {
      0x0,   0x0,   0x0,   0x0
};

V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 cclUserMask[4] = {
      0x1,   0x2,   0x4,   0x8
};

V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 cclUserChannel[4] = {
    0x0, 0x0, 0x0, 0x0
};
/******************************************************************************/
/* global data definitions                                                    */
/******************************************************************************/
/***************************************************************************** 
| NAME:             CclInitPowerOnFct                                          
| PROTOTYPE:        void CclInitPowerOnFct( const tCclNmInitParaListType* nmInitPara )
| CALLED BY:        CclInitPowerOn                                             
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!          
| INPUT PARAMETERS: void                                                       
| RETURN VALUE:     void                                                       
| DESCRIPTION:      This function is a generated init container function. It   
|                   contains different init routines depending on the          
|                   used modules.                                              
|*****************************************************************************/

void CclInitPowerOnFct(const tCclNmInitParaListType* nmInitPara)
{
  #if defined(C_SINGLE_RECEIVE_CHANNEL) || defined(C_MULTIPLE_RECEIVE_CHANNEL)
    CanInitPowerOn();
  #else
    CanInitPowerOn(0);
  #endif
  IlInitPowerOn();
  if(nmInitPara->cclNmInit_0 == kCclNmInitSleep)
  {
    NmhInitPowerOn(NMH_INIT_SLEEP);
  }
  if(nmInitPara->cclNmInit_0 == kCclNmInitNormal)
  {
    NmhInitPowerOn(NMH_INIT_NORMAL);
    cclNmState[0] = kCclStateGoToSleep;
  }
  TpInitPowerOn();
  DescInitPowerOn(kDescPowerOnInitParam);
}
/***************************************************************************** 
| NAME:             CclInitFct                                                 
| PROTOTYPE:        void CclInitFct( const tCclNmInitParaListType* nmInitPara )
| CALLED BY:        CclInit                                                    
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!          
| INPUT PARAMETERS: void                                                       
| RETURN VALUE:     void                                                       
| DESCRIPTION:      This function is a generated init container function. It   
|                   contains different init routines depending on the          
|                   used modules.                                              
|*****************************************************************************/

void CclInitFct(const tCclNmInitParaListType* nmInitPara)
{
#if defined( C_MULTIPLE_RECEIVE_CHANNEL )
  CanInit(0, 0);
#else
  CanInit(0);
#endif
  IlInit();
  if(nmInitPara->cclNmInit_0 == kCclNmInitSleep)
  {
    NmhInit(NMH_INIT_SLEEP);
  }
  if(nmInitPara->cclNmInit_0 == kCclNmInitNormal)
  {
    NmhInit(NMH_INIT_NORMAL);
    cclNmState[0] = kCclStateGoToSleep;
  }
  ApplCclInit();
}
/*******************************************************************************
| NAME:             CclSystemStartupFct                                         
| PROTOTYPE:        void CclSystemStartupFct( void )                            
| CALLED BY:        CclSystemStartup                                            
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!           
| INPUT PARAMETERS: void                                                        
| RETURN VALUE:     void                                                        
| DESCRIPTION:      This function is a generated system startup container      
|                   function. It could be used to start services or initialize  
|                   variables before the system goes into the "normal" mode.  
|******************************************************************************/

void CclSystemStartupFct(void) 
{ 
}
/**************************************************************************************
| NAME:             CclSystemShutdownFct                                               
| PROTOTYPE:        void CclSystemShutdownFct( void )                                  
| CALLED BY:        CclSystemShutdown                                                  
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!                  
| INPUT PARAMETERS: void                                                               
| RETURN VALUE:     void                                                               
| DESCRIPTION:      This function is a generated system shutdown container             
|                   function. It could be used to stop services or deinitialize        
|                   variables after the system leaves the "normal" mode.             
|*************************************************************************************/

void CclSystemShutdownFct(void) 
{ 
}


/****************************************************************************************
| NAME:             CclScheduleTask                                                      
| PROTOTYPE:        void CclScheduleTask                                                 
| CALLED BY:        task handler                                                         
| PRECONDITIONS:    has to be called every 10ms                                           
| INPUT PARAMETERS: void                                                                 
| RETURN VALUE:     void                                                                 
| DESCRIPTION:      This function is a generated schedule task. This task call all other 
|                   task with in the right task cycle + offset.                          
|***************************************************************************************/
void CCL_API_CALL_TYPE CclScheduleTask(void)
{ 
  IlTxTask();

  IlRxTask(); 

  CclTask();

  NmhTask();

  TpRxTask();

  DescTask();

   TpTxTask();



}

/******************************************************************************
| NAME:             CclComStart                                                
| PROTOTYPE:        void CclComStart(void)                                  
| CALLED BY:        network management                                         
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!          
| INPUT PARAMETERS:                                                            
| RETURN VALUE:     void                                                       
| DESCRIPTION:      This function start the communication with interaction layer.
|*****************************************************************************/
void CclComStart(void)
{
  ApplCclComStart();
  IlTxStart();
  IlRxStart();
}
/******************************************************************************
| NAME:             CclComStop                                                 
| PROTOTYPE:        void CclComStop(void)                                      
| CALLED BY:        network management                                         
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!          
| INPUT PARAMETERS:                                                            
| RETURN VALUE:     void                                                       
| DESCRIPTION:      This function stop the communication with interaction layer.
|*****************************************************************************/
void CclComStop(void)
{
  IlTxStop();
  IlRxStop();
  ApplCclComStop();
}
/******************************************************************************
| NAME:             CclComWait                                                
| PROTOTYPE:        void CclComWait(void)                                  
| CALLED BY:        network management                                         
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!          
| INPUT PARAMETERS:                                                            
| RETURN VALUE:     void                                                       
| DESCRIPTION:      This function start the communication with interaction layer.
|*****************************************************************************/
void CclComWait(void)
{
  cclComSwState[0]=kCclComSwOff;
  ApplCclComWait();
  IlTxWait();
  IlRxWait();
}
/******************************************************************************
| NAME:             CclComResume                                                 
| PROTOTYPE:        void CclComResume(void)                                      
| CALLED BY:        network management                                         
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!          
| INPUT PARAMETERS:                                                            
| RETURN VALUE:     void                                                       
| DESCRIPTION:      This function stop the communication with interaction layer.
|*****************************************************************************/
void CclComResume(void)
{
  IlTxRelease();
  IlRxRelease();
  cclComSwState[0]=kCclComSwOn;
  ApplCclComResume();
}




/******************************************************************************
| NAME:             CclBusOffStart                                             
| PROTOTYPE:        void CclBusOffStart(void)                                  
| CALLED BY:        network management                                         
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!          
| INPUT PARAMETERS:                                          ,                 
| RETURN VALUE:     void                                                       
| DESCRIPTION:      This function stop the communication with interaction layer.
|*****************************************************************************/
void CclBusOffStart(void)
{
  #if defined( CCL_ENABLE_STOP_TIMEOUT)
    IlTxWait();
    IlRxWait();
  #endif
  ApplCclBusOffStart();
}
/******************************************************************************
| NAME:             CclBusOffEnd                                               
| PROTOTYPE:        void CclBusOffEnd(void)                                    
| CALLED BY:        network management                                         
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!          
| INPUT PARAMETERS:                                                            
| RETURN VALUE:     void                                                       
| DESCRIPTION:      This function start the communication with interaction layer.
|*****************************************************************************/
void CclBusOffEnd(void)
{
  #if defined(CCL_ENABLE_STOP_TIMEOUT)
    IlTxRelease();
    IlRxRelease();
  #endif
  ApplCclBusOffEnd();
}

/**********************************************************************************
| NAME:             CclNmActiveReqFct                                              
| PROTOTYPE:        vuint8 CclNmActiveReqFct( vuint8 network )                     
| CALLED BY:        CclTask                                                        
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!              
| INPUT PARAMETERS: vuint8 network                                                 
| RETURN VALUE:     vuint8                                                         
| DESCRIPTION:      This function contains the algorithm to go in the active       
|                   mode. The algorithm depends on the used modules.               
|*********************************************************************************/

vuint8 CclNmActiveReqFct(vuint8 network)
{
  network = network;

   NmhRequestCommState(NMH_NORMAL_OPERATION);
  return NM_OK;
}
/***********************************************************************************
| NAME:             CclNmPrepareSleepReqFct                                          
| PROTOTYPE:        void CclNmPrepareSleepReqFct( void )                             
| CALLED BY:        CclTask                                                          
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!                
| INPUT PARAMETERS: void                                                             
| RETURN VALUE:     void                                                             
| DESCRIPTION:      This function contains the algorithm to set the system in        
|                   prepare sleep mode. The algorithm depends on the used            
|                   modules.                                                         
|***********************************************************************************/

void CclNmPrepareSleepReqFct(void)
{
  NmhWakeUpRequest();
}
/***********************************************************************************
| NAME:             CclNmSleepReqFct                                                
| PROTOTYPE:        void CclNmSleepReqFct( vuint8 network )                         
| CALLED BY:        CclRelNetRequest                                                
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!               
| INPUT PARAMETERS: vuint8 network                                                  
| RETURN VALUE:     void                                                            
| DESCRIPTION:      This function contains the algorithm to go in the sleep         
|                   mode. The algorithm depends on the used modules.                
|**********************************************************************************/
void CclNmSleepReqFct(vuint8 network)
{
  network = network;

   NmhRequestCommState(NMH_READY_SLEEP);
}

/********************************************************************************
| NAME:             CclExtCanComReqFct                                              
| PROTOTYPE:        void CclExtCanComReqFct(void)                                   
| CALLED BY:        ApplCanWakeUp,                                               
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!            
| INPUT PARAMETERS: void                                                         
| RETURN VALUE:     void                                                         
| DESCRIPTION:      This function sets a communication flag. This flag is        
|                   used to synchronize the state requests between CCL           
|                   and higher layer component.                                             
|*******************************************************************************/

void CclExtCanComReqFct(void)
{
  ApplCclNetworkWakeup();
}
/********************************************************************************
| NAME:             CclIntComReqFct                                              
| PROTOTYPE:        void CclIntComReqFct(void)                                   
| CALLED BY:        CclRequestNetwork                                            
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!            
| INPUT PARAMETERS: void                                                         
| RETURN VALUE:     void                                                         
| DESCRIPTION:      This function sets a communication flag. This flag is        
|                   used to synchronize the state requests between CCL           
|                   and higher layer component.                                             
|*******************************************************************************/

void CclIntComReqFct(void)
{
  ApplCclLocalWakeup();
}
/********************************************************************************
| NAME:             CclComRelFct                                            
| PROTOTYPE:        void CclComRelFct(void)                                 
| CALLED BY:        ApplNmCanSleep                                               
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!            
| INPUT PARAMETERS: void                                                         
| RETURN VALUE:     void                                                         
| DESCRIPTION:      This function clears a communication flag. This flag are     
|                   used to synchronize the state requests between CCL           
|                   and higher layer component.                                             
|*******************************************************************************/

void CclComRelFct(void)
{
  ApplCclSleep();
}

/********************************************************************************
| NAME:             CclInitTrcvFct                                              
| PROTOTYPE:        void CclInitTrcvFct( void )                                 
| CALLED BY:        CclInitPortsPowerOn                                          
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!            
| INPUT PARAMETERS: void                                                         
| RETURN VALUE:     void                                                         
| DESCRIPTION:      This function contains the transceiver init routine.         
|                   The routine depends on the used transceiver type.            
|*******************************************************************************/

void CclInitTrcvFct(void)
{
  ApplCclInitTrcv();
}
/************************************************************************************
| NAME:             CclWakeUpTrcvFct                                                
| PROTOTYPE:        void CclWakeUpTrcvFct( void )                                   
| CALLED BY:        ApplNmCanNormal                                                  
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!                
| INPUT PARAMETERS: void                                                             
| RETURN VALUE:     void                                                             
| DESCRIPTION:      This function contains the routine to wakeup the                 
|                   transceiver. The routine depends on the used transceiver         
|                   type.                                                            
|***********************************************************************************/

void CclWakeUpTrcvFct(void)
{ 
  ApplCclWakeUpTrcv();
}
/************************************************************************************
| NAME:             CclSleepTrcvFct                                                 
| PROTOTYPE:        void CclSleepTrcvFct( void )                                    
| CALLED BY:        ApplNmCanSleep                                                   
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!                
| INPUT PARAMETERS: void                                                             
| RETURN VALUE:     void                                                             
| DESCRIPTION:      This function contains the routine to switch the                 
|                   transceiver into sleep mode. The routine depends on              
|                   the used transceiver type.                                       
|***********************************************************************************/

void CclSleepTrcvFct(void)
{
  ApplCclStandbyTrcv();
  ApplCclSleepTrcv();
}







/************************************************************************************
| NAME:             ApplCclNpmPrecopy                                                
| PROTOTYPE:        void ApplCclNpmPrecopy( CanRxInfoStructPtr rxStruct )            
| CALLED BY:        CanDriver                                                        
| PRECONDITIONS:    Application is NOT ALLOWED to call this function!                
| INPUT PARAMETERS: void                                                             
| RETURN VALUE:     void                                                             
| DESCRIPTION:      
|***********************************************************************************/
vuint8 ApplCclNpmPrecopy(CanRxInfoStructPtr rxStruct)
{
  vuint8 cclNpmDirectAddrBit;
  vuint8 cclNpmPwFsLevelData;
  vuint8 cclNpmLevel;

  cclNpmMsgDataTmp[rxStruct->Channel] = kCclNpmMessageReceived;

  cclNpmDirectAddrBit = (*((rxStruct->pChipData) + 1));
  cclNpmDirectAddrBit &= (vuint8)0x01;

  if(cclNpmDirectAddrBit == 0x00)
  {
    /* get NPM message PW and FS level */
    cclNpmPwFsLevelData = (*(rxStruct->pChipData));

#if defined(CCL_ENABLE_PREVENT_WAKEUP)
    /* check the prevent wake up level */
    cclNpmLevel = (cclNpmPwFsLevelData & (vuint8)0xF0);
    cclNpmLevel = cclNpmLevel >> 4;
    if(cclNpmLevel >= cclNpmPwuLevel[rxStruct->Channel])
    {
      cclNpmMsgDataTmp[rxStruct->Channel] |= kCclNpmPreventWakeUpOn;
    }
#endif
#if defined(CCL_ENABLE_FORCE_SHUTDOWN)
    /* check force shutdown level */
    cclNpmLevel = (cclNpmPwFsLevelData & (vuint8)0x0F);
    if(cclNpmLevel >= cclNpmFsLevel[rxStruct->Channel])
    {
      cclNpmMsgDataTmp[rxStruct->Channel] |= kCclNpmForceShutdownOn;
    }
#endif
  }
  else
  {
    /* Direct addresse mode activated by master! Check if we are addressed.
     * GenTool generates mask values for configured NPM address   */
#if defined(CCL_ENABLE_PREVENT_WAKEUP)
    if( ((*((rxStruct->pChipData) + cclNpmPwuEcuOffset[rxStruct->Channel])) & cclNpmPwuEcuAdrMask[rxStruct->Channel]) > 0x00)
    {
      cclNpmMsgDataTmp[rxStruct->Channel] |= kCclNpmPreventWakeUpOn;
    }
#endif

#if defined(CCL_ENABLE_FORCE_SHUTDOWN)
    if( ((*((rxStruct->pChipData) + cclNpmFsEcuOffset[rxStruct->Channel])) & cclNpmFsEcuAdrMask[rxStruct->Channel]) > 0x00)
    {
      cclNpmMsgDataTmp[rxStruct->Channel] |= kCclNpmForceShutdownOn;
    }
#endif
   }

  return kCanNoCopyData;
}


/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 88863978
      #error "The magic number of the generated file <F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\src\ccl_par.c> is different. Please check time and date of generated files!"
  #endif
#else
  #error "The magic number is not defined in the generated file <F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\src\ccl_par.c> "

#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

