/* -----------------------------------------------------------------------------
  Filename:    drv_par.c
  Description: Toolversion: 03.20.21.01.10.02.79.00.00.00
               
               Serial Number: CBD1100279
               Customer Info: Dr. Ing. h. c. F. Porsche AG
                              CBD / Porsche 2007+
                              Texas Instruments TMS470 / TMS470 R1SF55
                              Texas Instruments 4.6.6 Compiler
               
               
               Generator Fwk   : GENy 
               Generator Module: GenTool_GenyDriverBase
               
               Configuration   : F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\cfg\Porsche_ADR.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470Cpu
                       Compiler:     TexasInstruments
                       Derivates:    TMS470R1
               
               Channel "Channel0":
                       Databasefile: F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\cfg\CAN_Matrix_Dashboard_2_11_0_X2_Release.dbc
                       Bussystem:    CAN
                       Manufacturer: Porsche AG
                       Node:         ADR_PAG_X2

  Generated by , 2012-02-15  08:51:07
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2010 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#include "v_inc.h"
#include "can_inc.h"

#include "drv_par.h"
/* -----------------------------------------------------------------------------
    &&&~ Message Buffers
 ----------------------------------------------------------------------------- */

/* RAM CATEGORY 2 START */
V_MEMRAM0 V_MEMRAM1 _c_BCM1_02_buf V_MEMRAM2 BCM1_02;
V_MEMRAM0 V_MEMRAM1 _c_BCM2_03_PAG_buf V_MEMRAM2 BCM2_03_PAG;
V_MEMRAM0 V_MEMRAM1 _c_BEM_02_buf V_MEMRAM2 BEM_02;
V_MEMRAM0 V_MEMRAM1 _c_Diagnose_01_buf V_MEMRAM2 Diagnose_01;
V_MEMRAM0 V_MEMRAM1 _c_Einheiten_01_buf V_MEMRAM2 Einheiten_01;
V_MEMRAM0 V_MEMRAM1 _c_ESP_01_buf V_MEMRAM2 ESP_01;
V_MEMRAM0 V_MEMRAM1 _c_ESP_02_buf V_MEMRAM2 ESP_02;
V_MEMRAM0 V_MEMRAM1 _c_ESP_10_buf V_MEMRAM2 ESP_10;
V_MEMRAM0 V_MEMRAM1 _c_Gateway_01_buf V_MEMRAM2 Gateway_01;
V_MEMRAM0 V_MEMRAM1 _c_Gateway_03_buf V_MEMRAM2 Gateway_03;
V_MEMRAM0 V_MEMRAM1 _c_Getriebe_03_buf V_MEMRAM2 Getriebe_03;
V_MEMRAM0 V_MEMRAM1 _c_GW_Mmi_01_PAG_buf V_MEMRAM2 GW_Mmi_01_PAG;
V_MEMRAM0 V_MEMRAM1 _c_GW_Mmi_04_PAG_buf V_MEMRAM2 GW_Mmi_04_PAG;
V_MEMRAM0 V_MEMRAM1 _c_GW_Mmi_05_PAG_buf V_MEMRAM2 GW_Mmi_05_PAG;
V_MEMRAM0 V_MEMRAM1 _c_GW_Mmi_06_PAG_buf V_MEMRAM2 GW_Mmi_06_PAG;
V_MEMRAM0 V_MEMRAM1 _c_GW_Mmi_07_PAG_buf V_MEMRAM2 GW_Mmi_07_PAG;
V_MEMRAM0 V_MEMRAM1 _c_GW_Mmi_10_PAG_buf V_MEMRAM2 GW_Mmi_10_PAG;
V_MEMRAM0 V_MEMRAM1 _c_HVLM_05_buf V_MEMRAM2 HVLM_05;
V_MEMRAM0 V_MEMRAM1 _c_ISO_Info_El_Resp_buf V_MEMRAM2 ISO_Info_El_Resp;
V_MEMRAM0 V_MEMRAM1 _c_Klemmen_Status_01_buf V_MEMRAM2 Klemmen_Status_01;
V_MEMRAM0 V_MEMRAM1 _c_Klima_02_buf V_MEMRAM2 Klima_02;
V_MEMRAM0 V_MEMRAM1 _c_Klima_03_buf V_MEMRAM2 Klima_03;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_02_buf V_MEMRAM2 Kombi_02;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_09_PAG_buf V_MEMRAM2 Kombi_09_PAG;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_10_PAG_buf V_MEMRAM2 Kombi_10_PAG;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_11_PAG_buf V_MEMRAM2 Kombi_11_PAG;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_13_PAG_buf V_MEMRAM2 Kombi_13_PAG;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_14_PAG_buf V_MEMRAM2 Kombi_14_PAG;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_16_PAG_buf V_MEMRAM2 Kombi_16_PAG;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_17_PAG_buf V_MEMRAM2 Kombi_17_PAG;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_EV_01_PAG_buf V_MEMRAM2 Kombi_EV_01_PAG;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_18_PAG_buf V_MEMRAM2 Kombi_18_PAG;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_18_PAG_m1_buf V_MEMRAM2 Kombi_18_PAG_m1;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_18_PAG_m2_buf V_MEMRAM2 Kombi_18_PAG_m2;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_18_PAG_m3_buf V_MEMRAM2 Kombi_18_PAG_m3;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_18_PAG_m4_buf V_MEMRAM2 Kombi_18_PAG_m4;
V_MEMRAM0 V_MEMRAM1 _c_LAD_02_buf V_MEMRAM2 LAD_02;
V_MEMRAM0 V_MEMRAM1 _c_Lift_01_buf V_MEMRAM2 Lift_01;
V_MEMRAM0 V_MEMRAM1 _c_Mem_Kombi_01_PAG_buf V_MEMRAM2 Mem_Kombi_01_PAG;
V_MEMRAM0 V_MEMRAM1 _c_MFL_Tasten_Kon_01_buf V_MEMRAM2 MFL_Tasten_Kon_01;
V_MEMRAM0 V_MEMRAM1 _c_Motor_06_buf V_MEMRAM2 Motor_06;
V_MEMRAM0 V_MEMRAM1 _c_Motor_15_PAG_buf V_MEMRAM2 Motor_15_PAG;
V_MEMRAM0 V_MEMRAM1 _c_NMH_CDR_PCM_buf V_MEMRAM2 NMH_CDR_PCM;
V_MEMRAM0 V_MEMRAM1 _c_NPM_01_PAG_buf V_MEMRAM2 NPM_01_PAG;
V_MEMRAM0 V_MEMRAM1 _c_PCM_02_PAG_buf V_MEMRAM2 PCM_02_PAG;
V_MEMRAM0 V_MEMRAM1 _c_PCM_04_PAG_buf V_MEMRAM2 PCM_04_PAG;
V_MEMRAM0 V_MEMRAM1 _c_PCM_CDR_01_PAG_buf V_MEMRAM2 PCM_CDR_01_PAG;
V_MEMRAM0 V_MEMRAM1 _c_RDK_02_PAG_buf V_MEMRAM2 RDK_02_PAG;
V_MEMRAM0 V_MEMRAM1 _c_Systeminfo_01_buf V_MEMRAM2 Systeminfo_01;
V_MEMRAM0 V_MEMRAM1 _c_VIN_01_buf V_MEMRAM2 VIN_01;
V_MEMRAM0 V_MEMRAM1 _c_VIN_01_m0_buf V_MEMRAM2 VIN_01_m0;
V_MEMRAM0 V_MEMRAM1 _c_VIN_01_m1_buf V_MEMRAM2 VIN_01_m1;
V_MEMRAM0 V_MEMRAM1 _c_VIN_01_m2_buf V_MEMRAM2 VIN_01_m2;
V_MEMRAM0 V_MEMRAM1 _c_ADR_01_PAG_buf V_MEMRAM2 ADR_01_PAG;
V_MEMRAM0 V_MEMRAM1 _c_ADR_02_PAG_buf V_MEMRAM2 ADR_02_PAG;
V_MEMRAM0 V_MEMRAM1 _c_Klima_13_PAG_buf V_MEMRAM2 Klima_13_PAG;
V_MEMRAM0 V_MEMRAM1 _c_Miko_01_PAG_buf V_MEMRAM2 Miko_01_PAG;
V_MEMRAM0 V_MEMRAM1 _c_Motor_02_sek_buf V_MEMRAM2 Motor_02_sek;
V_MEMRAM0 V_MEMRAM1 _c_HVLM_07_PAG_buf V_MEMRAM2 HVLM_07_PAG;
V_MEMRAM0 V_MEMRAM1 _c_HVLM_07_PAG_m1_buf V_MEMRAM2 HVLM_07_PAG_m1;
V_MEMRAM0 V_MEMRAM1 _c_HVLM_07_PAG_m2_buf V_MEMRAM2 HVLM_07_PAG_m2;
V_MEMRAM0 V_MEMRAM1 _c_HVLM_07_PAG_m3_buf V_MEMRAM2 HVLM_07_PAG_m3;
V_MEMRAM0 V_MEMRAM1 _c_HVLM_07_PAG_m4_buf V_MEMRAM2 HVLM_07_PAG_m4;
V_MEMRAM0 V_MEMRAM1 _c_HVLM_07_PAG_m7_buf V_MEMRAM2 HVLM_07_PAG_m7;
V_MEMRAM0 V_MEMRAM1 _c_Kombi_19_PAG_buf V_MEMRAM2 Kombi_19_PAG;
V_MEMRAM0 V_MEMRAM1 _c_Motor_K_02_buf V_MEMRAM2 Motor_K_02;
/* RAM CATEGORY 2 END */





/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 88863978
      #error "The magic number of the generated file <F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\src\drv_par.c> is different. Please check time and date of generated files!"
  #endif
#else
  #error "The magic number is not defined in the generated file <F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\src\drv_par.c> "

#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

