/* -----------------------------------------------------------------------------
  Filename:    can_par.h
  Description: Toolversion: 03.20.21.01.10.02.79.00.00.00
               
               Serial Number: CBD1100279
               Customer Info: Dr. Ing. h. c. F. Porsche AG
                              CBD / Porsche 2007+
                              Texas Instruments TMS470 / TMS470 R1SF55
                              Texas Instruments 4.6.6 Compiler
               
               
               Generator Fwk   : GENy 
               Generator Module: DrvCan__base
               
               Configuration   : F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\cfg\Porsche_ADR.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470Cpu
                       Compiler:     TexasInstruments
                       Derivates:    TMS470R1
               
               Channel "Channel0":
                       Databasefile: F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\cfg\CAN_Matrix_Dashboard_2_11_0_X2_Release.dbc
                       Bussystem:    CAN
                       Manufacturer: Porsche AG
                       Node:         ADR_PAG_X2

  Generated by , 2012-02-15  08:51:07
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2010 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__CAN_PAR_H__)
#define __CAN_PAR_H__

#include "can_cfg.h"
#include "v_inc.h"
#include "drv_par.h"

/* -----------------------------------------------------------------------------
    &&&~ Extern declarations of callback functions
 ----------------------------------------------------------------------------- */

#if defined(C_MULTIPLE_RECEIVE_CHANNEL) || defined(C_SINGLE_RECEIVE_CHANNEL)
/* CODE CATEGORY 1 START */
extern vuint8 PreTransmitFunctionADR_02_PAG(CanTxInfoStruct ctis);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 PreTransmitFunctionADR_01_PAG(CanTxInfoStruct ctis);
/* CODE CATEGORY 1 END */

#else
/* CODE CATEGORY 1 START */
extern vuint8 PreTransmitFunctionADR_02_PAG(CanChipDataPtr txObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 PreTransmitFunctionADR_01_PAG(CanChipDataPtr txObject);
/* CODE CATEGORY 1 END */

#endif

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgKombi_11_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgKombi_02PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgVIN_01PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgDiagnose_01PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgLAD_02PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgRDK_02_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgKlima_03PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgGateway_03PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgKlima_02PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgBEM_02PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgBCM1_02PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgKombi_19_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgGW_Mmi_07_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgGW_Mmi_06_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMFL_Tasten_Kon_01PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgHVLM_05PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgSysteminfo_01PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgHVLM_07_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgKombi_EV_01_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgKombi_14_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgLift_01PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 ApplCclNpmPrecopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 CanRxNPM_01_PAGPrecopyFct(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */
/* CODE CATEGORY 1 START */
extern vuint8 IlMsgNPM_01_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgGW_Mmi_10_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMotor_06PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgGateway_01PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgKlemmen_Status_01PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMotor_15_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMotor_K_02PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgKombi_17_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgKombi_16_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgGW_Mmi_01_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgGW_Mmi_05_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgBCM2_03_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgKlima_13_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgGW_Mmi_04_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgKombi_10_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgKombi_13_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgESP_10PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgGetriebe_03PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgESP_02PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgESP_01PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMiko_01_PAGPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMotor_02_sekPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 TpPrecopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 TpFuncPrecopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */


/* -----------------------------------------------------------------------------
    &&&~ Extern declarations of confirmation functions
 ----------------------------------------------------------------------------- */

/* CODE CATEGORY 1 START */
extern void TpDrvConfirmation(CanTransmitHandle txObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void NmhCanMsgConfirmation(CanTransmitHandle txObject);
/* CODE CATEGORY 1 END */



/* -----------------------------------------------------------------------------
    &&&~ Extern declarations of indication functions
 ----------------------------------------------------------------------------- */

/* CODE CATEGORY 1 START */
extern void Kombi_11_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Kombi_02_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void VIN_01_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Diagnose_01_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void CanRxDiagnose_01IndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */
/* CODE CATEGORY 1 START */
extern void IlMsgDiagnose_01Indication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void LAD_02_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void RDK_02_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Klima_03_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Gateway_03_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxGateway_03IndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgGateway_03Indication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Klima_02_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void BEM_02_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void BCM1_02_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Kombi_19_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void GW_Mmi_07_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxGW_Mmi_07_PAGIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgGW_Mmi_07_PAGIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void GW_Mmi_06_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxGW_Mmi_06_PAGIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgGW_Mmi_06_PAGIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void MFL_Tasten_Kon_01_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void HVLM_05_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Systeminfo_01_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxSysteminfo_01IndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgSysteminfo_01Indication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void HVLM_07_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxHVLM_07_PAGIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgHVLM_07_PAGIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Kombi_EV_01_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Kombi_14_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Lift_01_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void NPM_01_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void GW_Mmi_10_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxGW_Mmi_10_PAGIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgGW_Mmi_10_PAGIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Motor_06_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Gateway_01_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxGateway_01IndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgGateway_01Indication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Klemmen_Status_01_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Motor_15_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Motor_K_02_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Kombi_17_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Kombi_16_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void GW_Mmi_01_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxGW_Mmi_01_PAGIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgGW_Mmi_01_PAGIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void GW_Mmi_05_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxGW_Mmi_05_PAGIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgGW_Mmi_05_PAGIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void BCM2_03_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Klima_13_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void GW_Mmi_04_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

extern void CanRxGW_Mmi_04_PAGIndicationFct(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 START */
extern void IlMsgGW_Mmi_04_PAGIndication(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Kombi_10_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Kombi_13_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void ESP_10_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Getriebe_03_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void ESP_02_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void ESP_01_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Miko_01_PAG_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void Motor_02_sek_RxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */





/* -----------------------------------------------------------------------------
    &&&~ Handles of send objects
 ----------------------------------------------------------------------------- */

#define CanTxISO_Info_El_Resp                0
#define CanTxNMH_CDR_PCM                     1
#define CanTxPCM_CDR_01_PAG                  2
#define CanTxMem_Kombi_01_PAG                3
#define CanTxKombi_09_PAG                    4
#define CanTxEinheiten_01                    5
#define CanTxKombi_18_PAG                    6
#define CanTxPCM_04_PAG                      7
#define CanTxPCM_02_PAG                      8
#define CanTxADR_02_PAG                      9
#define CanTxADR_01_PAG                      10


/* -----------------------------------------------------------------------------
    &&&~ Access to confirmation flags
 ----------------------------------------------------------------------------- */

#define PCM_CDR_01_PAG_conf_b                (CanConfirmationFlags.w[0].b0)
#define CanWriteSyncPCM_CDR_01_PAG_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  PCM_CDR_01_PAG_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define Mem_Kombi_01_PAG_conf_b              (CanConfirmationFlags.w[0].b1)
#define CanWriteSyncMem_Kombi_01_PAG_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  Mem_Kombi_01_PAG_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define Kombi_09_PAG_conf_b                  (CanConfirmationFlags.w[0].b2)
#define CanWriteSyncKombi_09_PAG_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  Kombi_09_PAG_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define Einheiten_01_conf_b                  (CanConfirmationFlags.w[0].b3)
#define CanWriteSyncEinheiten_01_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  Einheiten_01_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define Kombi_18_PAG_conf_b                  (CanConfirmationFlags.w[0].b4)
#define CanWriteSyncKombi_18_PAG_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  Kombi_18_PAG_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define PCM_04_PAG_conf_b                    (CanConfirmationFlags.w[0].b5)
#define CanWriteSyncPCM_04_PAG_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  PCM_04_PAG_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define PCM_02_PAG_conf_b                    (CanConfirmationFlags.w[0].b6)
#define CanWriteSyncPCM_02_PAG_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  PCM_02_PAG_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define ADR_02_PAG_conf_b                    (CanConfirmationFlags.w[0].b7)
#define CanWriteSyncADR_02_PAG_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  ADR_02_PAG_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define ADR_01_PAG_conf_b                    (CanConfirmationFlags.w[0].b10)
#define CanWriteSyncADR_01_PAG_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  ADR_01_PAG_conf_b = (x); \
  CanEndFlagWriteSync(); \
}


/* -----------------------------------------------------------------------------
    &&&~ Handles of receive objects
 ----------------------------------------------------------------------------- */

#define CanRxKombi_11_PAG                    0
#define CanRxKombi_02                        1
#define CanRxVIN_01                          2
#define CanRxDiagnose_01                     3
#define CanRxLAD_02                          4
#define CanRxRDK_02_PAG                      5
#define CanRxKlima_03                        6
#define CanRxGateway_03                      7
#define CanRxKlima_02                        8
#define CanRxBEM_02                          9
#define CanRxBCM1_02                         10
#define CanRxKombi_19_PAG                    11
#define CanRxGW_Mmi_07_PAG                   12
#define CanRxGW_Mmi_06_PAG                   13
#define CanRxMFL_Tasten_Kon_01               14
#define CanRxHVLM_05                         15
#define CanRxSysteminfo_01                   16
#define CanRxHVLM_07_PAG                     17
#define CanRxKombi_EV_01_PAG                 18
#define CanRxKombi_14_PAG                    19
#define CanRxLift_01                         20
#define CanRxNPM_01_PAG                      21
#define CanRxGW_Mmi_10_PAG                   22
#define CanRxMotor_06                        23
#define CanRxGateway_01                      24
#define CanRxKlemmen_Status_01               25
#define CanRxMotor_15_PAG                    26
#define CanRxMotor_K_02                      27
#define CanRxKombi_17_PAG                    28
#define CanRxKombi_16_PAG                    29
#define CanRxGW_Mmi_01_PAG                   30
#define CanRxGW_Mmi_05_PAG                   31
#define CanRxBCM2_03_PAG                     32
#define CanRxKlima_13_PAG                    33
#define CanRxGW_Mmi_04_PAG                   34
#define CanRxKombi_10_PAG                    35
#define CanRxKombi_13_PAG                    36
#define CanRxESP_10                          37
#define CanRxGetriebe_03                     38
#define CanRxESP_02                          39
#define CanRxESP_01                          40
#define CanRxMiko_01_PAG                     41
#define CanRxMotor_02_sek                    42
#define CanRxISO_Info_El_Req                 43
#define CanRxISO_Funktionaler_Req_All        44


/* -----------------------------------------------------------------------------
    &&&~ Access to data bytes of Rx messages
 ----------------------------------------------------------------------------- */

/* ID: 0x000006bd, Handle: 0, Kombi_11_PAG [FC] */
#define c1_Kombi_11_PAG_c                    (Kombi_11_PAG._c[0])
#define c2_Kombi_11_PAG_c                    (Kombi_11_PAG._c[1])
#define c3_Kombi_11_PAG_c                    (Kombi_11_PAG._c[2])
#define c4_Kombi_11_PAG_c                    (Kombi_11_PAG._c[3])
#define c5_Kombi_11_PAG_c                    (Kombi_11_PAG._c[4])
#define c6_Kombi_11_PAG_c                    (Kombi_11_PAG._c[5])

/* ID: 0x000006b7, Handle: 1, Kombi_02 [FC] */
#define c1_Kombi_02_c                        (Kombi_02._c[0])
#define c2_Kombi_02_c                        (Kombi_02._c[1])
#define c3_Kombi_02_c                        (Kombi_02._c[2])
#define c4_Kombi_02_c                        (Kombi_02._c[3])
#define c5_Kombi_02_c                        (Kombi_02._c[4])
#define c6_Kombi_02_c                        (Kombi_02._c[5])
#define c7_Kombi_02_c                        (Kombi_02._c[6])
#define c8_Kombi_02_c                        (Kombi_02._c[7])

/* ID: 0x000006b4, Handle: 2, VIN_01 [BC] */
#define c1_VIN_01_c                          (VIN_01._c[0])
#define c2_VIN_01_c                          (VIN_01._c[1])
#define c3_VIN_01_c                          (VIN_01._c[2])
#define c4_VIN_01_c                          (VIN_01._c[3])
#define c5_VIN_01_c                          (VIN_01._c[4])
#define c6_VIN_01_c                          (VIN_01._c[5])
#define c7_VIN_01_c                          (VIN_01._c[6])
#define c8_VIN_01_c                          (VIN_01._c[7])

/* ID: 0x000006b2, Handle: 3, Diagnose_01 [FC] */
#define c1_Diagnose_01_c                     (Diagnose_01._c[0])
#define c2_Diagnose_01_c                     (Diagnose_01._c[1])
#define c3_Diagnose_01_c                     (Diagnose_01._c[2])
#define c4_Diagnose_01_c                     (Diagnose_01._c[3])
#define c5_Diagnose_01_c                     (Diagnose_01._c[4])
#define c6_Diagnose_01_c                     (Diagnose_01._c[5])
#define c7_Diagnose_01_c                     (Diagnose_01._c[6])
#define c8_Diagnose_01_c                     (Diagnose_01._c[7])

/* ID: 0x0000067e, Handle: 4, LAD_02 [BC] */
#define c1_LAD_02_c                          (LAD_02._c[0])
#define c2_LAD_02_c                          (LAD_02._c[1])
#define c3_LAD_02_c                          (LAD_02._c[2])
#define c4_LAD_02_c                          (LAD_02._c[3])
#define c5_LAD_02_c                          (LAD_02._c[4])
#define c6_LAD_02_c                          (LAD_02._c[5])
#define c7_LAD_02_c                          (LAD_02._c[6])
#define c8_LAD_02_c                          (LAD_02._c[7])

/* ID: 0x00000674, Handle: 5, RDK_02_PAG [BC] */
#define c1_RDK_02_PAG_c                      (RDK_02_PAG._c[0])
#define c2_RDK_02_PAG_c                      (RDK_02_PAG._c[1])

/* ID: 0x0000066e, Handle: 6, Klima_03 [FC] */
#define c1_Klima_03_c                        (Klima_03._c[0])
#define c2_Klima_03_c                        (Klima_03._c[1])
#define c3_Klima_03_c                        (Klima_03._c[2])
#define c4_Klima_03_c                        (Klima_03._c[3])
#define c5_Klima_03_c                        (Klima_03._c[4])
#define c6_Klima_03_c                        (Klima_03._c[5])

/* ID: 0x0000066b, Handle: 7, Gateway_03 [FC] */
#define c1_Gateway_03_c                      (Gateway_03._c[0])
#define c2_Gateway_03_c                      (Gateway_03._c[1])
#define c3_Gateway_03_c                      (Gateway_03._c[2])
#define c4_Gateway_03_c                      (Gateway_03._c[3])
#define c5_Gateway_03_c                      (Gateway_03._c[4])
#define c6_Gateway_03_c                      (Gateway_03._c[5])
#define c7_Gateway_03_c                      (Gateway_03._c[6])

/* ID: 0x00000664, Handle: 8, Klima_02 [FC] */
#define c1_Klima_02_c                        (Klima_02._c[0])
#define c2_Klima_02_c                        (Klima_02._c[1])
#define c3_Klima_02_c                        (Klima_02._c[2])
#define c4_Klima_02_c                        (Klima_02._c[3])
#define c5_Klima_02_c                        (Klima_02._c[4])

/* ID: 0x00000663, Handle: 9, BEM_02 [FC] */
#define c1_BEM_02_c                          (BEM_02._c[0])

/* ID: 0x00000662, Handle: 10, BCM1_02 [FC] */
#define c1_BCM1_02_c                         (BCM1_02._c[0])
#define c2_BCM1_02_c                         (BCM1_02._c[1])
#define c3_BCM1_02_c                         (BCM1_02._c[2])

/* ID: 0x000005ff, Handle: 11, Kombi_19_PAG [BC] */
#define c1_Kombi_19_PAG_c                    (Kombi_19_PAG._c[0])
#define c2_Kombi_19_PAG_c                    (Kombi_19_PAG._c[1])
#define c3_Kombi_19_PAG_c                    (Kombi_19_PAG._c[2])

/* ID: 0x000005ec, Handle: 12, GW_Mmi_07_PAG [FC] */
#define c1_GW_Mmi_07_PAG_c                   (GW_Mmi_07_PAG._c[0])
#define c2_GW_Mmi_07_PAG_c                   (GW_Mmi_07_PAG._c[1])
#define c3_GW_Mmi_07_PAG_c                   (GW_Mmi_07_PAG._c[2])
#define c4_GW_Mmi_07_PAG_c                   (GW_Mmi_07_PAG._c[3])
#define c5_GW_Mmi_07_PAG_c                   (GW_Mmi_07_PAG._c[4])
#define c6_GW_Mmi_07_PAG_c                   (GW_Mmi_07_PAG._c[5])
#define c7_GW_Mmi_07_PAG_c                   (GW_Mmi_07_PAG._c[6])
#define c8_GW_Mmi_07_PAG_c                   (GW_Mmi_07_PAG._c[7])

/* ID: 0x000005eb, Handle: 13, GW_Mmi_06_PAG [FC] */
#define c1_GW_Mmi_06_PAG_c                   (GW_Mmi_06_PAG._c[0])
#define c2_GW_Mmi_06_PAG_c                   (GW_Mmi_06_PAG._c[1])
#define c3_GW_Mmi_06_PAG_c                   (GW_Mmi_06_PAG._c[2])
#define c4_GW_Mmi_06_PAG_c                   (GW_Mmi_06_PAG._c[3])
#define c5_GW_Mmi_06_PAG_c                   (GW_Mmi_06_PAG._c[4])
#define c6_GW_Mmi_06_PAG_c                   (GW_Mmi_06_PAG._c[5])
#define c7_GW_Mmi_06_PAG_c                   (GW_Mmi_06_PAG._c[6])
#define c8_GW_Mmi_06_PAG_c                   (GW_Mmi_06_PAG._c[7])

/* ID: 0x000005bf, Handle: 14, MFL_Tasten_Kon_01 [BC] */
#define c1_MFL_Tasten_Kon_01_c               (MFL_Tasten_Kon_01._c[0])
#define c2_MFL_Tasten_Kon_01_c               (MFL_Tasten_Kon_01._c[1])
#define c3_MFL_Tasten_Kon_01_c               (MFL_Tasten_Kon_01._c[2])
#define c4_MFL_Tasten_Kon_01_c               (MFL_Tasten_Kon_01._c[3])

/* ID: 0x00000594, Handle: 15, HVLM_05 [FC] */
#define c1_HVLM_05_c                         (HVLM_05._c[0])
#define c2_HVLM_05_c                         (HVLM_05._c[1])
#define c3_HVLM_05_c                         (HVLM_05._c[2])
#define c4_HVLM_05_c                         (HVLM_05._c[3])
#define c5_HVLM_05_c                         (HVLM_05._c[4])
#define c6_HVLM_05_c                         (HVLM_05._c[5])
#define c7_HVLM_05_c                         (HVLM_05._c[6])

/* ID: 0x00000585, Handle: 16, Systeminfo_01 [BC] */
#define c1_Systeminfo_01_c                   (Systeminfo_01._c[0])
#define c2_Systeminfo_01_c                   (Systeminfo_01._c[1])

/* ID: 0x00000575, Handle: 17, HVLM_07_PAG [BC] */
#define c1_HVLM_07_PAG_c                     (HVLM_07_PAG._c[0])
#define c2_HVLM_07_PAG_c                     (HVLM_07_PAG._c[1])
#define c3_HVLM_07_PAG_c                     (HVLM_07_PAG._c[2])
#define c4_HVLM_07_PAG_c                     (HVLM_07_PAG._c[3])
#define c5_HVLM_07_PAG_c                     (HVLM_07_PAG._c[4])

/* ID: 0x0000053f, Handle: 18, Kombi_EV_01_PAG [BC] */
#define c1_Kombi_EV_01_PAG_c                 (Kombi_EV_01_PAG._c[0])
#define c2_Kombi_EV_01_PAG_c                 (Kombi_EV_01_PAG._c[1])
#define c3_Kombi_EV_01_PAG_c                 (Kombi_EV_01_PAG._c[2])
#define c4_Kombi_EV_01_PAG_c                 (Kombi_EV_01_PAG._c[3])
#define c5_Kombi_EV_01_PAG_c                 (Kombi_EV_01_PAG._c[4])
#define c6_Kombi_EV_01_PAG_c                 (Kombi_EV_01_PAG._c[5])
#define c7_Kombi_EV_01_PAG_c                 (Kombi_EV_01_PAG._c[6])
#define c8_Kombi_EV_01_PAG_c                 (Kombi_EV_01_PAG._c[7])

/* ID: 0x00000533, Handle: 19, Kombi_14_PAG [FC] */
#define c1_Kombi_14_PAG_c                    (Kombi_14_PAG._c[0])
#define c2_Kombi_14_PAG_c                    (Kombi_14_PAG._c[1])
#define c3_Kombi_14_PAG_c                    (Kombi_14_PAG._c[2])
#define c4_Kombi_14_PAG_c                    (Kombi_14_PAG._c[3])
#define c5_Kombi_14_PAG_c                    (Kombi_14_PAG._c[4])
#define c6_Kombi_14_PAG_c                    (Kombi_14_PAG._c[5])
#define c7_Kombi_14_PAG_c                    (Kombi_14_PAG._c[6])
#define c8_Kombi_14_PAG_c                    (Kombi_14_PAG._c[7])

/* ID: 0x00000529, Handle: 20, Lift_01 [BC] */
#define c1_Lift_01_c                         (Lift_01._c[0])
#define c2_Lift_01_c                         (Lift_01._c[1])

/* ID: 0x00000484, Handle: 21, NPM_01_PAG [BC] */
#define c1_NPM_01_PAG_c                      (NPM_01_PAG._c[0])
#define c2_NPM_01_PAG_c                      (NPM_01_PAG._c[1])
#define c3_NPM_01_PAG_c                      (NPM_01_PAG._c[2])
#define c4_NPM_01_PAG_c                      (NPM_01_PAG._c[3])
#define c5_NPM_01_PAG_c                      (NPM_01_PAG._c[4])
#define c6_NPM_01_PAG_c                      (NPM_01_PAG._c[5])
#define c7_NPM_01_PAG_c                      (NPM_01_PAG._c[6])
#define c8_NPM_01_PAG_c                      (NPM_01_PAG._c[7])

/* ID: 0x00000444, Handle: 22, GW_Mmi_10_PAG [FC] */
#define c1_GW_Mmi_10_PAG_c                   (GW_Mmi_10_PAG._c[0])
#define c2_GW_Mmi_10_PAG_c                   (GW_Mmi_10_PAG._c[1])
#define c3_GW_Mmi_10_PAG_c                   (GW_Mmi_10_PAG._c[2])
#define c4_GW_Mmi_10_PAG_c                   (GW_Mmi_10_PAG._c[3])
#define c5_GW_Mmi_10_PAG_c                   (GW_Mmi_10_PAG._c[4])
#define c6_GW_Mmi_10_PAG_c                   (GW_Mmi_10_PAG._c[5])
#define c7_GW_Mmi_10_PAG_c                   (GW_Mmi_10_PAG._c[6])
#define c8_GW_Mmi_10_PAG_c                   (GW_Mmi_10_PAG._c[7])

/* ID: 0x00000440, Handle: 23, Motor_06 [BC] */
#define c1_Motor_06_c                        (Motor_06._c[0])
#define c2_Motor_06_c                        (Motor_06._c[1])
#define c3_Motor_06_c                        (Motor_06._c[2])
#define c4_Motor_06_c                        (Motor_06._c[3])

/* ID: 0x000003c3, Handle: 24, Gateway_01 [FC] */
#define c1_Gateway_01_c                      (Gateway_01._c[0])
#define c2_Gateway_01_c                      (Gateway_01._c[1])
#define c3_Gateway_01_c                      (Gateway_01._c[2])
#define c4_Gateway_01_c                      (Gateway_01._c[3])
#define c5_Gateway_01_c                      (Gateway_01._c[4])
#define c6_Gateway_01_c                      (Gateway_01._c[5])
#define c7_Gateway_01_c                      (Gateway_01._c[6])

/* ID: 0x000003c0, Handle: 25, Klemmen_Status_01 [FC] */
#define c1_Klemmen_Status_01_c               (Klemmen_Status_01._c[0])
#define c2_Klemmen_Status_01_c               (Klemmen_Status_01._c[1])
#define c3_Klemmen_Status_01_c               (Klemmen_Status_01._c[2])

/* ID: 0x000003a5, Handle: 26, Motor_15_PAG [BC] */
#define c1_Motor_15_PAG_c                    (Motor_15_PAG._c[0])
#define c2_Motor_15_PAG_c                    (Motor_15_PAG._c[1])

/* ID: 0x000003a3, Handle: 27, Motor_K_02 [BC] */
#define c1_Motor_K_02_c                      (Motor_K_02._c[0])
#define c2_Motor_K_02_c                      (Motor_K_02._c[1])
#define c3_Motor_K_02_c                      (Motor_K_02._c[2])
#define c4_Motor_K_02_c                      (Motor_K_02._c[3])
#define c5_Motor_K_02_c                      (Motor_K_02._c[4])
#define c6_Motor_K_02_c                      (Motor_K_02._c[5])

/* ID: 0x0000039b, Handle: 28, Kombi_17_PAG [FC] */
#define c1_Kombi_17_PAG_c                    (Kombi_17_PAG._c[0])
#define c2_Kombi_17_PAG_c                    (Kombi_17_PAG._c[1])
#define c3_Kombi_17_PAG_c                    (Kombi_17_PAG._c[2])
#define c4_Kombi_17_PAG_c                    (Kombi_17_PAG._c[3])
#define c5_Kombi_17_PAG_c                    (Kombi_17_PAG._c[4])
#define c6_Kombi_17_PAG_c                    (Kombi_17_PAG._c[5])
#define c7_Kombi_17_PAG_c                    (Kombi_17_PAG._c[6])
#define c8_Kombi_17_PAG_c                    (Kombi_17_PAG._c[7])

/* ID: 0x0000039a, Handle: 29, Kombi_16_PAG [FC] */
#define c1_Kombi_16_PAG_c                    (Kombi_16_PAG._c[0])
#define c2_Kombi_16_PAG_c                    (Kombi_16_PAG._c[1])
#define c3_Kombi_16_PAG_c                    (Kombi_16_PAG._c[2])
#define c4_Kombi_16_PAG_c                    (Kombi_16_PAG._c[3])
#define c5_Kombi_16_PAG_c                    (Kombi_16_PAG._c[4])
#define c6_Kombi_16_PAG_c                    (Kombi_16_PAG._c[5])
#define c7_Kombi_16_PAG_c                    (Kombi_16_PAG._c[6])
#define c8_Kombi_16_PAG_c                    (Kombi_16_PAG._c[7])

/* ID: 0x0000038d, Handle: 30, GW_Mmi_01_PAG [FC] */
#define c1_GW_Mmi_01_PAG_c                   (GW_Mmi_01_PAG._c[0])
#define c2_GW_Mmi_01_PAG_c                   (GW_Mmi_01_PAG._c[1])
#define c3_GW_Mmi_01_PAG_c                   (GW_Mmi_01_PAG._c[2])
#define c4_GW_Mmi_01_PAG_c                   (GW_Mmi_01_PAG._c[3])
#define c5_GW_Mmi_01_PAG_c                   (GW_Mmi_01_PAG._c[4])
#define c6_GW_Mmi_01_PAG_c                   (GW_Mmi_01_PAG._c[5])
#define c7_GW_Mmi_01_PAG_c                   (GW_Mmi_01_PAG._c[6])
#define c8_GW_Mmi_01_PAG_c                   (GW_Mmi_01_PAG._c[7])

/* ID: 0x0000038c, Handle: 31, GW_Mmi_05_PAG [FC] */
#define c1_GW_Mmi_05_PAG_c                   (GW_Mmi_05_PAG._c[0])
#define c2_GW_Mmi_05_PAG_c                   (GW_Mmi_05_PAG._c[1])
#define c3_GW_Mmi_05_PAG_c                   (GW_Mmi_05_PAG._c[2])
#define c4_GW_Mmi_05_PAG_c                   (GW_Mmi_05_PAG._c[3])
#define c5_GW_Mmi_05_PAG_c                   (GW_Mmi_05_PAG._c[4])
#define c6_GW_Mmi_05_PAG_c                   (GW_Mmi_05_PAG._c[5])
#define c7_GW_Mmi_05_PAG_c                   (GW_Mmi_05_PAG._c[6])
#define c8_GW_Mmi_05_PAG_c                   (GW_Mmi_05_PAG._c[7])

/* ID: 0x00000384, Handle: 32, BCM2_03_PAG [FC] */
#define c1_BCM2_03_PAG_c                     (BCM2_03_PAG._c[0])
#define c2_BCM2_03_PAG_c                     (BCM2_03_PAG._c[1])
#define c3_BCM2_03_PAG_c                     (BCM2_03_PAG._c[2])
#define c4_BCM2_03_PAG_c                     (BCM2_03_PAG._c[3])

/* ID: 0x0000037f, Handle: 33, Klima_13_PAG [BC] */
#define c1_Klima_13_PAG_c                    (Klima_13_PAG._c[0])
#define c2_Klima_13_PAG_c                    (Klima_13_PAG._c[1])
#define c3_Klima_13_PAG_c                    (Klima_13_PAG._c[2])

/* ID: 0x0000031c, Handle: 34, GW_Mmi_04_PAG [FC] */
#define c1_GW_Mmi_04_PAG_c                   (GW_Mmi_04_PAG._c[0])
#define c2_GW_Mmi_04_PAG_c                   (GW_Mmi_04_PAG._c[1])
#define c3_GW_Mmi_04_PAG_c                   (GW_Mmi_04_PAG._c[2])
#define c4_GW_Mmi_04_PAG_c                   (GW_Mmi_04_PAG._c[3])
#define c5_GW_Mmi_04_PAG_c                   (GW_Mmi_04_PAG._c[4])
#define c6_GW_Mmi_04_PAG_c                   (GW_Mmi_04_PAG._c[5])
#define c7_GW_Mmi_04_PAG_c                   (GW_Mmi_04_PAG._c[6])
#define c8_GW_Mmi_04_PAG_c                   (GW_Mmi_04_PAG._c[7])

/* ID: 0x0000031a, Handle: 35, Kombi_10_PAG [FC] */
#define c1_Kombi_10_PAG_c                    (Kombi_10_PAG._c[0])
#define c2_Kombi_10_PAG_c                    (Kombi_10_PAG._c[1])
#define c3_Kombi_10_PAG_c                    (Kombi_10_PAG._c[2])
#define c4_Kombi_10_PAG_c                    (Kombi_10_PAG._c[3])
#define c5_Kombi_10_PAG_c                    (Kombi_10_PAG._c[4])

/* ID: 0x0000011a, Handle: 36, Kombi_13_PAG [FC] */
#define c1_Kombi_13_PAG_c                    (Kombi_13_PAG._c[0])
#define c2_Kombi_13_PAG_c                    (Kombi_13_PAG._c[1])
#define c3_Kombi_13_PAG_c                    (Kombi_13_PAG._c[2])
#define c4_Kombi_13_PAG_c                    (Kombi_13_PAG._c[3])
#define c5_Kombi_13_PAG_c                    (Kombi_13_PAG._c[4])
#define c6_Kombi_13_PAG_c                    (Kombi_13_PAG._c[5])
#define c7_Kombi_13_PAG_c                    (Kombi_13_PAG._c[6])

/* ID: 0x00000116, Handle: 37, ESP_10 [FC] */
#define c1_ESP_10_c                          (ESP_10._c[0])
#define c2_ESP_10_c                          (ESP_10._c[1])
#define c3_ESP_10_c                          (ESP_10._c[2])
#define c4_ESP_10_c                          (ESP_10._c[3])
#define c5_ESP_10_c                          (ESP_10._c[4])
#define c6_ESP_10_c                          (ESP_10._c[5])
#define c7_ESP_10_c                          (ESP_10._c[6])
#define c8_ESP_10_c                          (ESP_10._c[7])

/* ID: 0x00000102, Handle: 38, Getriebe_03 [FC] */
#define c1_Getriebe_03_c                     (Getriebe_03._c[0])
#define c2_Getriebe_03_c                     (Getriebe_03._c[1])
#define c3_Getriebe_03_c                     (Getriebe_03._c[2])
#define c4_Getriebe_03_c                     (Getriebe_03._c[3])

/* ID: 0x00000101, Handle: 39, ESP_02 [FC] */
#define c1_ESP_02_c                          (ESP_02._c[0])
#define c2_ESP_02_c                          (ESP_02._c[1])
#define c3_ESP_02_c                          (ESP_02._c[2])
#define c4_ESP_02_c                          (ESP_02._c[3])
#define c5_ESP_02_c                          (ESP_02._c[4])

/* ID: 0x00000100, Handle: 40, ESP_01 [FC] */
#define c1_ESP_01_c                          (ESP_01._c[0])
#define c2_ESP_01_c                          (ESP_01._c[1])
#define c3_ESP_01_c                          (ESP_01._c[2])
#define c4_ESP_01_c                          (ESP_01._c[3])
#define c5_ESP_01_c                          (ESP_01._c[4])
#define c6_ESP_01_c                          (ESP_01._c[5])
#define c7_ESP_01_c                          (ESP_01._c[6])

/* ID: 0x000000c1, Handle: 41, Miko_01_PAG [BC] */
#define c1_Miko_01_PAG_c                     (Miko_01_PAG._c[0])
#define c2_Miko_01_PAG_c                     (Miko_01_PAG._c[1])
#define c3_Miko_01_PAG_c                     (Miko_01_PAG._c[2])
#define c4_Miko_01_PAG_c                     (Miko_01_PAG._c[3])
#define c5_Miko_01_PAG_c                     (Miko_01_PAG._c[4])
#define c6_Miko_01_PAG_c                     (Miko_01_PAG._c[5])

/* ID: 0x0000007e, Handle: 42, Motor_02_sek [BC] */
#define c1_Motor_02_sek_c                    (Motor_02_sek._c[0])
#define c2_Motor_02_sek_c                    (Motor_02_sek._c[1])
#define c3_Motor_02_sek_c                    (Motor_02_sek._c[2])



/* -----------------------------------------------------------------------------
    &&&~ Access to data bytes of Tx messages
 ----------------------------------------------------------------------------- */

/* ID: 0x000007dd, Handle: 0, ISO_Info_El_Resp [BC] */
#define c1_ISO_Info_El_Resp_c                (ISO_Info_El_Resp._c[0])
#define c2_ISO_Info_El_Resp_c                (ISO_Info_El_Resp._c[1])
#define c3_ISO_Info_El_Resp_c                (ISO_Info_El_Resp._c[2])
#define c4_ISO_Info_El_Resp_c                (ISO_Info_El_Resp._c[3])
#define c5_ISO_Info_El_Resp_c                (ISO_Info_El_Resp._c[4])
#define c6_ISO_Info_El_Resp_c                (ISO_Info_El_Resp._c[5])
#define c7_ISO_Info_El_Resp_c                (ISO_Info_El_Resp._c[6])
#define c8_ISO_Info_El_Resp_c                (ISO_Info_El_Resp._c[7])

/* ID: 0x000006d3, Handle: 1, NMH_CDR_PCM [BC] */
#define c1_NMH_CDR_PCM_c                     (NMH_CDR_PCM._c[0])
#define c2_NMH_CDR_PCM_c                     (NMH_CDR_PCM._c[1])
#define c3_NMH_CDR_PCM_c                     (NMH_CDR_PCM._c[2])
#define c4_NMH_CDR_PCM_c                     (NMH_CDR_PCM._c[3])
#define c5_NMH_CDR_PCM_c                     (NMH_CDR_PCM._c[4])
#define c6_NMH_CDR_PCM_c                     (NMH_CDR_PCM._c[5])
#define c7_NMH_CDR_PCM_c                     (NMH_CDR_PCM._c[6])

/* ID: 0x000006ab, Handle: 2, PCM_CDR_01_PAG [BC] */
#define c1_PCM_CDR_01_PAG_c                  (PCM_CDR_01_PAG._c[0])
#define c2_PCM_CDR_01_PAG_c                  (PCM_CDR_01_PAG._c[1])
#define c3_PCM_CDR_01_PAG_c                  (PCM_CDR_01_PAG._c[2])
#define c4_PCM_CDR_01_PAG_c                  (PCM_CDR_01_PAG._c[3])
#define c5_PCM_CDR_01_PAG_c                  (PCM_CDR_01_PAG._c[4])
#define c6_PCM_CDR_01_PAG_c                  (PCM_CDR_01_PAG._c[5])
#define c7_PCM_CDR_01_PAG_c                  (PCM_CDR_01_PAG._c[6])
#define c8_PCM_CDR_01_PAG_c                  (PCM_CDR_01_PAG._c[7])

/* ID: 0x000006a8, Handle: 3, Mem_Kombi_01_PAG [BC] */
#define c1_Mem_Kombi_01_PAG_c                (Mem_Kombi_01_PAG._c[0])
#define c2_Mem_Kombi_01_PAG_c                (Mem_Kombi_01_PAG._c[1])
#define c3_Mem_Kombi_01_PAG_c                (Mem_Kombi_01_PAG._c[2])
#define c4_Mem_Kombi_01_PAG_c                (Mem_Kombi_01_PAG._c[3])
#define c5_Mem_Kombi_01_PAG_c                (Mem_Kombi_01_PAG._c[4])
#define c6_Mem_Kombi_01_PAG_c                (Mem_Kombi_01_PAG._c[5])
#define c7_Mem_Kombi_01_PAG_c                (Mem_Kombi_01_PAG._c[6])
#define c8_Mem_Kombi_01_PAG_c                (Mem_Kombi_01_PAG._c[7])

/* ID: 0x00000666, Handle: 4, Kombi_09_PAG [BC] */
#define c1_Kombi_09_PAG_c                    (Kombi_09_PAG._c[0])
#define c2_Kombi_09_PAG_c                    (Kombi_09_PAG._c[1])
#define c3_Kombi_09_PAG_c                    (Kombi_09_PAG._c[2])
#define c4_Kombi_09_PAG_c                    (Kombi_09_PAG._c[3])
#define c5_Kombi_09_PAG_c                    (Kombi_09_PAG._c[4])
#define c6_Kombi_09_PAG_c                    (Kombi_09_PAG._c[5])
#define c7_Kombi_09_PAG_c                    (Kombi_09_PAG._c[6])
#define c8_Kombi_09_PAG_c                    (Kombi_09_PAG._c[7])

/* ID: 0x00000643, Handle: 5, Einheiten_01 [BC] */
#define c1_Einheiten_01_c                    (Einheiten_01._c[0])
#define c2_Einheiten_01_c                    (Einheiten_01._c[1])
#define c3_Einheiten_01_c                    (Einheiten_01._c[2])

/* ID: 0x000005fe, Handle: 6, Kombi_18_PAG [BC] */
#define c1_Kombi_18_PAG_c                    (Kombi_18_PAG._c[0])
#define c2_Kombi_18_PAG_c                    (Kombi_18_PAG._c[1])
#define c3_Kombi_18_PAG_c                    (Kombi_18_PAG._c[2])
#define c4_Kombi_18_PAG_c                    (Kombi_18_PAG._c[3])
#define c5_Kombi_18_PAG_c                    (Kombi_18_PAG._c[4])
#define c6_Kombi_18_PAG_c                    (Kombi_18_PAG._c[5])
#define c7_Kombi_18_PAG_c                    (Kombi_18_PAG._c[6])
#define c8_Kombi_18_PAG_c                    (Kombi_18_PAG._c[7])

/* ID: 0x000005fa, Handle: 7, PCM_04_PAG [BC] */
#define c1_PCM_04_PAG_c                      (PCM_04_PAG._c[0])
#define c2_PCM_04_PAG_c                      (PCM_04_PAG._c[1])
#define c3_PCM_04_PAG_c                      (PCM_04_PAG._c[2])
#define c4_PCM_04_PAG_c                      (PCM_04_PAG._c[3])
#define c5_PCM_04_PAG_c                      (PCM_04_PAG._c[4])
#define c6_PCM_04_PAG_c                      (PCM_04_PAG._c[5])
#define c7_PCM_04_PAG_c                      (PCM_04_PAG._c[6])
#define c8_PCM_04_PAG_c                      (PCM_04_PAG._c[7])

/* ID: 0x00000539, Handle: 8, PCM_02_PAG [BC] */
#define c1_PCM_02_PAG_c                      (PCM_02_PAG._c[0])
#define c2_PCM_02_PAG_c                      (PCM_02_PAG._c[1])
#define c3_PCM_02_PAG_c                      (PCM_02_PAG._c[2])
#define c4_PCM_02_PAG_c                      (PCM_02_PAG._c[3])
#define c5_PCM_02_PAG_c                      (PCM_02_PAG._c[4])
#define c6_PCM_02_PAG_c                      (PCM_02_PAG._c[5])
#define c7_PCM_02_PAG_c                      (PCM_02_PAG._c[6])
#define c8_PCM_02_PAG_c                      (PCM_02_PAG._c[7])

/* ID: 0x000000c2, Handle: 9, ADR_02_PAG [BC] */
#define c1_ADR_02_PAG_c                      (ADR_02_PAG._c[0])
#define c2_ADR_02_PAG_c                      (ADR_02_PAG._c[1])
#define c3_ADR_02_PAG_c                      (ADR_02_PAG._c[2])
#define c4_ADR_02_PAG_c                      (ADR_02_PAG._c[3])
#define c5_ADR_02_PAG_c                      (ADR_02_PAG._c[4])
#define c6_ADR_02_PAG_c                      (ADR_02_PAG._c[5])
#define c7_ADR_02_PAG_c                      (ADR_02_PAG._c[6])
#define c8_ADR_02_PAG_c                      (ADR_02_PAG._c[7])

/* ID: 0x000000c0, Handle: 10, ADR_01_PAG [BC] */
#define c1_ADR_01_PAG_c                      (ADR_01_PAG._c[0])
#define c2_ADR_01_PAG_c                      (ADR_01_PAG._c[1])
#define c3_ADR_01_PAG_c                      (ADR_01_PAG._c[2])
#define c4_ADR_01_PAG_c                      (ADR_01_PAG._c[3])
#define c5_ADR_01_PAG_c                      (ADR_01_PAG._c[4])
#define c6_ADR_01_PAG_c                      (ADR_01_PAG._c[5])
#define c7_ADR_01_PAG_c                      (ADR_01_PAG._c[6])
#define c8_ADR_01_PAG_c                      (ADR_01_PAG._c[7])



/* -----------------------------------------------------------------------------
    &&&~ RDS Access
 ----------------------------------------------------------------------------- */

typedef struct _c_Kombi_EV_01_PAG_RDS_msgTypeTag
{
  vbittype KBI_Trip_E_Verbr_fortl_0 : 8;
  vbittype KBI_Trip_E_Verbr_seit_0 : 2;
  vbittype KBI_Trip_E_Verbr_fortl_1 : 6;
  vbittype KBI_Trip_E_Verbr_seit_1 : 8;
  vbittype KBI_Trip_E_Strecke_fortl_0 : 4;
  vbittype KBI_Trip_E_Verbr_seit_2 : 4;
  vbittype KBI_Trip_E_Strecke_fortl_1 : 8;
  vbittype KBI_Trip_E_Strecke_seit_0 : 3;
  vbittype KBI_Trip_E_Strecke_fortl_2 : 5;
  vbittype KBI_Trip_E_Strecke_seit_1 : 8;
  vbittype unused0 : 2;
  vbittype KBI_Trip_E_Strecke_seit_2 : 6;
} _c_Kombi_EV_01_PAG_RDS_msgType;

typedef struct _c_LAD_02_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype LAD_Fehlerzustand : 1;
  vbittype LAD_Warnzustand : 1;
  vbittype unused7 : 6;
} _c_LAD_02_RDS_msgType;

typedef struct _c_Lift_01_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 1;
  vbittype Lift_Status : 3;
  vbittype unused2 : 4;
} _c_Lift_01_RDS_msgType;

typedef struct _c_MFL_Tasten_Kon_01_RDS_msgTypeTag
{
  vbittype MFL_Tastencode_1 : 8;
  vbittype MFL_Tastencode_2 : 8;
  vbittype MFL_Eventcode_2 : 4;
  vbittype MFL_Eventcode_1 : 4;
  vbittype MFL_Variante : 4;
  vbittype MFL_Marke : 4;
} _c_MFL_Tasten_Kon_01_RDS_msgType;

typedef struct _c_Motor_06_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype MO_HYB_Text_4 : 1;
  vbittype unused3 : 7;
} _c_Motor_06_RDS_msgType;
typedef struct _c_Motor_06_RDS_m0_msgTypeTag
{
  vbittype cunused0 : 7;
  vbittype unused0 : 1;
} _c_Motor_06_RDS_m0_msgType;
typedef struct _c_Motor_06_RDS_m1_msgTypeTag
{
  vbittype cunused0 : 7;
  vbittype unused0 : 1;
} _c_Motor_06_RDS_m1_msgType;

typedef struct _c_Motor_15_PAG_RDS_msgTypeTag
{
  vbittype Enrgfluss_State : 8;
  vbittype Ladezustand : 8;
} _c_Motor_15_PAG_RDS_msgType;

typedef struct _c_NPM_01_PAG_RDS_msgTypeTag
{
  vbittype NPM_PreventWakeup : 4;
  vbittype NPM_ForceShutdown : 4;
  vbittype unused0 : 7;
  vbittype NPM_directAdressing : 1;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 6;
  vbittype NPM_FS_HU : 1;
  vbittype unused4 : 1;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype unused7 : 3;
  vbittype NPM_PrWu_HU : 1;
  vbittype unused8 : 4;
} _c_NPM_01_PAG_RDS_msgType;

typedef struct _c_RDK_02_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 5;
  vbittype RDK_angelernt : 1;
  vbittype unused2 : 2;
} _c_RDK_02_PAG_RDS_msgType;

typedef struct _c_Systeminfo_01_RDS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype SI_Fahrwerk_Sleep : 1;
  vbittype SI_CAN_Extended_Sleep : 1;
  vbittype unused1 : 1;
  vbittype SI_CAN_Antrieb_Sleep : 1;
  vbittype SI_CAN_Dashboard_Sleep : 1;
  vbittype SI_CAN_Komfort_Sleep : 1;
  vbittype unused2 : 1;
  vbittype unused3 : 4;
  vbittype SI_NWDF_gueltig : 1;
  vbittype SI_NWDF : 1;
  vbittype SI_T_Mode : 1;
  vbittype unused4 : 1;
} _c_Systeminfo_01_RDS_msgType;

typedef struct _c_VIN_01_RDS_msgTypeTag
{
  vbittype unused0 : 6;
  vbittype VIN_01_MUX : 2;
  vbittype cunused0 : 8;
  vbittype cunused2 : 8;
  vbittype cunused4 : 8;
  vbittype cunused6 : 8;
  vbittype cunused10 : 8;
  vbittype cunused11 : 8;
  vbittype cunused14 : 8;
} _c_VIN_01_RDS_msgType;
typedef struct _c_VIN_01_RDS_m0_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype cunused0 : 8;
  vbittype cunused1 : 8;
  vbittype cunused2 : 8;
  vbittype cunused3 : 8;
  vbittype VIN_1 : 8;
  vbittype VIN_2 : 8;
  vbittype VIN_3 : 8;
} _c_VIN_01_RDS_m0_msgType;
typedef struct _c_VIN_01_RDS_m1_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype VIN_4 : 8;
  vbittype VIN_5 : 8;
  vbittype VIN_6 : 8;
  vbittype VIN_7 : 8;
  vbittype VIN_8 : 8;
  vbittype VIN_9 : 8;
  vbittype VIN_10 : 8;
} _c_VIN_01_RDS_m1_msgType;
typedef struct _c_VIN_01_RDS_m2_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype VIN_11 : 8;
  vbittype VIN_12 : 8;
  vbittype VIN_13 : 8;
  vbittype VIN_14 : 8;
  vbittype VIN_15 : 8;
  vbittype VIN_16 : 8;
  vbittype VIN_17 : 8;
} _c_VIN_01_RDS_m2_msgType;

typedef struct _c_Klima_13_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype KL_LVT_M_LED_an : 1;
  vbittype KL_LVT_O_LED_an : 1;
  vbittype unused1 : 6;
  vbittype unused2 : 7;
  vbittype KL_LVT_U_LED_an : 1;
} _c_Klima_13_PAG_RDS_msgType;

typedef struct _c_Miko_01_PAG_RDS_msgTypeTag
{
  vbittype Miko_T_Tuner : 1;
  vbittype Miko_T_Media : 1;
  vbittype Miko_T_Phone : 1;
  vbittype Miko_T_AC_Menue : 1;
  vbittype Miko_T_Source : 1;
  vbittype unused0 : 3;
  vbittype unused1 : 3;
  vbittype Miko_T_Navi : 1;
  vbittype Miko_T_Info : 1;
  vbittype Miko_T_Car : 1;
  vbittype Miko_T_Option : 1;
  vbittype Miko_T_Back : 1;
  vbittype Miko_Volume_press_0 : 1;
  vbittype Miko_Volume_dir : 1;
  vbittype Miko_Volume_Err : 1;
  vbittype Miko_Volume : 5;
  vbittype Miko_MMI_Err : 1;
  vbittype Miko_MMI_fast : 1;
  vbittype Miko_MMI : 5;
  vbittype Miko_Volume_press_1 : 1;
  vbittype unused2 : 7;
  vbittype Miko_MMI_dir : 1;
  vbittype unused3 : 1;
  vbittype Miko_ADR_UltralongPress : 1;
  vbittype Miko_ADR_Reset : 1;
  vbittype unused4 : 5;
} _c_Miko_01_PAG_RDS_msgType;

typedef struct _c_Motor_02_sek_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype Enrgfluss_State_BN : 2;
  vbittype unused1 : 6;
  vbittype unused2 : 6;
  vbittype Enrgfluss_State_sek : 2;
} _c_Motor_02_sek_RDS_msgType;

typedef struct _c_HVLM_07_PAG_RDS_msgTypeTag
{
  vbittype cunused0 : 5;
  vbittype HVLM_Status_Timer_MUX : 3;
  vbittype cunused14 : 6;
  vbittype cunused9 : 2;
  vbittype cunused28 : 4;
  vbittype cunused19 : 4;
  vbittype cunused42 : 1;
  vbittype cunused38 : 1;
  vbittype cunused33 : 5;
  vbittype cunused29 : 1;
  vbittype cunused74 : 1;
  vbittype cunused70 : 1;
  vbittype cunused66 : 1;
  vbittype cunused59 : 1;
  vbittype cunused55 : 1;
  vbittype cunused54 : 1;
  vbittype cunused50 : 1;
  vbittype cunused46 : 1;
} _c_HVLM_07_PAG_RDS_msgType;
typedef struct _c_HVLM_07_PAG_RDS_m1_msgTypeTag
{
  vbittype HVLM_Status_Timer_1_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype HVLM_Status_Timer_1_Minute : 6;
  vbittype HVLM_Status_Timer_1_Jahr_1 : 2;
  vbittype HVLM_Status_Timer_1_Stunde_0 : 4;
  vbittype HVLM_Status_Timer_1_Monat : 4;
  vbittype HVLM_Status_Timer_1_Vorklima : 1;
  vbittype HVLM_Status_Timer_1_Laden : 1;
  vbittype HVLM_Status_Timer_1_Tag : 5;
  vbittype HVLM_Status_Timer_1_Stunde_1 : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_WH : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_So : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_Sa : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_Fr : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_Do : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_Mi : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_Di : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_Mo : 1;
} _c_HVLM_07_PAG_RDS_m1_msgType;
typedef struct _c_HVLM_07_PAG_RDS_m2_msgTypeTag
{
  vbittype HVLM_Status_Timer_2_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype HVLM_Status_Timer_2_Minute : 6;
  vbittype HVLM_Status_Timer_2_Jahr_1 : 2;
  vbittype HVLM_Status_Timer_2_Stunde_0 : 4;
  vbittype HVLM_Status_Timer_2_Monat : 4;
  vbittype HVLM_Status_Timer_2_Vorklima : 1;
  vbittype HVLM_Status_Timer_2_Laden : 1;
  vbittype HVLM_Status_Timer_2_Tag : 5;
  vbittype HVLM_Status_Timer_2_Stunde_1 : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_WH : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_So : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_Sa : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_Fr : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_Do : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_Mi : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_Di : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_Mo : 1;
} _c_HVLM_07_PAG_RDS_m2_msgType;
typedef struct _c_HVLM_07_PAG_RDS_m3_msgTypeTag
{
  vbittype HVLM_Status_Timer_3_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype HVLM_Status_Timer_3_Minute : 6;
  vbittype HVLM_Status_Timer_3_Jahr_1 : 2;
  vbittype HVLM_Status_Timer_3_Stunde_0 : 4;
  vbittype HVLM_Status_Timer_3_Monat : 4;
  vbittype HVLM_Status_Timer_3_Vorklima : 1;
  vbittype HVLM_Status_Timer_3_Laden : 1;
  vbittype HVLM_Status_Timer_3_Tag : 5;
  vbittype HVLM_Status_Timer_3_Stunde_1 : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_WH : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_So : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_Sa : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_Fr : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_Do : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_Mi : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_Di : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_Mo : 1;
} _c_HVLM_07_PAG_RDS_m3_msgType;
typedef struct _c_HVLM_07_PAG_RDS_m4_msgTypeTag
{
  vbittype HVLM_Status_Timer_4_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype HVLM_Status_Timer_4_Minute : 6;
  vbittype HVLM_Status_Timer_4_Jahr_1 : 2;
  vbittype HVLM_Status_Timer_4_Stunde_0 : 4;
  vbittype HVLM_Status_Timer_4_Monat : 4;
  vbittype HVLM_Status_Timer_4_Vorklima : 1;
  vbittype HVLM_Status_Timer_4_Laden : 1;
  vbittype HVLM_Status_Timer_4_Tag : 5;
  vbittype HVLM_Status_Timer_4_Stunde_1 : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_WH : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_So : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_Sa : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_Fr : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_Do : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_Mi : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_Di : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_Mo : 1;
} _c_HVLM_07_PAG_RDS_m4_msgType;
typedef struct _c_HVLM_07_PAG_RDS_m7_msgTypeTag
{
  vbittype HVLM_Status_Timer_7_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype HVLM_Status_Timer_7_Minute : 6;
  vbittype HVLM_Status_Timer_7_Jahr_1 : 2;
  vbittype HVLM_Status_Timer_7_Stunde_0 : 4;
  vbittype HVLM_Status_Timer_7_Monat : 4;
  vbittype unused1 : 2;
  vbittype HVLM_Status_Timer_7_Tag : 5;
  vbittype HVLM_Status_Timer_7_Stunde_1 : 1;
} _c_HVLM_07_PAG_RDS_m7_msgType;

typedef struct _c_Kombi_19_PAG_RDS_msgTypeTag
{
  vbittype KBI_Trip_E_Std_0 : 2;
  vbittype KBI_Trip_E_Min : 6;
  vbittype KBI_Trip_E_Std_1 : 8;
  vbittype unused0 : 3;
  vbittype KBI_Trip_E_Std_2 : 5;
} _c_Kombi_19_PAG_RDS_msgType;

typedef struct _c_Motor_K_02_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 1;
  vbittype MO_StartStopp_Motorstopp : 1;
  vbittype unused6 : 6;
} _c_Motor_K_02_RDS_msgType;

typedef struct _c_ISO_Info_El_Req_RDS_msgTypeTag
{
  vbittype ISO_Info_El_Req_Data_0 : 8;
  vbittype ISO_Info_El_Req_Data_1 : 8;
  vbittype ISO_Info_El_Req_Data_2 : 8;
  vbittype ISO_Info_El_Req_Data_3 : 8;
  vbittype ISO_Info_El_Req_Data_4 : 8;
  vbittype ISO_Info_El_Req_Data_5 : 8;
  vbittype ISO_Info_El_Req_Data_6 : 8;
  vbittype ISO_Info_El_Req_Data_7 : 8;
} _c_ISO_Info_El_Req_RDS_msgType;

typedef struct _c_ISO_Funktionaler_Req_All_RDS_msgTypeTag
{
  vbittype ISO_ALL_01_Req_Data_0 : 8;
  vbittype ISO_ALL_01_Req_Data_1 : 8;
  vbittype ISO_ALL_01_Req_Data_2 : 8;
  vbittype ISO_ALL_01_Req_Data_3 : 8;
  vbittype ISO_ALL_01_Req_Data_4 : 8;
  vbittype ISO_ALL_01_Req_Data_5 : 8;
  vbittype ISO_ALL_01_Req_Data_6 : 8;
  vbittype ISO_ALL_01_Req_Data_7 : 8;
} _c_ISO_Funktionaler_Req_All_RDS_msgType;

typedef struct _c_Kombi_11_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype KBI_Fotosensor : 8;
  vbittype unused3 : 8;
  vbittype KBI_KL58s : 8;
} _c_Kombi_11_PAG_RDS_msgType;

typedef struct _c_Kombi_02_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype KBI_Aussen_Temp_gef : 8;
} _c_Kombi_02_RDS_msgType;

typedef struct _c_Diagnose_01_RDS_msgTypeTag
{
  vbittype DGN_Verlernzaehler : 8;
  vbittype KBI_Kilometerstand_0 : 8;
  vbittype KBI_Kilometerstand_1 : 8;
  vbittype UH_Jahr_0 : 4;
  vbittype KBI_Kilometerstand_2 : 4;
  vbittype UH_Tag_0 : 1;
  vbittype UH_Monat : 4;
  vbittype UH_Jahr_1 : 3;
  vbittype UH_Stunde_0 : 4;
  vbittype UH_Tag_1 : 4;
  vbittype UH_Sekunde_0 : 1;
  vbittype UH_Minute : 6;
  vbittype UH_Stunde_1 : 1;
  vbittype Uhrzeit_01_alt : 1;
  vbittype Kombi_02_alt : 1;
  vbittype unused0 : 1;
  vbittype UH_Sekunde_1 : 5;
} _c_Diagnose_01_RDS_msgType;

typedef struct _c_Klima_03_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype KL_Sonnenintensitaet : 8;
} _c_Klima_03_RDS_msgType;

typedef struct _c_Gateway_03_RDS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype Motor_06_alt : 1;
  vbittype unused1 : 6;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype unused7 : 2;
  vbittype MO_HYB_Fahrbereitschaft : 1;
  vbittype unused8 : 5;
} _c_Gateway_03_RDS_msgType;

typedef struct _c_Klima_02_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype KL_Geblaese_Status : 4;
  vbittype unused4 : 4;
} _c_Klima_02_RDS_msgType;

typedef struct _c_BEM_02_RDS_msgTypeTag
{
  vbittype unused0 : 5;
  vbittype BEM_02_Abschaltstufen : 3;
} _c_BEM_02_RDS_msgType;

typedef struct _c_BCM1_02_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 7;
  vbittype LV_Standlicht_Anzeige : 1;
} _c_BCM1_02_RDS_msgType;

typedef struct _c_GW_Mmi_07_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 7;
  vbittype FT_Tuer_geoeffnet : 1;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype unused7 : 7;
  vbittype F_TSG_FT_01_Mmi : 1;
} _c_GW_Mmi_07_PAG_RDS_msgType;

typedef struct _c_GW_Mmi_06_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype LWI_Lenkradwinkel_0 : 8;
  vbittype unused5 : 2;
  vbittype LWI_VZ_Lenkradwinkel : 1;
  vbittype LWI_Lenkradwinkel_1 : 5;
  vbittype unused6 : 7;
  vbittype F_LWI_01_Mmi : 1;
} _c_GW_Mmi_06_PAG_RDS_msgType;

typedef struct _c_HVLM_05_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype HVLM_Restladezeit_HV_Bat_02_0 : 4;
  vbittype unused1 : 4;
  vbittype unused2 : 1;
  vbittype HVLM_Lademodus_HV_Bat : 2;
  vbittype HVLM_Restladezeit_HV_Bat_02_1 : 5;
  vbittype unused3 : 2;
  vbittype HVLM_Bat_laden_aktiv : 1;
  vbittype unused4 : 5;
  vbittype unused5 : 8;
  vbittype unused6 : 4;
  vbittype HVLM_Ladeart : 2;
  vbittype unused7 : 2;
  vbittype unused8 : 2;
  vbittype HVLM_Stecker_Status : 2;
  vbittype unused9 : 4;
} _c_HVLM_05_RDS_msgType;

typedef struct _c_Kombi_14_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype KBI_Trip_Reset_Std_0 : 2;
  vbittype KBI_Trip_Reset_Min : 6;
  vbittype unused6 : 5;
  vbittype KBI_Trip_Reset_Std_1 : 3;
} _c_Kombi_14_PAG_RDS_msgType;

typedef struct _c_GW_Mmi_10_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype ZV_verriegelt_extern_ist : 1;
  vbittype unused1 : 6;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype unused7 : 8;
  vbittype unused8 : 7;
  vbittype F_BCM2_02_Mmi : 1;
} _c_GW_Mmi_10_PAG_RDS_msgType;

typedef struct _c_Gateway_01_RDS_msgTypeTag
{
  vbittype ESP_01_alt : 1;
  vbittype unused0 : 1;
  vbittype EPB_01_alt : 1;
  vbittype unused1 : 3;
  vbittype Getriebe_03_alt : 1;
  vbittype Motor_03_alt : 1;
  vbittype ESP_v_Signal_0 : 8;
  vbittype ESP_v_Signal_1 : 8;
  vbittype unused2 : 4;
  vbittype EPB_Status : 2;
  vbittype unused3 : 2;
  vbittype unused4 : 4;
  vbittype GE_Waehlhebel : 4;
  vbittype MO_Drehzahl_01_0 : 8;
  vbittype MO_Drehzahl_01_1 : 8;
} _c_Gateway_01_RDS_msgType;

typedef struct _c_Klemmen_Status_01_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 6;
  vbittype ZAS_Kl_15 : 1;
  vbittype ZAS_Kl_S : 1;
} _c_Klemmen_Status_01_RDS_msgType;

typedef struct _c_Kombi_17_PAG_RDS_msgTypeTag
{
  vbittype KBI_Trip_DS_Verbr_2_0 : 8;
  vbittype KBI_Trip_Min_2_0 : 2;
  vbittype KBI_Trip_DS_Verbr_2_1 : 6;
  vbittype KBI_Trip_Std_2_0 : 4;
  vbittype KBI_Trip_Min_2_1 : 4;
  vbittype KBI_Trip_Std_2_1 : 8;
  vbittype KBI_Trip_Strecke_2_0 : 5;
  vbittype KBI_Trip_Std_2_2 : 3;
  vbittype KBI_Trip_Strecke_2_1 : 8;
  vbittype KBI_Trip_DS_V_2_0 : 4;
  vbittype KBI_Trip_Strecke_2_2 : 4;
  vbittype unused0 : 3;
  vbittype KBI_Trip_DS_V_2_1 : 5;
} _c_Kombi_17_PAG_RDS_msgType;

typedef struct _c_Kombi_16_PAG_RDS_msgTypeTag
{
  vbittype KBI_Trip_DS_Verbr_1_0 : 8;
  vbittype KBI_Trip_Min_1_0 : 2;
  vbittype KBI_Trip_DS_Verbr_1_1 : 6;
  vbittype KBI_Trip_Std_1_0 : 4;
  vbittype KBI_Trip_Min_1_1 : 4;
  vbittype KBI_Trip_Std_1_1 : 8;
  vbittype KBI_Trip_Strecke_1_0 : 5;
  vbittype KBI_Trip_Std_1_2 : 3;
  vbittype KBI_Trip_Strecke_1_1 : 8;
  vbittype KBI_Trip_DS_V_1_0 : 4;
  vbittype KBI_Trip_Strecke_1_2 : 4;
  vbittype unused0 : 3;
  vbittype KBI_Trip_DS_V_1_1 : 5;
} _c_Kombi_16_PAG_RDS_msgType;

typedef struct _c_GW_Mmi_01_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 7;
  vbittype BCM1_Rueckfahrlicht_Schalter : 1;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype unused7 : 2;
  vbittype F_BCM1_01_Mmi : 1;
  vbittype unused8 : 5;
} _c_GW_Mmi_01_PAG_RDS_msgType;

typedef struct _c_GW_Mmi_05_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype ESP_Querbeschleunigung_Roh_0 : 8;
  vbittype unused2 : 1;
  vbittype ESP_Querbeschleunigung_Offset : 6;
  vbittype ESP_Querbeschleunigung_Roh_1 : 1;
  vbittype unused3 : 2;
  vbittype ESP_Off_Lampe : 1;
  vbittype unused4 : 5;
  vbittype unused5 : 6;
  vbittype ESP_Stillstandsflag : 1;
  vbittype unused6 : 1;
  vbittype unused7 : 8;
  vbittype unused8 : 2;
  vbittype F_ESP_13_Mmi : 1;
  vbittype unused9 : 1;
  vbittype F_ESP_02_Mmi : 1;
  vbittype F_ESP_04_Mmi : 1;
  vbittype unused10 : 2;
} _c_GW_Mmi_05_PAG_RDS_msgType;

typedef struct _c_BCM2_03_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype BCM2_DWA_aktiv : 1;
  vbittype unused3 : 7;
} _c_BCM2_03_PAG_RDS_msgType;

typedef struct _c_GW_Mmi_04_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 2;
  vbittype MO_HYB_VM_aktiv : 1;
  vbittype unused4 : 1;
  vbittype DR_Daempferreg_Texte : 4;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype unused7 : 5;
  vbittype F_Daempfer_01_FR_Mmi : 1;
  vbittype unused8 : 2;
  vbittype unused9 : 1;
  vbittype F_Motor_Hybrid_01_Mmi : 1;
  vbittype unused10 : 6;
} _c_GW_Mmi_04_PAG_RDS_msgType;

typedef struct _c_Kombi_10_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype KBI_V_Anz_0 : 8;
  vbittype unused3 : 1;
  vbittype KBI_V_Anz_1 : 7;
} _c_Kombi_10_PAG_RDS_msgType;

typedef struct _c_Kombi_13_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype KBI_Reichw_anz_0 : 4;
  vbittype unused3 : 4;
  vbittype KBI_Reichw_anz_1 : 8;
  vbittype KBI_E_Restreichweite_0 : 8;
  vbittype unused4 : 4;
  vbittype KBI_E_Restreichweite_1 : 4;
} _c_Kombi_13_PAG_RDS_msgType;

typedef struct _c_ESP_10_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype ESP_QBit_Wegimpuls_HR : 1;
  vbittype ESP_QBit_Wegimpuls_HL : 1;
  vbittype ESP_QBit_Wegimpuls_VR : 1;
  vbittype ESP_QBit_Wegimpuls_VL : 1;
  vbittype unused1 : 4;
  vbittype ESP_Wegimpuls_VL_0 : 8;
  vbittype ESP_Wegimpuls_VR_0 : 6;
  vbittype ESP_Wegimpuls_VL_1 : 2;
  vbittype ESP_Wegimpuls_HL_0 : 4;
  vbittype ESP_Wegimpuls_VR_1 : 4;
  vbittype ESP_Wegimpuls_HR_0 : 2;
  vbittype ESP_Wegimpuls_HL_1 : 6;
  vbittype ESP_Wegimpuls_HR_1 : 8;
  vbittype ESP_HR_Fahrtrichtung : 2;
  vbittype ESP_HL_Fahrtrichtung : 2;
  vbittype ESP_VR_Fahrtrichtung : 2;
  vbittype ESP_VL_Fahrtrichtung : 2;
} _c_ESP_10_RDS_msgType;

typedef struct _c_Getriebe_03_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 4;
  vbittype GE_Zielgang : 4;
} _c_Getriebe_03_RDS_msgType;

typedef struct _c_ESP_02_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype ESP_Laengsbeschl_0 : 8;
  vbittype unused3 : 6;
  vbittype ESP_Laengsbeschl_1 : 2;
} _c_ESP_02_RDS_msgType;

typedef struct _c_ESP_01_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 7;
  vbittype ASR_Tastung_passiv : 1;
} _c_ESP_01_RDS_msgType;

typedef struct _c_Einheiten_01_RDS_msgTypeTag
{
  vbittype KBI_Einheit_Uhrzeit : 1;
  vbittype KBI_Einheit_Temp : 1;
  vbittype KBI_MFA_v_Einheit_02 : 1;
  vbittype KBI_Einheit_Streckenanz : 1;
  vbittype KBI_Einheit_Druck : 2;
  vbittype KBI_Einheit_Datum : 2;
  vbittype unused0 : 1;
  vbittype KBI_Einheit_Verbrauch_elektr : 3;
  vbittype KBI_Einheit_Volumen : 2;
  vbittype KBI_Einheit_Verbrauch : 2;
  vbittype KBI_Einheit_Sprache : 8;
} _c_Einheiten_01_RDS_msgType;

typedef struct _c_ISO_Info_El_Resp_RDS_msgTypeTag
{
  vbittype ISO_Info_El_Resp_Data_0 : 8;
  vbittype ISO_Info_El_Resp_Data_1 : 8;
  vbittype ISO_Info_El_Resp_Data_2 : 8;
  vbittype ISO_Info_El_Resp_Data_3 : 8;
  vbittype ISO_Info_El_Resp_Data_4 : 8;
  vbittype ISO_Info_El_Resp_Data_5 : 8;
  vbittype ISO_Info_El_Resp_Data_6 : 8;
  vbittype ISO_Info_El_Resp_Data_7 : 8;
} _c_ISO_Info_El_Resp_RDS_msgType;

typedef struct _c_Kombi_09_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype KBI_SDruck_HA_komfort_0 : 2;
  vbittype KBI_SDruck_VA_komfort : 6;
  vbittype KBI_SDruck_VA_vmax_0 : 4;
  vbittype KBI_SDruck_HA_komfort_1 : 4;
  vbittype KBI_SDruck_HA_vmax : 6;
  vbittype KBI_SDruck_VA_vmax_1 : 2;
  vbittype unused2 : 8;
  vbittype KBI_KomfortDruck_V_Warnschwelle : 2;
  vbittype ActiveSafe_HMI_FStatus : 1;
  vbittype ActiveSafe_HMI_Vorwarnung : 1;
  vbittype KBI_RDK_Beladung_neu : 1;
  vbittype KBI_RDK_DDAnz_akt : 1;
  vbittype KBI_RDK_Solldruck_neu : 1;
  vbittype KBI_KomfortDruck : 1;
  vbittype unused3 : 6;
  vbittype KBI_RS_Druck_uebernehmen : 1;
  vbittype KBI_Rundstreckenmodus : 1;
} _c_Kombi_09_PAG_RDS_msgType;

typedef struct _c_Kombi_18_PAG_RDS_msgTypeTag
{
  vbittype cunused0 : 5;
  vbittype KBI_Set_Timer_MUX : 3;
  vbittype cunused11 : 6;
  vbittype cunused7 : 2;
  vbittype cunused16 : 4;
  vbittype cunused12 : 4;
  vbittype cunused35 : 1;
  vbittype cunused28 : 1;
  vbittype cunused24 : 5;
  vbittype cunused23 : 1;
  vbittype cunused67 : 1;
  vbittype cunused63 : 1;
  vbittype cunused59 : 1;
  vbittype cunused52 : 1;
  vbittype cunused48 : 1;
  vbittype cunused47 : 1;
  vbittype cunused43 : 1;
  vbittype cunused39 : 1;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
} _c_Kombi_18_PAG_RDS_msgType;
typedef struct _c_Kombi_18_PAG_RDS_m1_msgTypeTag
{
  vbittype KBI_Set_Timer_1_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype KBI_Set_Timer_1_Minute : 6;
  vbittype KBI_Set_Timer_1_Jahr_1 : 2;
  vbittype KBI_Set_Timer_1_Stunde_0 : 4;
  vbittype KBI_Set_Timer_1_Monat : 4;
  vbittype KBI_Set_Timer_1_Vorklima : 1;
  vbittype KBI_Set_Timer_1_Laden : 1;
  vbittype KBI_Set_Timer_1_Tag : 5;
  vbittype KBI_Set_Timer_1_Stunde_1 : 1;
  vbittype KBI_Set_Timer_1_Zyklus_WH : 1;
  vbittype KBI_Set_Timer_1_Zyklus_So : 1;
  vbittype KBI_Set_Timer_1_Zyklus_Sa : 1;
  vbittype KBI_Set_Timer_1_Zyklus_Fr : 1;
  vbittype KBI_Set_Timer_1_Zyklus_Do : 1;
  vbittype KBI_Set_Timer_1_Zyklus_Mi : 1;
  vbittype KBI_Set_Timer_1_Zyklus_Di : 1;
  vbittype KBI_Set_Timer_1_Zyklus_Mo : 1;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
} _c_Kombi_18_PAG_RDS_m1_msgType;
typedef struct _c_Kombi_18_PAG_RDS_m2_msgTypeTag
{
  vbittype KBI_Set_Timer_2_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype KBI_Set_Timer_2_Minute : 6;
  vbittype KBI_Set_Timer_2_Jahr_1 : 2;
  vbittype KBI_Set_Timer_2_Stunde_0 : 4;
  vbittype KBI_Set_Timer_2_Monat : 4;
  vbittype KBI_Set_Timer_2_Vorklima : 1;
  vbittype KBI_Set_Timer_2_Laden : 1;
  vbittype KBI_Set_Timer_2_Tag : 5;
  vbittype KBI_Set_Timer_2_Stunde_1 : 1;
  vbittype KBI_Set_Timer_2_Zyklus_WH : 1;
  vbittype KBI_Set_Timer_2_Zyklus_So : 1;
  vbittype KBI_Set_Timer_2_Zyklus_Sa : 1;
  vbittype KBI_Set_Timer_2_Zyklus_Fr : 1;
  vbittype KBI_Set_Timer_2_Zyklus_Do : 1;
  vbittype KBI_Set_Timer_2_Zyklus_Mi : 1;
  vbittype KBI_Set_Timer_2_Zyklus_Di : 1;
  vbittype KBI_Set_Timer_2_Zyklus_Mo : 1;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
} _c_Kombi_18_PAG_RDS_m2_msgType;
typedef struct _c_Kombi_18_PAG_RDS_m3_msgTypeTag
{
  vbittype KBI_Set_Timer_3_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype KBI_Set_Timer_3_Minute : 6;
  vbittype KBI_Set_Timer_3_Jahr_1 : 2;
  vbittype KBI_Set_Timer_3_Stunde_0 : 4;
  vbittype KBI_Set_Timer_3_Monat : 4;
  vbittype KBI_Set_Timer_3_Vorklima : 1;
  vbittype KBI_Set_Timer_3_Laden : 1;
  vbittype KBI_Set_Timer_3_Tag : 5;
  vbittype KBI_Set_Timer_3_Stunde_1 : 1;
  vbittype KBI_Set_Timer_3_Zyklus_WH : 1;
  vbittype KBI_Set_Timer_3_Zyklus_So : 1;
  vbittype KBI_Set_Timer_3_Zyklus_Sa : 1;
  vbittype KBI_Set_Timer_3_Zyklus_Fr : 1;
  vbittype KBI_Set_Timer_3_Zyklus_Do : 1;
  vbittype KBI_Set_Timer_3_Zyklus_Mi : 1;
  vbittype KBI_Set_Timer_3_Zyklus_Di : 1;
  vbittype KBI_Set_Timer_3_Zyklus_Mo : 1;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
} _c_Kombi_18_PAG_RDS_m3_msgType;
typedef struct _c_Kombi_18_PAG_RDS_m4_msgTypeTag
{
  vbittype KBI_Set_Timer_4_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype KBI_Set_Timer_4_Minute : 6;
  vbittype KBI_Set_Timer_4_Jahr_1 : 2;
  vbittype KBI_Set_Timer_4_Stunde_0 : 4;
  vbittype KBI_Set_Timer_4_Monat : 4;
  vbittype KBI_Set_Timer_4_Vorklima : 1;
  vbittype KBI_Set_Timer_4_Laden : 1;
  vbittype KBI_Set_Timer_4_Tag : 5;
  vbittype KBI_Set_Timer_4_Stunde_1 : 1;
  vbittype KBI_Set_Timer_4_Zyklus_WH : 1;
  vbittype KBI_Set_Timer_4_Zyklus_So : 1;
  vbittype KBI_Set_Timer_4_Zyklus_Sa : 1;
  vbittype KBI_Set_Timer_4_Zyklus_Fr : 1;
  vbittype KBI_Set_Timer_4_Zyklus_Do : 1;
  vbittype KBI_Set_Timer_4_Zyklus_Mi : 1;
  vbittype KBI_Set_Timer_4_Zyklus_Di : 1;
  vbittype KBI_Set_Timer_4_Zyklus_Mo : 1;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
} _c_Kombi_18_PAG_RDS_m4_msgType;

typedef struct _c_Mem_Kombi_01_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype KBI_FLA_GLW_Aktiv : 1;
  vbittype KBI_Schneekettenmodus_Aktiv : 1;
  vbittype KBI_Einstiegshilfe_aktiv : 1;
  vbittype KBI_FULL_AFS_Tourist : 1;
  vbittype KBI_Schaltpkt_Anz_ein : 1;
  vbittype KBI_Aussenspiegel_einklapp_auto : 1;
  vbittype KBI_Aussenspiegel_absenken_auto : 1;
  vbittype KBI_RS_d_akt : 1;
  vbittype KBI_Dimmung_OriLicht : 7;
  vbittype KBI_Heckrollo_b_R : 1;
  vbittype KBI_Auto_Umluft : 1;
  vbittype KBI_Erw_BelueftFeld : 1;
  vbittype KBI_Nachleucht_IL : 5;
  vbittype KBI_Heckw_b_R : 2;
  vbittype KBI_TFL_akt : 1;
  vbittype KBI_Nachleucht : 5;
  vbittype KBI_Carjack : 2;
  vbittype KBI_Tuerentr_T : 1;
  vbittype KBI_WV_Entr : 5;
  vbittype KBI_LDW_aktiv : 1;
  vbittype KBI_Jokerkey_Hupe_Aktiv : 1;
  vbittype KBI_Automem_Inaktiv : 1;
  vbittype unused1 : 1;
  vbittype KBI_WV_Entr_Kof : 4;
  vbittype KBI_Mittenduesentemp : 3;
  vbittype KBI_Klimastyles : 2;
  vbittype unused2 : 1;
  vbittype KBI_Steigerung_Luftmenge_Fond : 1;
  vbittype KBI_PTC_Zuheizer : 1;
  vbittype KBI_Innenlicht_per_Tuerkontakt : 1;
  vbittype KBI_Dimmung_AmbLicht : 7;
} _c_Mem_Kombi_01_PAG_RDS_msgType;

typedef struct _c_NMH_CDR_PCM_RDS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype NM_CDR_PCM_Car_WakeUp : 1;
  vbittype unused1 : 2;
  vbittype NM_CDR_PCM_Normal_Mode_2 : 1;
  vbittype NM_CDR_PCM_Normal_Mode_1 : 1;
  vbittype NM_CDR_PCM_Start_2 : 1;
  vbittype NM_CDR_PCM_Start_1 : 1;
  vbittype NM_CDR_PCM_Fkt_WakeUp : 3;
  vbittype NM_CDR_PCM_Per_WakeUp : 5;
  vbittype unused2 : 5;
  vbittype NM_CDR_PCM_MindestAktivZeit : 1;
  vbittype NM_CDR_PCM_Diagnose : 1;
  vbittype NM_CDR_PCM_Klemme_15 : 1;
  vbittype unused3 : 8;
  vbittype NM_CDR_PCM_Busfehler : 1;
  vbittype NM_CDR_PCM_Abschaltstufe_aktiv : 1;
  vbittype NM_CDR_PCM_Transport_Mode : 1;
  vbittype NM_CDR_PCM_Mute_Mode : 1;
  vbittype NM_CDR_PCM_KompSchutz : 1;
  vbittype NM_CDR_PCM_CAN_Diag_deaktiv : 1;
  vbittype NM_CDR_PCM_TimeOut_Fehler : 1;
  vbittype NMH_CDR_PCM_Signalfehler : 1;
  vbittype unused4 : 8;
  vbittype unused5 : 6;
  vbittype NMH_CDR_PCM_Subsystemaktiv : 1;
  vbittype NMH_CDR_PCM_Lokalaktiv : 1;
} _c_NMH_CDR_PCM_RDS_msgType;

typedef struct _c_PCM_02_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype PCM_FOT_Temp : 7;
  vbittype unused1 : 2;
  vbittype PCM_Rundenfarbe : 2;
  vbittype PCM_RFK_manuell : 2;
  vbittype PCM_HMI_mode : 2;
  vbittype PCM_Limit_Einheit : 1;
  vbittype PCM_Limit_Info : 7;
  vbittype PCM_Rundenfortschritt : 8;
  vbittype PCM_Kompass_0 : 8;
  vbittype unused2 : 1;
  vbittype PCM_HMI_Mode_TopView : 5;
  vbittype PCM_Elev_Einheit : 1;
  vbittype PCM_Kompass_1 : 1;
  vbittype PCM_Sat : 4;
  vbittype PCM_Street_class : 4;
  vbittype PCM_Entfernung_Kurve : 8;
} _c_PCM_02_PAG_RDS_msgType;

typedef struct _c_PCM_04_PAG_RDS_msgTypeTag
{
  vbittype GPS_N_Grad_0 : 8;
  vbittype GPS_N_Grad_1 : 8;
  vbittype GPS_N_Grad_2 : 8;
  vbittype GPS_E_Grad_0 : 7;
  vbittype GPS_N_Grad_3 : 1;
  vbittype GPS_E_Grad_1 : 8;
  vbittype GPS_E_Grad_2 : 8;
  vbittype GPS_elev_0 : 5;
  vbittype GPS_E_Grad_3 : 3;
  vbittype GPS_elev_1 : 8;
} _c_PCM_04_PAG_RDS_msgType;

typedef struct _c_PCM_CDR_01_PAG_RDS_msgTypeTag
{
  vbittype PCM_Min_0 : 3;
  vbittype PCM_Std : 5;
  vbittype PCM_Sek_0 : 5;
  vbittype PCM_Min_1 : 3;
  vbittype PCM_Uebern : 1;
  vbittype PCM_Zeitzone_Vorzeichen : 1;
  vbittype PCM_Zeitzone : 5;
  vbittype PCM_Sek_1 : 1;
  vbittype PCM_Mon_0 : 3;
  vbittype PCM_Tag : 5;
  vbittype PCM_JJ : 7;
  vbittype PCM_Mon_1 : 1;
  vbittype unused0 : 5;
  vbittype PCM_Reset_Trip_2 : 1;
  vbittype PCM_Reset_Trip_1 : 1;
  vbittype PCM_Sommerzeit : 1;
  vbittype HU_Fotosensor_0 : 8;
  vbittype HU_KD_Fehler : 1;
  vbittype HU_Topview_on_Anf : 1;
  vbittype HU_PCMCDR : 1;
  vbittype PCM_KD_Fehler_TV : 1;
  vbittype PCM_KD_Fehler_AMP : 1;
  vbittype PCM_SVB_TV : 1;
  vbittype HU_SVB_AMP : 1;
  vbittype HU_Fotosensor_1 : 1;
} _c_PCM_CDR_01_PAG_RDS_msgType;

typedef struct _c_ADR_01_PAG_RDS_msgTypeTag
{
  vbittype Adr_Tuner_LED_an : 1;
  vbittype Adr_Media_LED_an : 1;
  vbittype Adr_Phone_LED_an : 1;
  vbittype Adr_AC_Menue_LED_an : 1;
  vbittype Adr_T_LVT_U : 1;
  vbittype Adr_T_LVT_M : 1;
  vbittype Adr_T_LVT_O : 1;
  vbittype Adr_Clima_Mono : 1;
  vbittype Adr_Pos_En : 1;
  vbittype Adr_Alive_Cnt : 4;
  vbittype Adr_Navi_LED_an : 1;
  vbittype Adr_Info_LED_an : 1;
  vbittype Adr_Car_LED_an : 1;
  vbittype unused0 : 3;
  vbittype Adr_Active_Character_Page : 4;
  vbittype Adr_Display_Status : 1;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype Adr_Chr_Mode : 8;
  vbittype Adr_Gst_Mode_0 : 8;
  vbittype Adr_Gst_Mode_1 : 8;
} _c_ADR_01_PAG_RDS_msgType;

typedef struct _c_ADR_02_PAG_RDS_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 1;
  vbittype Adr_Konfig_Datenfeld : 3;
  vbittype unused2 : 4;
  vbittype Adr_KI_BC_Rolle_Konfig : 8;
  vbittype Adr_Joker_Taste : 3;
  vbittype Adr_KI_BC_Rolle_Datenfeld : 5;
  vbittype Adr_KI_Helligkeit_0 : 1;
  vbittype Adr_KL58d : 7;
  vbittype Adr_Miko_Helligkeit_0 : 2;
  vbittype Adr_KI_Helligkeit_1 : 6;
  vbittype unused3 : 3;
  vbittype Adr_Miko_Helligkeit_1 : 5;
  vbittype unused4 : 8;
} _c_ADR_02_PAG_RDS_msgType;

typedef union _c_RDSBasic_bufTag
{
  vuint8 _c[8];
  _c_Kombi_EV_01_PAG_RDS_msgType Kombi_EV_01_PAG;
  _c_LAD_02_RDS_msgType LAD_02;
  _c_Lift_01_RDS_msgType Lift_01;
  _c_MFL_Tasten_Kon_01_RDS_msgType MFL_Tasten_Kon_01;
  _c_Motor_06_RDS_msgType Motor_06;
  _c_Motor_15_PAG_RDS_msgType Motor_15_PAG;
  _c_NPM_01_PAG_RDS_msgType NPM_01_PAG;
  _c_RDK_02_PAG_RDS_msgType RDK_02_PAG;
  _c_Systeminfo_01_RDS_msgType Systeminfo_01;
  _c_VIN_01_RDS_msgType VIN_01;
  _c_VIN_01_RDS_m0_msgType VIN_01_m0;
  _c_VIN_01_RDS_m1_msgType VIN_01_m1;
  _c_VIN_01_RDS_m2_msgType VIN_01_m2;
  _c_Klima_13_PAG_RDS_msgType Klima_13_PAG;
  _c_Miko_01_PAG_RDS_msgType Miko_01_PAG;
  _c_Motor_02_sek_RDS_msgType Motor_02_sek;
  _c_HVLM_07_PAG_RDS_msgType HVLM_07_PAG;
  _c_HVLM_07_PAG_RDS_m1_msgType HVLM_07_PAG_m1;
  _c_HVLM_07_PAG_RDS_m2_msgType HVLM_07_PAG_m2;
  _c_HVLM_07_PAG_RDS_m3_msgType HVLM_07_PAG_m3;
  _c_HVLM_07_PAG_RDS_m4_msgType HVLM_07_PAG_m4;
  _c_HVLM_07_PAG_RDS_m7_msgType HVLM_07_PAG_m7;
  _c_Kombi_19_PAG_RDS_msgType Kombi_19_PAG;
  _c_Motor_K_02_RDS_msgType Motor_K_02;
} _c_RDSBasic_buf;
typedef union _c_RDS2_bufTag
{
  vuint8 _c[8];
  _c_ISO_Info_El_Req_RDS_msgType ISO_Info_El_Req;
} _c_RDS2_buf;
typedef union _c_RDS3_bufTag
{
  vuint8 _c[8];
  _c_ISO_Funktionaler_Req_All_RDS_msgType ISO_Funktionaler_Req_All;
} _c_RDS3_buf;
typedef union _c_RDS4_bufTag
{
  vuint8 _c[6];
  _c_Kombi_11_PAG_RDS_msgType Kombi_11_PAG;
} _c_RDS4_buf;
typedef union _c_RDS5_bufTag
{
  vuint8 _c[8];
  _c_Kombi_02_RDS_msgType Kombi_02;
} _c_RDS5_buf;
typedef union _c_RDS6_bufTag
{
  vuint8 _c[8];
  _c_Diagnose_01_RDS_msgType Diagnose_01;
} _c_RDS6_buf;
typedef union _c_RDS7_bufTag
{
  vuint8 _c[6];
  _c_Klima_03_RDS_msgType Klima_03;
} _c_RDS7_buf;
typedef union _c_RDS8_bufTag
{
  vuint8 _c[7];
  _c_Gateway_03_RDS_msgType Gateway_03;
} _c_RDS8_buf;
typedef union _c_RDS9_bufTag
{
  vuint8 _c[5];
  _c_Klima_02_RDS_msgType Klima_02;
} _c_RDS9_buf;
typedef union _c_RDS10_bufTag
{
  vuint8 _c[1];
  _c_BEM_02_RDS_msgType BEM_02;
} _c_RDS10_buf;
typedef union _c_RDS11_bufTag
{
  vuint8 _c[3];
  _c_BCM1_02_RDS_msgType BCM1_02;
} _c_RDS11_buf;
typedef union _c_RDS12_bufTag
{
  vuint8 _c[8];
  _c_GW_Mmi_07_PAG_RDS_msgType GW_Mmi_07_PAG;
} _c_RDS12_buf;
typedef union _c_RDS13_bufTag
{
  vuint8 _c[8];
  _c_GW_Mmi_06_PAG_RDS_msgType GW_Mmi_06_PAG;
} _c_RDS13_buf;
typedef union _c_RDS14_bufTag
{
  vuint8 _c[7];
  _c_HVLM_05_RDS_msgType HVLM_05;
} _c_RDS14_buf;
typedef union _c_RDS15_bufTag
{
  vuint8 _c[8];
  _c_Kombi_14_PAG_RDS_msgType Kombi_14_PAG;
} _c_RDS15_buf;
typedef union _c_RDS16_bufTag
{
  vuint8 _c[8];
  _c_GW_Mmi_10_PAG_RDS_msgType GW_Mmi_10_PAG;
} _c_RDS16_buf;
typedef union _c_RDS17_bufTag
{
  vuint8 _c[7];
  _c_Gateway_01_RDS_msgType Gateway_01;
} _c_RDS17_buf;
typedef union _c_RDS18_bufTag
{
  vuint8 _c[3];
  _c_Klemmen_Status_01_RDS_msgType Klemmen_Status_01;
} _c_RDS18_buf;
typedef union _c_RDS19_bufTag
{
  vuint8 _c[8];
  _c_Kombi_17_PAG_RDS_msgType Kombi_17_PAG;
} _c_RDS19_buf;
typedef union _c_RDS20_bufTag
{
  vuint8 _c[8];
  _c_Kombi_16_PAG_RDS_msgType Kombi_16_PAG;
} _c_RDS20_buf;
typedef union _c_RDS21_bufTag
{
  vuint8 _c[8];
  _c_GW_Mmi_01_PAG_RDS_msgType GW_Mmi_01_PAG;
} _c_RDS21_buf;
typedef union _c_RDS22_bufTag
{
  vuint8 _c[8];
  _c_GW_Mmi_05_PAG_RDS_msgType GW_Mmi_05_PAG;
} _c_RDS22_buf;
typedef union _c_RDS23_bufTag
{
  vuint8 _c[4];
  _c_BCM2_03_PAG_RDS_msgType BCM2_03_PAG;
} _c_RDS23_buf;
typedef union _c_RDS24_bufTag
{
  vuint8 _c[8];
  _c_GW_Mmi_04_PAG_RDS_msgType GW_Mmi_04_PAG;
} _c_RDS24_buf;
typedef union _c_RDS25_bufTag
{
  vuint8 _c[5];
  _c_Kombi_10_PAG_RDS_msgType Kombi_10_PAG;
} _c_RDS25_buf;
typedef union _c_RDS26_bufTag
{
  vuint8 _c[7];
  _c_Kombi_13_PAG_RDS_msgType Kombi_13_PAG;
} _c_RDS26_buf;
typedef union _c_RDS27_bufTag
{
  vuint8 _c[8];
  _c_ESP_10_RDS_msgType ESP_10;
} _c_RDS27_buf;
typedef union _c_RDS28_bufTag
{
  vuint8 _c[4];
  _c_Getriebe_03_RDS_msgType Getriebe_03;
} _c_RDS28_buf;
typedef union _c_RDS29_bufTag
{
  vuint8 _c[5];
  _c_ESP_02_RDS_msgType ESP_02;
} _c_RDS29_buf;
typedef union _c_RDS30_bufTag
{
  vuint8 _c[7];
  _c_ESP_01_RDS_msgType ESP_01;
} _c_RDS30_buf;
typedef union _c_RDS_Tx_bufTag
{
  vuint8 _c[8];
  _c_Einheiten_01_RDS_msgType Einheiten_01;
  _c_ISO_Info_El_Resp_RDS_msgType ISO_Info_El_Resp;
  _c_Kombi_09_PAG_RDS_msgType Kombi_09_PAG;
  _c_Kombi_18_PAG_RDS_msgType Kombi_18_PAG;
  _c_Kombi_18_PAG_RDS_m1_msgType Kombi_18_PAG_m1;
  _c_Kombi_18_PAG_RDS_m2_msgType Kombi_18_PAG_m2;
  _c_Kombi_18_PAG_RDS_m3_msgType Kombi_18_PAG_m3;
  _c_Kombi_18_PAG_RDS_m4_msgType Kombi_18_PAG_m4;
  _c_Mem_Kombi_01_PAG_RDS_msgType Mem_Kombi_01_PAG;
  _c_NMH_CDR_PCM_RDS_msgType NMH_CDR_PCM;
  _c_PCM_02_PAG_RDS_msgType PCM_02_PAG;
  _c_PCM_04_PAG_RDS_msgType PCM_04_PAG;
  _c_PCM_CDR_01_PAG_RDS_msgType PCM_CDR_01_PAG;
  _c_ADR_01_PAG_RDS_msgType ADR_01_PAG;
  _c_ADR_02_PAG_RDS_msgType ADR_02_PAG;
} _c_RDS_Tx_buf;


#define RDSBasic                             ((* ((_c_RDSBasic_buf  *)(canRDSRxPtr[0]))))
#define RDS2                                 ((* ((_c_RDS2_buf  *)(canRDSRxPtr[0]))))
#define RDS3                                 ((* ((_c_RDS3_buf  *)(canRDSRxPtr[0]))))
#define RDS4                                 ((* ((_c_RDS4_buf  *)(canRDSRxPtr[0]))))
#define RDS5                                 ((* ((_c_RDS5_buf  *)(canRDSRxPtr[0]))))
#define RDS6                                 ((* ((_c_RDS6_buf  *)(canRDSRxPtr[0]))))
#define RDS7                                 ((* ((_c_RDS7_buf  *)(canRDSRxPtr[0]))))
#define RDS8                                 ((* ((_c_RDS8_buf  *)(canRDSRxPtr[0]))))
#define RDS9                                 ((* ((_c_RDS9_buf  *)(canRDSRxPtr[0]))))
#define RDS10                                ((* ((_c_RDS10_buf  *)(canRDSRxPtr[0]))))
#define RDS11                                ((* ((_c_RDS11_buf  *)(canRDSRxPtr[0]))))
#define RDS12                                ((* ((_c_RDS12_buf  *)(canRDSRxPtr[0]))))
#define RDS13                                ((* ((_c_RDS13_buf  *)(canRDSRxPtr[0]))))
#define RDS14                                ((* ((_c_RDS14_buf  *)(canRDSRxPtr[0]))))
#define RDS15                                ((* ((_c_RDS15_buf  *)(canRDSRxPtr[0]))))
#define RDS16                                ((* ((_c_RDS16_buf  *)(canRDSRxPtr[0]))))
#define RDS17                                ((* ((_c_RDS17_buf  *)(canRDSRxPtr[0]))))
#define RDS18                                ((* ((_c_RDS18_buf  *)(canRDSRxPtr[0]))))
#define RDS19                                ((* ((_c_RDS19_buf  *)(canRDSRxPtr[0]))))
#define RDS20                                ((* ((_c_RDS20_buf  *)(canRDSRxPtr[0]))))
#define RDS21                                ((* ((_c_RDS21_buf  *)(canRDSRxPtr[0]))))
#define RDS22                                ((* ((_c_RDS22_buf  *)(canRDSRxPtr[0]))))
#define RDS23                                ((* ((_c_RDS23_buf  *)(canRDSRxPtr[0]))))
#define RDS24                                ((* ((_c_RDS24_buf  *)(canRDSRxPtr[0]))))
#define RDS25                                ((* ((_c_RDS25_buf  *)(canRDSRxPtr[0]))))
#define RDS26                                ((* ((_c_RDS26_buf  *)(canRDSRxPtr[0]))))
#define RDS27                                ((* ((_c_RDS27_buf  *)(canRDSRxPtr[0]))))
#define RDS28                                ((* ((_c_RDS28_buf  *)(canRDSRxPtr[0]))))
#define RDS29                                ((* ((_c_RDS29_buf  *)(canRDSRxPtr[0]))))
#define RDS30                                ((* ((_c_RDS30_buf  *)(canRDSRxPtr[0]))))
#define RDSTx                                ((* ((_c_RDS_Tx_buf  *)(canRDSTxPtr[0]))))



/* -----------------------------------------------------------------------------
    &&&~ Message Hardware Objects
 ----------------------------------------------------------------------------- */

#define C_BASIC0_HW_OBJ                      0
#define C_BASIC0_HW_CHANNEL                  0
#define CanRxISO_Info_El_Req_HW_OBJ          2
#define CanRxISO_Info_El_Req_HW_CHANNEL      0
#define CanRxISO_Funktionaler_Req_All_HW_OBJ 3
#define CanRxISO_Funktionaler_Req_All_HW_CHANNEL 0
#define CanRxKombi_11_PAG_HW_OBJ             4
#define CanRxKombi_11_PAG_HW_CHANNEL         0
#define CanRxKombi_02_HW_OBJ                 5
#define CanRxKombi_02_HW_CHANNEL             0
#define CanRxDiagnose_01_HW_OBJ              6
#define CanRxDiagnose_01_HW_CHANNEL          0
#define CanRxKlima_03_HW_OBJ                 7
#define CanRxKlima_03_HW_CHANNEL             0
#define CanRxGateway_03_HW_OBJ               8
#define CanRxGateway_03_HW_CHANNEL           0
#define CanRxKlima_02_HW_OBJ                 9
#define CanRxKlima_02_HW_CHANNEL             0
#define CanRxBEM_02_HW_OBJ                   10
#define CanRxBEM_02_HW_CHANNEL               0
#define CanRxBCM1_02_HW_OBJ                  11
#define CanRxBCM1_02_HW_CHANNEL              0
#define CanRxGW_Mmi_07_PAG_HW_OBJ            12
#define CanRxGW_Mmi_07_PAG_HW_CHANNEL        0
#define CanRxGW_Mmi_06_PAG_HW_OBJ            13
#define CanRxGW_Mmi_06_PAG_HW_CHANNEL        0
#define CanRxHVLM_05_HW_OBJ                  14
#define CanRxHVLM_05_HW_CHANNEL              0
#define CanRxKombi_14_PAG_HW_OBJ             15
#define CanRxKombi_14_PAG_HW_CHANNEL         0
#define CanRxGW_Mmi_10_PAG_HW_OBJ            16
#define CanRxGW_Mmi_10_PAG_HW_CHANNEL        0
#define CanRxGateway_01_HW_OBJ               17
#define CanRxGateway_01_HW_CHANNEL           0
#define CanRxKlemmen_Status_01_HW_OBJ        18
#define CanRxKlemmen_Status_01_HW_CHANNEL    0
#define CanRxKombi_17_PAG_HW_OBJ             19
#define CanRxKombi_17_PAG_HW_CHANNEL         0
#define CanRxKombi_16_PAG_HW_OBJ             20
#define CanRxKombi_16_PAG_HW_CHANNEL         0
#define CanRxGW_Mmi_01_PAG_HW_OBJ            21
#define CanRxGW_Mmi_01_PAG_HW_CHANNEL        0
#define CanRxGW_Mmi_05_PAG_HW_OBJ            22
#define CanRxGW_Mmi_05_PAG_HW_CHANNEL        0
#define CanRxBCM2_03_PAG_HW_OBJ              23
#define CanRxBCM2_03_PAG_HW_CHANNEL          0
#define CanRxGW_Mmi_04_PAG_HW_OBJ            24
#define CanRxGW_Mmi_04_PAG_HW_CHANNEL        0
#define CanRxKombi_10_PAG_HW_OBJ             25
#define CanRxKombi_10_PAG_HW_CHANNEL         0
#define CanRxKombi_13_PAG_HW_OBJ             26
#define CanRxKombi_13_PAG_HW_CHANNEL         0
#define CanRxESP_10_HW_OBJ                   27
#define CanRxESP_10_HW_CHANNEL               0
#define CanRxGetriebe_03_HW_OBJ              28
#define CanRxGetriebe_03_HW_CHANNEL          0
#define CanRxESP_02_HW_OBJ                   29
#define CanRxESP_02_HW_CHANNEL               0
#define CanRxESP_01_HW_OBJ                   30
#define CanRxESP_01_HW_CHANNEL               0
#define C_TX_NORMAL_HW_OBJ                   31
#define C_TX_NORMAL_HW_CHANNEL               0





/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 88863978
      #error "The magic number of the generated file <F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\inc\can_par.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 88863978
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __CAN_PAR_H__ */
