/* -----------------------------------------------------------------------------
  Filename:    ccl_cfg.h
  Description: Toolversion: 03.20.21.01.10.02.79.00.00.00
               
               Serial Number: CBD1100279
               Customer Info: Dr. Ing. h. c. F. Porsche AG
                              CBD / Porsche 2007+
                              Texas Instruments TMS470 / TMS470 R1SF55
                              Texas Instruments 4.6.6 Compiler
               
               
               Generator Fwk   : GENy 
               Generator Module: Ccl__core
               
               Configuration   : F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\cfg\Porsche_ADR.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470Cpu
                       Compiler:     TexasInstruments
                       Derivates:    TMS470R1
               
               Channel "Channel0":
                       Databasefile: F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\cfg\CAN_Matrix_Dashboard_2_11_0_X2_Release.dbc
                       Bussystem:    CAN
                       Manufacturer: Porsche AG
                       Node:         ADR_PAG_X2

  Generated by , 2012-02-15  08:51:07
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2010 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__CCL_CFG_H__)
#define __CCL_CFG_H__

#include "can_inc.h"
#include "il_inc.h"
#include "nmh.h"
#include "tpmc.h"
#include "desc.h"
#include "appdesc.h"
/***************************************************************************/ 
/* Version                  (abcd: Main version ab Sub Version cd )        */ 
/***************************************************************************/ 

#define CCL_DLL_VERSION  0x0201
#define CCL_DLL_BUGFIX_VERSION  0x00
#define CCL__COREDLL_VERSION                 0x0308
#define CCL__COREDLL_RELEASE_VERSION         0x11
/***************************************************************************/ 
/* Defines                                                                 */ 
/***************************************************************************/ 

#define C_ENABLE_CCL 

#define CCL_ENABLE_ERROR_HOOK  /* CclFatalError function is enabled */ 

#define CCL_ENABLE_DEBUG /* enables the debug mode and switches the assertions to on */ 

#define CCL_DISABLE_EMC_WAKEUP

#define CCL_DISABLE_WAKEUP_REG
#define CCL_ENABLE_INTERNAL_REQUEST
#define CCL_ENABLE_EXTERNAL_REQUEST
#define CCL_ENABLE_SLEEP_REPETITION

#define CCL_ENABLE_CANBEDDED_HANDLING
#define CCL_ENABLE_SCHEDULE_TASK
#define CCL_DISABLE_CONTAINER_TASK
#define CCL_ENABLE_STOP_MODE_ECU
#define CCL_DISABLE_POWER_DOWN_MODE_ECU
#define CCL_DISABLE_CUSTOMER_MODE_ECU
#define CCL_DISABLE_NET_STATE_RESTRICTION

#define CCL_DISABLE_TRCV_PORT_INT

#define CCL_ENABLE_SYSTEM_SHUTDOWN

#define CCL_ENABLE_SW_COM_STATE
#define CCL_ENABLE_NMSTARTUP_TIMER
#define CCL_ENABLE_NPM_SUPPORT
#define CCL_ENABLE_PREVENT_WAKEUP
#define CCL_ENABLE_EEPROM_PREVENT_WAKEUP
#define CCL_ENABLE_FORCE_SHUTDOWN
#define CCL_ENABLE_POSRES_FBL
#define kCclCanDescChannel 0
#define CCL_ENABLE_EXTENDED_NMINIT

#define kCclNrOfSystemChannels 1

#define kCclNrOfChannels 1  /* number of used channels */

#define kCclNrOfNetworks 1  /* number of used networks */ 

#define CCL_DISABLE_MULTIPLE_NODES  /* no multiple nodes */ 

#define CCL_ENABLE_BUSOFF_START

#define CCL_ENABLE_BUSOFF_END

#define CCL_ENABLE_BUSSTART

#define kCclNetReqTableSize 1  /* size of network request tabless */
#define kCclNumberOfUser 4
#define kCclCycleTime 10


/* Communication Handles */
#define CCL_KL_15    1
#define CCL_CSHDL    2
#define CCL_DiagReq_0    3
/***************************************************************************/ 
/* Macros                                                                  */ 
/***************************************************************************/ 


  /* *** Communication Request access macros *** */
#define CclSet_KL_15()                      CclRequestCommunication(CCL_KL_15)
#define CclSet_CSHDL()                      CclRequestCommunication(CCL_CSHDL)
#define CclSet_DiagReq_0()                          CclRequestCommunication(CCL_DiagReq_0)


  /* *** Release Communication access macros *** */
#define CclRel_KL_15()                      CclReleaseCommunication(CCL_KL_15)
#define CclRel_CSHDL()                      CclReleaseCommunication(CCL_CSHDL)
#define CclRel_DiagReq_0()                          CclReleaseCommunication(CCL_DiagReq_0)

extern void CclComStart(void);
extern void CclComStop(void);
extern void CclComWait(void);
extern void CclComResume(void);
extern void CCL_API_CALLBACK_TYPE ApplCclComStart(void);
extern void CCL_API_CALLBACK_TYPE ApplCclComStop(void);
extern void CCL_API_CALLBACK_TYPE ApplCclComWait(void);
extern void CCL_API_CALLBACK_TYPE ApplCclComResume(void);
extern void CclBusOffStart(void);
extern void CclBusOffEnd(void);
extern void CCL_API_CALLBACK_TYPE ApplCclBusOffStart(void);
extern void CCL_API_CALLBACK_TYPE ApplCclBusOffEnd(void);
extern void CCL_API_CALLBACK_TYPE ApplCclInit(void);
extern void CCL_API_CALLBACK_TYPE ApplCclInitTrcv(void);
extern void CCL_API_CALLBACK_TYPE ApplCclWakeUpTrcv(void);
extern void CCL_API_CALLBACK_TYPE ApplCclStandbyTrcv(void);
extern void CCL_API_CALLBACK_TYPE ApplCclSleepTrcv(void);
extern void CCL_API_CALL_TYPE CclScheduleTask(void);
/* Start of Nm_DirOsek_UserConfigFile */

#include "GIO.h"
#include "Port.h"
#include "spi.h"



/* End of Nm_DirOsek_UserConfigFile */

/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 88863978
      #error "The magic number of the generated file <F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\inc\ccl_cfg.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 88863978
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __CCL_CFG_H__ */
