/* -----------------------------------------------------------------------------
  Filename:    drv_par.h
  Description: Toolversion: 03.20.21.01.10.02.79.00.00.00
               
               Serial Number: CBD1100279
               Customer Info: Dr. Ing. h. c. F. Porsche AG
                              CBD / Porsche 2007+
                              Texas Instruments TMS470 / TMS470 R1SF55
                              Texas Instruments 4.6.6 Compiler
               
               
               Generator Fwk   : GENy 
               Generator Module: GenTool_GenyDriverBase
               
               Configuration   : F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\cfg\Porsche_ADR.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470Cpu
                       Compiler:     TexasInstruments
                       Derivates:    TMS470R1
               
               Channel "Channel0":
                       Databasefile: F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\cfg\CAN_Matrix_Dashboard_2_11_0_X2_Release.dbc
                       Bussystem:    CAN
                       Manufacturer: Porsche AG
                       Node:         ADR_PAG_X2

  Generated by , 2012-02-15  08:51:06
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2010 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__DRV_PAR_H__)
#define __DRV_PAR_H__

/* -----------------------------------------------------------------------------
    &&&~ Signal Structures
 ----------------------------------------------------------------------------- */

typedef struct _c_BCM1_02_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 7;
  vbittype LV_Standlicht_Anzeige : 1;
} _c_BCM1_02_msgType;
typedef struct _c_BCM2_03_PAG_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype BCM2_DWA_aktiv : 1;
  vbittype unused3 : 7;
} _c_BCM2_03_PAG_msgType;
typedef struct _c_BEM_02_msgTypeTag
{
  vbittype unused0 : 5;
  vbittype BEM_02_Abschaltstufen : 3;
} _c_BEM_02_msgType;
typedef struct _c_Diagnose_01_msgTypeTag
{
  vbittype DGN_Verlernzaehler : 8;
  vbittype KBI_Kilometerstand_0 : 8;
  vbittype KBI_Kilometerstand_1 : 8;
  vbittype UH_Jahr_0 : 4;
  vbittype KBI_Kilometerstand_2 : 4;
  vbittype UH_Tag_0 : 1;
  vbittype UH_Monat : 4;
  vbittype UH_Jahr_1 : 3;
  vbittype UH_Stunde_0 : 4;
  vbittype UH_Tag_1 : 4;
  vbittype UH_Sekunde_0 : 1;
  vbittype UH_Minute : 6;
  vbittype UH_Stunde_1 : 1;
  vbittype Uhrzeit_01_alt : 1;
  vbittype Kombi_02_alt : 1;
  vbittype unused0 : 1;
  vbittype UH_Sekunde_1 : 5;
} _c_Diagnose_01_msgType;
typedef struct _c_Einheiten_01_msgTypeTag
{
  vbittype KBI_Einheit_Uhrzeit : 1;
  vbittype KBI_Einheit_Temp : 1;
  vbittype KBI_MFA_v_Einheit_02 : 1;
  vbittype KBI_Einheit_Streckenanz : 1;
  vbittype KBI_Einheit_Druck : 2;
  vbittype KBI_Einheit_Datum : 2;
  vbittype unused0 : 1;
  vbittype KBI_Einheit_Verbrauch_elektr : 3;
  vbittype KBI_Einheit_Volumen : 2;
  vbittype KBI_Einheit_Verbrauch : 2;
  vbittype KBI_Einheit_Sprache : 8;
} _c_Einheiten_01_msgType;
typedef struct _c_ESP_01_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 7;
  vbittype ASR_Tastung_passiv : 1;
} _c_ESP_01_msgType;
typedef struct _c_ESP_02_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype ESP_Laengsbeschl_0 : 8;
  vbittype unused3 : 6;
  vbittype ESP_Laengsbeschl_1 : 2;
} _c_ESP_02_msgType;
typedef struct _c_ESP_10_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype ESP_QBit_Wegimpuls_HR : 1;
  vbittype ESP_QBit_Wegimpuls_HL : 1;
  vbittype ESP_QBit_Wegimpuls_VR : 1;
  vbittype ESP_QBit_Wegimpuls_VL : 1;
  vbittype unused1 : 4;
  vbittype ESP_Wegimpuls_VL_0 : 8;
  vbittype ESP_Wegimpuls_VR_0 : 6;
  vbittype ESP_Wegimpuls_VL_1 : 2;
  vbittype ESP_Wegimpuls_HL_0 : 4;
  vbittype ESP_Wegimpuls_VR_1 : 4;
  vbittype ESP_Wegimpuls_HR_0 : 2;
  vbittype ESP_Wegimpuls_HL_1 : 6;
  vbittype ESP_Wegimpuls_HR_1 : 8;
  vbittype ESP_HR_Fahrtrichtung : 2;
  vbittype ESP_HL_Fahrtrichtung : 2;
  vbittype ESP_VR_Fahrtrichtung : 2;
  vbittype ESP_VL_Fahrtrichtung : 2;
} _c_ESP_10_msgType;
typedef struct _c_Gateway_01_msgTypeTag
{
  vbittype ESP_01_alt : 1;
  vbittype unused0 : 1;
  vbittype EPB_01_alt : 1;
  vbittype unused1 : 3;
  vbittype Getriebe_03_alt : 1;
  vbittype Motor_03_alt : 1;
  vbittype ESP_v_Signal_0 : 8;
  vbittype ESP_v_Signal_1 : 8;
  vbittype unused2 : 4;
  vbittype EPB_Status : 2;
  vbittype unused3 : 2;
  vbittype unused4 : 4;
  vbittype GE_Waehlhebel : 4;
  vbittype MO_Drehzahl_01_0 : 8;
  vbittype MO_Drehzahl_01_1 : 8;
} _c_Gateway_01_msgType;
typedef struct _c_Gateway_03_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype Motor_06_alt : 1;
  vbittype unused1 : 6;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype unused7 : 2;
  vbittype MO_HYB_Fahrbereitschaft : 1;
  vbittype unused8 : 5;
} _c_Gateway_03_msgType;
typedef struct _c_Getriebe_03_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 4;
  vbittype GE_Zielgang : 4;
} _c_Getriebe_03_msgType;
typedef struct _c_GW_Mmi_01_PAG_msgTypeTag
{
  vbittype unused0 : 7;
  vbittype BCM1_Rueckfahrlicht_Schalter : 1;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype unused7 : 2;
  vbittype F_BCM1_01_Mmi : 1;
  vbittype unused8 : 5;
} _c_GW_Mmi_01_PAG_msgType;
typedef struct _c_GW_Mmi_04_PAG_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 2;
  vbittype MO_HYB_VM_aktiv : 1;
  vbittype unused4 : 1;
  vbittype DR_Daempferreg_Texte : 4;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype unused7 : 5;
  vbittype F_Daempfer_01_FR_Mmi : 1;
  vbittype unused8 : 2;
  vbittype unused9 : 1;
  vbittype F_Motor_Hybrid_01_Mmi : 1;
  vbittype unused10 : 6;
} _c_GW_Mmi_04_PAG_msgType;
typedef struct _c_GW_Mmi_05_PAG_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype ESP_Querbeschleunigung_Roh_0 : 8;
  vbittype unused2 : 1;
  vbittype ESP_Querbeschleunigung_Offset : 6;
  vbittype ESP_Querbeschleunigung_Roh_1 : 1;
  vbittype unused3 : 2;
  vbittype ESP_Off_Lampe : 1;
  vbittype unused4 : 5;
  vbittype unused5 : 6;
  vbittype ESP_Stillstandsflag : 1;
  vbittype unused6 : 1;
  vbittype unused7 : 8;
  vbittype unused8 : 2;
  vbittype F_ESP_13_Mmi : 1;
  vbittype unused9 : 1;
  vbittype F_ESP_02_Mmi : 1;
  vbittype F_ESP_04_Mmi : 1;
  vbittype unused10 : 2;
} _c_GW_Mmi_05_PAG_msgType;
typedef struct _c_GW_Mmi_06_PAG_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype LWI_Lenkradwinkel_0 : 8;
  vbittype unused5 : 2;
  vbittype LWI_VZ_Lenkradwinkel : 1;
  vbittype LWI_Lenkradwinkel_1 : 5;
  vbittype unused6 : 7;
  vbittype F_LWI_01_Mmi : 1;
} _c_GW_Mmi_06_PAG_msgType;
typedef struct _c_GW_Mmi_07_PAG_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 7;
  vbittype FT_Tuer_geoeffnet : 1;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype unused7 : 7;
  vbittype F_TSG_FT_01_Mmi : 1;
} _c_GW_Mmi_07_PAG_msgType;
typedef struct _c_GW_Mmi_10_PAG_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype ZV_verriegelt_extern_ist : 1;
  vbittype unused1 : 6;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype unused7 : 8;
  vbittype unused8 : 7;
  vbittype F_BCM2_02_Mmi : 1;
} _c_GW_Mmi_10_PAG_msgType;
typedef struct _c_HVLM_05_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype HVLM_Restladezeit_HV_Bat_02_0 : 4;
  vbittype unused1 : 4;
  vbittype unused2 : 1;
  vbittype HVLM_Lademodus_HV_Bat : 2;
  vbittype HVLM_Restladezeit_HV_Bat_02_1 : 5;
  vbittype unused3 : 2;
  vbittype HVLM_Bat_laden_aktiv : 1;
  vbittype unused4 : 5;
  vbittype unused5 : 8;
  vbittype unused6 : 4;
  vbittype HVLM_Ladeart : 2;
  vbittype unused7 : 2;
  vbittype unused8 : 2;
  vbittype HVLM_Stecker_Status : 2;
  vbittype unused9 : 4;
} _c_HVLM_05_msgType;
typedef struct _c_ISO_Info_El_Resp_msgTypeTag
{
  vbittype ISO_Info_El_Resp_Data_0 : 8;
  vbittype ISO_Info_El_Resp_Data_1 : 8;
  vbittype ISO_Info_El_Resp_Data_2 : 8;
  vbittype ISO_Info_El_Resp_Data_3 : 8;
  vbittype ISO_Info_El_Resp_Data_4 : 8;
  vbittype ISO_Info_El_Resp_Data_5 : 8;
  vbittype ISO_Info_El_Resp_Data_6 : 8;
  vbittype ISO_Info_El_Resp_Data_7 : 8;
} _c_ISO_Info_El_Resp_msgType;
typedef struct _c_Klemmen_Status_01_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 6;
  vbittype ZAS_Kl_15 : 1;
  vbittype ZAS_Kl_S : 1;
} _c_Klemmen_Status_01_msgType;
typedef struct _c_Klima_02_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype KL_Geblaese_Status : 4;
  vbittype unused4 : 4;
} _c_Klima_02_msgType;
typedef struct _c_Klima_03_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype KL_Sonnenintensitaet : 8;
} _c_Klima_03_msgType;
typedef struct _c_Kombi_02_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype KBI_Aussen_Temp_gef : 8;
} _c_Kombi_02_msgType;
typedef struct _c_Kombi_09_PAG_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype KBI_SDruck_HA_komfort_0 : 2;
  vbittype KBI_SDruck_VA_komfort : 6;
  vbittype KBI_SDruck_VA_vmax_0 : 4;
  vbittype KBI_SDruck_HA_komfort_1 : 4;
  vbittype KBI_SDruck_HA_vmax : 6;
  vbittype KBI_SDruck_VA_vmax_1 : 2;
  vbittype unused2 : 8;
  vbittype KBI_KomfortDruck_V_Warnschwelle : 2;
  vbittype ActiveSafe_HMI_FStatus : 1;
  vbittype ActiveSafe_HMI_Vorwarnung : 1;
  vbittype KBI_RDK_Beladung_neu : 1;
  vbittype KBI_RDK_DDAnz_akt : 1;
  vbittype KBI_RDK_Solldruck_neu : 1;
  vbittype KBI_KomfortDruck : 1;
  vbittype unused3 : 6;
  vbittype KBI_RS_Druck_uebernehmen : 1;
  vbittype KBI_Rundstreckenmodus : 1;
} _c_Kombi_09_PAG_msgType;
typedef struct _c_Kombi_10_PAG_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype KBI_V_Anz_0 : 8;
  vbittype unused3 : 1;
  vbittype KBI_V_Anz_1 : 7;
} _c_Kombi_10_PAG_msgType;
typedef struct _c_Kombi_11_PAG_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype KBI_Fotosensor : 8;
  vbittype unused3 : 8;
  vbittype KBI_KL58s : 8;
} _c_Kombi_11_PAG_msgType;
typedef struct _c_Kombi_13_PAG_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype KBI_Reichw_anz_0 : 4;
  vbittype unused3 : 4;
  vbittype KBI_Reichw_anz_1 : 8;
  vbittype KBI_E_Restreichweite_0 : 8;
  vbittype unused4 : 4;
  vbittype KBI_E_Restreichweite_1 : 4;
} _c_Kombi_13_PAG_msgType;
typedef struct _c_Kombi_14_PAG_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype KBI_Trip_Reset_Std_0 : 2;
  vbittype KBI_Trip_Reset_Min : 6;
  vbittype unused6 : 5;
  vbittype KBI_Trip_Reset_Std_1 : 3;
} _c_Kombi_14_PAG_msgType;
typedef struct _c_Kombi_16_PAG_msgTypeTag
{
  vbittype KBI_Trip_DS_Verbr_1_0 : 8;
  vbittype KBI_Trip_Min_1_0 : 2;
  vbittype KBI_Trip_DS_Verbr_1_1 : 6;
  vbittype KBI_Trip_Std_1_0 : 4;
  vbittype KBI_Trip_Min_1_1 : 4;
  vbittype KBI_Trip_Std_1_1 : 8;
  vbittype KBI_Trip_Strecke_1_0 : 5;
  vbittype KBI_Trip_Std_1_2 : 3;
  vbittype KBI_Trip_Strecke_1_1 : 8;
  vbittype KBI_Trip_DS_V_1_0 : 4;
  vbittype KBI_Trip_Strecke_1_2 : 4;
  vbittype unused0 : 3;
  vbittype KBI_Trip_DS_V_1_1 : 5;
} _c_Kombi_16_PAG_msgType;
typedef struct _c_Kombi_17_PAG_msgTypeTag
{
  vbittype KBI_Trip_DS_Verbr_2_0 : 8;
  vbittype KBI_Trip_Min_2_0 : 2;
  vbittype KBI_Trip_DS_Verbr_2_1 : 6;
  vbittype KBI_Trip_Std_2_0 : 4;
  vbittype KBI_Trip_Min_2_1 : 4;
  vbittype KBI_Trip_Std_2_1 : 8;
  vbittype KBI_Trip_Strecke_2_0 : 5;
  vbittype KBI_Trip_Std_2_2 : 3;
  vbittype KBI_Trip_Strecke_2_1 : 8;
  vbittype KBI_Trip_DS_V_2_0 : 4;
  vbittype KBI_Trip_Strecke_2_2 : 4;
  vbittype unused0 : 3;
  vbittype KBI_Trip_DS_V_2_1 : 5;
} _c_Kombi_17_PAG_msgType;
typedef struct _c_Kombi_EV_01_PAG_msgTypeTag
{
  vbittype KBI_Trip_E_Verbr_fortl_0 : 8;
  vbittype KBI_Trip_E_Verbr_seit_0 : 2;
  vbittype KBI_Trip_E_Verbr_fortl_1 : 6;
  vbittype KBI_Trip_E_Verbr_seit_1 : 8;
  vbittype KBI_Trip_E_Strecke_fortl_0 : 4;
  vbittype KBI_Trip_E_Verbr_seit_2 : 4;
  vbittype KBI_Trip_E_Strecke_fortl_1 : 8;
  vbittype KBI_Trip_E_Strecke_seit_0 : 3;
  vbittype KBI_Trip_E_Strecke_fortl_2 : 5;
  vbittype KBI_Trip_E_Strecke_seit_1 : 8;
  vbittype unused0 : 2;
  vbittype KBI_Trip_E_Strecke_seit_2 : 6;
} _c_Kombi_EV_01_PAG_msgType;
typedef struct _c_Kombi_18_PAG_msgTypeTag
{
  vbittype cunused0 : 5;
  vbittype KBI_Set_Timer_MUX : 3;
  vbittype cunused11 : 6;
  vbittype cunused7 : 2;
  vbittype cunused16 : 4;
  vbittype cunused12 : 4;
  vbittype cunused35 : 1;
  vbittype cunused28 : 1;
  vbittype cunused24 : 5;
  vbittype cunused23 : 1;
  vbittype cunused67 : 1;
  vbittype cunused63 : 1;
  vbittype cunused59 : 1;
  vbittype cunused52 : 1;
  vbittype cunused48 : 1;
  vbittype cunused47 : 1;
  vbittype cunused43 : 1;
  vbittype cunused39 : 1;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
} _c_Kombi_18_PAG_msgType;
typedef struct _c_Kombi_18_PAG_m1_msgTypeTag
{
  vbittype KBI_Set_Timer_1_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype KBI_Set_Timer_1_Minute : 6;
  vbittype KBI_Set_Timer_1_Jahr_1 : 2;
  vbittype KBI_Set_Timer_1_Stunde_0 : 4;
  vbittype KBI_Set_Timer_1_Monat : 4;
  vbittype KBI_Set_Timer_1_Vorklima : 1;
  vbittype KBI_Set_Timer_1_Laden : 1;
  vbittype KBI_Set_Timer_1_Tag : 5;
  vbittype KBI_Set_Timer_1_Stunde_1 : 1;
  vbittype KBI_Set_Timer_1_Zyklus_WH : 1;
  vbittype KBI_Set_Timer_1_Zyklus_So : 1;
  vbittype KBI_Set_Timer_1_Zyklus_Sa : 1;
  vbittype KBI_Set_Timer_1_Zyklus_Fr : 1;
  vbittype KBI_Set_Timer_1_Zyklus_Do : 1;
  vbittype KBI_Set_Timer_1_Zyklus_Mi : 1;
  vbittype KBI_Set_Timer_1_Zyklus_Di : 1;
  vbittype KBI_Set_Timer_1_Zyklus_Mo : 1;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
} _c_Kombi_18_PAG_m1_msgType;
typedef struct _c_Kombi_18_PAG_m2_msgTypeTag
{
  vbittype KBI_Set_Timer_2_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype KBI_Set_Timer_2_Minute : 6;
  vbittype KBI_Set_Timer_2_Jahr_1 : 2;
  vbittype KBI_Set_Timer_2_Stunde_0 : 4;
  vbittype KBI_Set_Timer_2_Monat : 4;
  vbittype KBI_Set_Timer_2_Vorklima : 1;
  vbittype KBI_Set_Timer_2_Laden : 1;
  vbittype KBI_Set_Timer_2_Tag : 5;
  vbittype KBI_Set_Timer_2_Stunde_1 : 1;
  vbittype KBI_Set_Timer_2_Zyklus_WH : 1;
  vbittype KBI_Set_Timer_2_Zyklus_So : 1;
  vbittype KBI_Set_Timer_2_Zyklus_Sa : 1;
  vbittype KBI_Set_Timer_2_Zyklus_Fr : 1;
  vbittype KBI_Set_Timer_2_Zyklus_Do : 1;
  vbittype KBI_Set_Timer_2_Zyklus_Mi : 1;
  vbittype KBI_Set_Timer_2_Zyklus_Di : 1;
  vbittype KBI_Set_Timer_2_Zyklus_Mo : 1;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
} _c_Kombi_18_PAG_m2_msgType;
typedef struct _c_Kombi_18_PAG_m3_msgTypeTag
{
  vbittype KBI_Set_Timer_3_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype KBI_Set_Timer_3_Minute : 6;
  vbittype KBI_Set_Timer_3_Jahr_1 : 2;
  vbittype KBI_Set_Timer_3_Stunde_0 : 4;
  vbittype KBI_Set_Timer_3_Monat : 4;
  vbittype KBI_Set_Timer_3_Vorklima : 1;
  vbittype KBI_Set_Timer_3_Laden : 1;
  vbittype KBI_Set_Timer_3_Tag : 5;
  vbittype KBI_Set_Timer_3_Stunde_1 : 1;
  vbittype KBI_Set_Timer_3_Zyklus_WH : 1;
  vbittype KBI_Set_Timer_3_Zyklus_So : 1;
  vbittype KBI_Set_Timer_3_Zyklus_Sa : 1;
  vbittype KBI_Set_Timer_3_Zyklus_Fr : 1;
  vbittype KBI_Set_Timer_3_Zyklus_Do : 1;
  vbittype KBI_Set_Timer_3_Zyklus_Mi : 1;
  vbittype KBI_Set_Timer_3_Zyklus_Di : 1;
  vbittype KBI_Set_Timer_3_Zyklus_Mo : 1;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
} _c_Kombi_18_PAG_m3_msgType;
typedef struct _c_Kombi_18_PAG_m4_msgTypeTag
{
  vbittype KBI_Set_Timer_4_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype KBI_Set_Timer_4_Minute : 6;
  vbittype KBI_Set_Timer_4_Jahr_1 : 2;
  vbittype KBI_Set_Timer_4_Stunde_0 : 4;
  vbittype KBI_Set_Timer_4_Monat : 4;
  vbittype KBI_Set_Timer_4_Vorklima : 1;
  vbittype KBI_Set_Timer_4_Laden : 1;
  vbittype KBI_Set_Timer_4_Tag : 5;
  vbittype KBI_Set_Timer_4_Stunde_1 : 1;
  vbittype KBI_Set_Timer_4_Zyklus_WH : 1;
  vbittype KBI_Set_Timer_4_Zyklus_So : 1;
  vbittype KBI_Set_Timer_4_Zyklus_Sa : 1;
  vbittype KBI_Set_Timer_4_Zyklus_Fr : 1;
  vbittype KBI_Set_Timer_4_Zyklus_Do : 1;
  vbittype KBI_Set_Timer_4_Zyklus_Mi : 1;
  vbittype KBI_Set_Timer_4_Zyklus_Di : 1;
  vbittype KBI_Set_Timer_4_Zyklus_Mo : 1;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
} _c_Kombi_18_PAG_m4_msgType;
typedef struct _c_LAD_02_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype LAD_Fehlerzustand : 1;
  vbittype LAD_Warnzustand : 1;
  vbittype unused7 : 6;
} _c_LAD_02_msgType;
typedef struct _c_Lift_01_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 1;
  vbittype Lift_Status : 3;
  vbittype unused2 : 4;
} _c_Lift_01_msgType;
typedef struct _c_Mem_Kombi_01_PAG_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype KBI_FLA_GLW_Aktiv : 1;
  vbittype KBI_Schneekettenmodus_Aktiv : 1;
  vbittype KBI_Einstiegshilfe_aktiv : 1;
  vbittype KBI_FULL_AFS_Tourist : 1;
  vbittype KBI_Schaltpkt_Anz_ein : 1;
  vbittype KBI_Aussenspiegel_einklapp_auto : 1;
  vbittype KBI_Aussenspiegel_absenken_auto : 1;
  vbittype KBI_RS_d_akt : 1;
  vbittype KBI_Dimmung_OriLicht : 7;
  vbittype KBI_Heckrollo_b_R : 1;
  vbittype KBI_Auto_Umluft : 1;
  vbittype KBI_Erw_BelueftFeld : 1;
  vbittype KBI_Nachleucht_IL : 5;
  vbittype KBI_Heckw_b_R : 2;
  vbittype KBI_TFL_akt : 1;
  vbittype KBI_Nachleucht : 5;
  vbittype KBI_Carjack : 2;
  vbittype KBI_Tuerentr_T : 1;
  vbittype KBI_WV_Entr : 5;
  vbittype KBI_LDW_aktiv : 1;
  vbittype KBI_Jokerkey_Hupe_Aktiv : 1;
  vbittype KBI_Automem_Inaktiv : 1;
  vbittype unused1 : 1;
  vbittype KBI_WV_Entr_Kof : 4;
  vbittype KBI_Mittenduesentemp : 3;
  vbittype KBI_Klimastyles : 2;
  vbittype unused2 : 1;
  vbittype KBI_Steigerung_Luftmenge_Fond : 1;
  vbittype KBI_PTC_Zuheizer : 1;
  vbittype KBI_Innenlicht_per_Tuerkontakt : 1;
  vbittype KBI_Dimmung_AmbLicht : 7;
} _c_Mem_Kombi_01_PAG_msgType;
typedef struct _c_MFL_Tasten_Kon_01_msgTypeTag
{
  vbittype MFL_Tastencode_1 : 8;
  vbittype MFL_Tastencode_2 : 8;
  vbittype MFL_Eventcode_2 : 4;
  vbittype MFL_Eventcode_1 : 4;
  vbittype MFL_Variante : 4;
  vbittype MFL_Marke : 4;
} _c_MFL_Tasten_Kon_01_msgType;
typedef struct _c_Motor_06_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype MO_HYB_Text_4 : 1;
  vbittype unused3 : 7;
} _c_Motor_06_msgType;
typedef struct _c_Motor_06_m0_msgTypeTag
{
  vbittype cunused0 : 7;
  vbittype unused0 : 1;
} _c_Motor_06_m0_msgType;
typedef struct _c_Motor_06_m1_msgTypeTag
{
  vbittype cunused0 : 7;
  vbittype unused0 : 1;
} _c_Motor_06_m1_msgType;
typedef struct _c_Motor_15_PAG_msgTypeTag
{
  vbittype Enrgfluss_State : 8;
  vbittype Ladezustand : 8;
} _c_Motor_15_PAG_msgType;
typedef struct _c_NMH_CDR_PCM_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype NM_CDR_PCM_Car_WakeUp : 1;
  vbittype unused1 : 2;
  vbittype NM_CDR_PCM_Normal_Mode_2 : 1;
  vbittype NM_CDR_PCM_Normal_Mode_1 : 1;
  vbittype NM_CDR_PCM_Start_2 : 1;
  vbittype NM_CDR_PCM_Start_1 : 1;
  vbittype NM_CDR_PCM_Fkt_WakeUp : 3;
  vbittype NM_CDR_PCM_Per_WakeUp : 5;
  vbittype unused2 : 5;
  vbittype NM_CDR_PCM_MindestAktivZeit : 1;
  vbittype NM_CDR_PCM_Diagnose : 1;
  vbittype NM_CDR_PCM_Klemme_15 : 1;
  vbittype unused3 : 8;
  vbittype NM_CDR_PCM_Busfehler : 1;
  vbittype NM_CDR_PCM_Abschaltstufe_aktiv : 1;
  vbittype NM_CDR_PCM_Transport_Mode : 1;
  vbittype NM_CDR_PCM_Mute_Mode : 1;
  vbittype NM_CDR_PCM_KompSchutz : 1;
  vbittype NM_CDR_PCM_CAN_Diag_deaktiv : 1;
  vbittype NM_CDR_PCM_TimeOut_Fehler : 1;
  vbittype NMH_CDR_PCM_Signalfehler : 1;
  vbittype unused4 : 8;
  vbittype unused5 : 6;
  vbittype NMH_CDR_PCM_Subsystemaktiv : 1;
  vbittype NMH_CDR_PCM_Lokalaktiv : 1;
} _c_NMH_CDR_PCM_msgType;
typedef struct _c_NPM_01_PAG_msgTypeTag
{
  vbittype NPM_PreventWakeup : 4;
  vbittype NPM_ForceShutdown : 4;
  vbittype unused0 : 7;
  vbittype NPM_directAdressing : 1;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 6;
  vbittype NPM_FS_HU : 1;
  vbittype unused4 : 1;
  vbittype unused5 : 8;
  vbittype unused6 : 8;
  vbittype unused7 : 3;
  vbittype NPM_PrWu_HU : 1;
  vbittype unused8 : 4;
} _c_NPM_01_PAG_msgType;
typedef struct _c_PCM_02_PAG_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype PCM_FOT_Temp : 7;
  vbittype unused1 : 2;
  vbittype PCM_Rundenfarbe : 2;
  vbittype PCM_RFK_manuell : 2;
  vbittype PCM_HMI_mode : 2;
  vbittype PCM_Limit_Einheit : 1;
  vbittype PCM_Limit_Info : 7;
  vbittype PCM_Rundenfortschritt : 8;
  vbittype PCM_Kompass_0 : 8;
  vbittype unused2 : 1;
  vbittype PCM_HMI_Mode_TopView : 5;
  vbittype PCM_Elev_Einheit : 1;
  vbittype PCM_Kompass_1 : 1;
  vbittype PCM_Sat : 4;
  vbittype PCM_Street_class : 4;
  vbittype PCM_Entfernung_Kurve : 8;
} _c_PCM_02_PAG_msgType;
typedef struct _c_PCM_04_PAG_msgTypeTag
{
  vbittype GPS_N_Grad_0 : 8;
  vbittype GPS_N_Grad_1 : 8;
  vbittype GPS_N_Grad_2 : 8;
  vbittype GPS_E_Grad_0 : 7;
  vbittype GPS_N_Grad_3 : 1;
  vbittype GPS_E_Grad_1 : 8;
  vbittype GPS_E_Grad_2 : 8;
  vbittype GPS_elev_0 : 5;
  vbittype GPS_E_Grad_3 : 3;
  vbittype GPS_elev_1 : 8;
} _c_PCM_04_PAG_msgType;
typedef struct _c_PCM_CDR_01_PAG_msgTypeTag
{
  vbittype PCM_Min_0 : 3;
  vbittype PCM_Std : 5;
  vbittype PCM_Sek_0 : 5;
  vbittype PCM_Min_1 : 3;
  vbittype PCM_Uebern : 1;
  vbittype PCM_Zeitzone_Vorzeichen : 1;
  vbittype PCM_Zeitzone : 5;
  vbittype PCM_Sek_1 : 1;
  vbittype PCM_Mon_0 : 3;
  vbittype PCM_Tag : 5;
  vbittype PCM_JJ : 7;
  vbittype PCM_Mon_1 : 1;
  vbittype unused0 : 5;
  vbittype PCM_Reset_Trip_2 : 1;
  vbittype PCM_Reset_Trip_1 : 1;
  vbittype PCM_Sommerzeit : 1;
  vbittype HU_Fotosensor_0 : 8;
  vbittype HU_KD_Fehler : 1;
  vbittype HU_Topview_on_Anf : 1;
  vbittype HU_PCMCDR : 1;
  vbittype PCM_KD_Fehler_TV : 1;
  vbittype PCM_KD_Fehler_AMP : 1;
  vbittype PCM_SVB_TV : 1;
  vbittype HU_SVB_AMP : 1;
  vbittype HU_Fotosensor_1 : 1;
} _c_PCM_CDR_01_PAG_msgType;
typedef struct _c_RDK_02_PAG_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 5;
  vbittype RDK_angelernt : 1;
  vbittype unused2 : 2;
} _c_RDK_02_PAG_msgType;
typedef struct _c_Systeminfo_01_msgTypeTag
{
  vbittype unused0 : 1;
  vbittype SI_Fahrwerk_Sleep : 1;
  vbittype SI_CAN_Extended_Sleep : 1;
  vbittype unused1 : 1;
  vbittype SI_CAN_Antrieb_Sleep : 1;
  vbittype SI_CAN_Dashboard_Sleep : 1;
  vbittype SI_CAN_Komfort_Sleep : 1;
  vbittype unused2 : 1;
  vbittype unused3 : 4;
  vbittype SI_NWDF_gueltig : 1;
  vbittype SI_NWDF : 1;
  vbittype SI_T_Mode : 1;
  vbittype unused4 : 1;
} _c_Systeminfo_01_msgType;
typedef struct _c_VIN_01_msgTypeTag
{
  vbittype unused0 : 6;
  vbittype VIN_01_MUX : 2;
  vbittype cunused0 : 8;
  vbittype cunused2 : 8;
  vbittype cunused4 : 8;
  vbittype cunused6 : 8;
  vbittype cunused10 : 8;
  vbittype cunused11 : 8;
  vbittype cunused14 : 8;
} _c_VIN_01_msgType;
typedef struct _c_VIN_01_m0_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype cunused0 : 8;
  vbittype cunused1 : 8;
  vbittype cunused2 : 8;
  vbittype cunused3 : 8;
  vbittype VIN_1 : 8;
  vbittype VIN_2 : 8;
  vbittype VIN_3 : 8;
} _c_VIN_01_m0_msgType;
typedef struct _c_VIN_01_m1_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype VIN_4 : 8;
  vbittype VIN_5 : 8;
  vbittype VIN_6 : 8;
  vbittype VIN_7 : 8;
  vbittype VIN_8 : 8;
  vbittype VIN_9 : 8;
  vbittype VIN_10 : 8;
} _c_VIN_01_m1_msgType;
typedef struct _c_VIN_01_m2_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype VIN_11 : 8;
  vbittype VIN_12 : 8;
  vbittype VIN_13 : 8;
  vbittype VIN_14 : 8;
  vbittype VIN_15 : 8;
  vbittype VIN_16 : 8;
  vbittype VIN_17 : 8;
} _c_VIN_01_m2_msgType;
typedef struct _c_ADR_01_PAG_msgTypeTag
{
  vbittype Adr_Tuner_LED_an : 1;
  vbittype Adr_Media_LED_an : 1;
  vbittype Adr_Phone_LED_an : 1;
  vbittype Adr_AC_Menue_LED_an : 1;
  vbittype Adr_T_LVT_U : 1;
  vbittype Adr_T_LVT_M : 1;
  vbittype Adr_T_LVT_O : 1;
  vbittype Adr_Clima_Mono : 1;
  vbittype Adr_Pos_En : 1;
  vbittype Adr_Alive_Cnt : 4;
  vbittype Adr_Navi_LED_an : 1;
  vbittype Adr_Info_LED_an : 1;
  vbittype Adr_Car_LED_an : 1;
  vbittype unused0 : 3;
  vbittype Adr_Active_Character_Page : 4;
  vbittype Adr_Display_Status : 1;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype Adr_Chr_Mode : 8;
  vbittype Adr_Gst_Mode_0 : 8;
  vbittype Adr_Gst_Mode_1 : 8;
} _c_ADR_01_PAG_msgType;
typedef struct _c_ADR_02_PAG_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 1;
  vbittype Adr_Konfig_Datenfeld : 3;
  vbittype unused2 : 4;
  vbittype Adr_KI_BC_Rolle_Konfig : 8;
  vbittype Adr_Joker_Taste : 3;
  vbittype Adr_KI_BC_Rolle_Datenfeld : 5;
  vbittype Adr_KI_Helligkeit_0 : 1;
  vbittype Adr_KL58d : 7;
  vbittype Adr_Miko_Helligkeit_0 : 2;
  vbittype Adr_KI_Helligkeit_1 : 6;
  vbittype unused3 : 3;
  vbittype Adr_Miko_Helligkeit_1 : 5;
  vbittype unused4 : 8;
} _c_ADR_02_PAG_msgType;
typedef struct _c_Klima_13_PAG_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype KL_LVT_M_LED_an : 1;
  vbittype KL_LVT_O_LED_an : 1;
  vbittype unused1 : 6;
  vbittype unused2 : 7;
  vbittype KL_LVT_U_LED_an : 1;
} _c_Klima_13_PAG_msgType;
typedef struct _c_Miko_01_PAG_msgTypeTag
{
  vbittype Miko_T_Tuner : 1;
  vbittype Miko_T_Media : 1;
  vbittype Miko_T_Phone : 1;
  vbittype Miko_T_AC_Menue : 1;
  vbittype Miko_T_Source : 1;
  vbittype unused0 : 3;
  vbittype unused1 : 3;
  vbittype Miko_T_Navi : 1;
  vbittype Miko_T_Info : 1;
  vbittype Miko_T_Car : 1;
  vbittype Miko_T_Option : 1;
  vbittype Miko_T_Back : 1;
  vbittype Miko_Volume_press_0 : 1;
  vbittype Miko_Volume_dir : 1;
  vbittype Miko_Volume_Err : 1;
  vbittype Miko_Volume : 5;
  vbittype Miko_MMI_Err : 1;
  vbittype Miko_MMI_fast : 1;
  vbittype Miko_MMI : 5;
  vbittype Miko_Volume_press_1 : 1;
  vbittype unused2 : 7;
  vbittype Miko_MMI_dir : 1;
  vbittype unused3 : 1;
  vbittype Miko_ADR_UltralongPress : 1;
  vbittype Miko_ADR_Reset : 1;
  vbittype unused4 : 5;
} _c_Miko_01_PAG_msgType;
typedef struct _c_Motor_02_sek_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype Enrgfluss_State_BN : 2;
  vbittype unused1 : 6;
  vbittype unused2 : 6;
  vbittype Enrgfluss_State_sek : 2;
} _c_Motor_02_sek_msgType;
typedef struct _c_HVLM_07_PAG_msgTypeTag
{
  vbittype cunused0 : 5;
  vbittype HVLM_Status_Timer_MUX : 3;
  vbittype cunused14 : 6;
  vbittype cunused9 : 2;
  vbittype cunused28 : 4;
  vbittype cunused19 : 4;
  vbittype cunused42 : 1;
  vbittype cunused38 : 1;
  vbittype cunused33 : 5;
  vbittype cunused29 : 1;
  vbittype cunused74 : 1;
  vbittype cunused70 : 1;
  vbittype cunused66 : 1;
  vbittype cunused59 : 1;
  vbittype cunused55 : 1;
  vbittype cunused54 : 1;
  vbittype cunused50 : 1;
  vbittype cunused46 : 1;
} _c_HVLM_07_PAG_msgType;
typedef struct _c_HVLM_07_PAG_m1_msgTypeTag
{
  vbittype HVLM_Status_Timer_1_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype HVLM_Status_Timer_1_Minute : 6;
  vbittype HVLM_Status_Timer_1_Jahr_1 : 2;
  vbittype HVLM_Status_Timer_1_Stunde_0 : 4;
  vbittype HVLM_Status_Timer_1_Monat : 4;
  vbittype HVLM_Status_Timer_1_Vorklima : 1;
  vbittype HVLM_Status_Timer_1_Laden : 1;
  vbittype HVLM_Status_Timer_1_Tag : 5;
  vbittype HVLM_Status_Timer_1_Stunde_1 : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_WH : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_So : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_Sa : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_Fr : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_Do : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_Mi : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_Di : 1;
  vbittype HVLM_Status_Timer_1_Zyklus_Mo : 1;
} _c_HVLM_07_PAG_m1_msgType;
typedef struct _c_HVLM_07_PAG_m2_msgTypeTag
{
  vbittype HVLM_Status_Timer_2_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype HVLM_Status_Timer_2_Minute : 6;
  vbittype HVLM_Status_Timer_2_Jahr_1 : 2;
  vbittype HVLM_Status_Timer_2_Stunde_0 : 4;
  vbittype HVLM_Status_Timer_2_Monat : 4;
  vbittype HVLM_Status_Timer_2_Vorklima : 1;
  vbittype HVLM_Status_Timer_2_Laden : 1;
  vbittype HVLM_Status_Timer_2_Tag : 5;
  vbittype HVLM_Status_Timer_2_Stunde_1 : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_WH : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_So : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_Sa : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_Fr : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_Do : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_Mi : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_Di : 1;
  vbittype HVLM_Status_Timer_2_Zyklus_Mo : 1;
} _c_HVLM_07_PAG_m2_msgType;
typedef struct _c_HVLM_07_PAG_m3_msgTypeTag
{
  vbittype HVLM_Status_Timer_3_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype HVLM_Status_Timer_3_Minute : 6;
  vbittype HVLM_Status_Timer_3_Jahr_1 : 2;
  vbittype HVLM_Status_Timer_3_Stunde_0 : 4;
  vbittype HVLM_Status_Timer_3_Monat : 4;
  vbittype HVLM_Status_Timer_3_Vorklima : 1;
  vbittype HVLM_Status_Timer_3_Laden : 1;
  vbittype HVLM_Status_Timer_3_Tag : 5;
  vbittype HVLM_Status_Timer_3_Stunde_1 : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_WH : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_So : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_Sa : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_Fr : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_Do : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_Mi : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_Di : 1;
  vbittype HVLM_Status_Timer_3_Zyklus_Mo : 1;
} _c_HVLM_07_PAG_m3_msgType;
typedef struct _c_HVLM_07_PAG_m4_msgTypeTag
{
  vbittype HVLM_Status_Timer_4_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype HVLM_Status_Timer_4_Minute : 6;
  vbittype HVLM_Status_Timer_4_Jahr_1 : 2;
  vbittype HVLM_Status_Timer_4_Stunde_0 : 4;
  vbittype HVLM_Status_Timer_4_Monat : 4;
  vbittype HVLM_Status_Timer_4_Vorklima : 1;
  vbittype HVLM_Status_Timer_4_Laden : 1;
  vbittype HVLM_Status_Timer_4_Tag : 5;
  vbittype HVLM_Status_Timer_4_Stunde_1 : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_WH : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_So : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_Sa : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_Fr : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_Do : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_Mi : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_Di : 1;
  vbittype HVLM_Status_Timer_4_Zyklus_Mo : 1;
} _c_HVLM_07_PAG_m4_msgType;
typedef struct _c_HVLM_07_PAG_m7_msgTypeTag
{
  vbittype HVLM_Status_Timer_7_Jahr_0 : 5;
  vbittype unused0 : 3;
  vbittype HVLM_Status_Timer_7_Minute : 6;
  vbittype HVLM_Status_Timer_7_Jahr_1 : 2;
  vbittype HVLM_Status_Timer_7_Stunde_0 : 4;
  vbittype HVLM_Status_Timer_7_Monat : 4;
  vbittype unused1 : 2;
  vbittype HVLM_Status_Timer_7_Tag : 5;
  vbittype HVLM_Status_Timer_7_Stunde_1 : 1;
} _c_HVLM_07_PAG_m7_msgType;
typedef struct _c_Kombi_19_PAG_msgTypeTag
{
  vbittype KBI_Trip_E_Std_0 : 2;
  vbittype KBI_Trip_E_Min : 6;
  vbittype KBI_Trip_E_Std_1 : 8;
  vbittype unused0 : 3;
  vbittype KBI_Trip_E_Std_2 : 5;
} _c_Kombi_19_PAG_msgType;
typedef struct _c_Motor_K_02_msgTypeTag
{
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 1;
  vbittype MO_StartStopp_Motorstopp : 1;
  vbittype unused6 : 6;
} _c_Motor_K_02_msgType;


/* -----------------------------------------------------------------------------
    &&&~ Signal value names
 ----------------------------------------------------------------------------- */



/* -----------------------------------------------------------------------------
    &&&~ Message Unions
 ----------------------------------------------------------------------------- */

typedef union _c_BCM1_02_bufTag
{
  vuint8 _c[3];
  _c_BCM1_02_msgType BCM1_02;
} _c_BCM1_02_buf;
typedef union _c_BCM2_03_PAG_bufTag
{
  vuint8 _c[4];
  _c_BCM2_03_PAG_msgType BCM2_03_PAG;
} _c_BCM2_03_PAG_buf;
typedef union _c_BEM_02_bufTag
{
  vuint8 _c[1];
  _c_BEM_02_msgType BEM_02;
} _c_BEM_02_buf;
typedef union _c_Diagnose_01_bufTag
{
  vuint8 _c[8];
  _c_Diagnose_01_msgType Diagnose_01;
} _c_Diagnose_01_buf;
typedef union _c_Einheiten_01_bufTag
{
  vuint8 _c[3];
  _c_Einheiten_01_msgType Einheiten_01;
} _c_Einheiten_01_buf;
typedef union _c_ESP_01_bufTag
{
  vuint8 _c[7];
  _c_ESP_01_msgType ESP_01;
} _c_ESP_01_buf;
typedef union _c_ESP_02_bufTag
{
  vuint8 _c[5];
  _c_ESP_02_msgType ESP_02;
} _c_ESP_02_buf;
typedef union _c_ESP_10_bufTag
{
  vuint8 _c[8];
  _c_ESP_10_msgType ESP_10;
} _c_ESP_10_buf;
typedef union _c_Gateway_01_bufTag
{
  vuint8 _c[7];
  _c_Gateway_01_msgType Gateway_01;
} _c_Gateway_01_buf;
typedef union _c_Gateway_03_bufTag
{
  vuint8 _c[7];
  _c_Gateway_03_msgType Gateway_03;
} _c_Gateway_03_buf;
typedef union _c_Getriebe_03_bufTag
{
  vuint8 _c[4];
  _c_Getriebe_03_msgType Getriebe_03;
} _c_Getriebe_03_buf;
typedef union _c_GW_Mmi_01_PAG_bufTag
{
  vuint8 _c[8];
  _c_GW_Mmi_01_PAG_msgType GW_Mmi_01_PAG;
} _c_GW_Mmi_01_PAG_buf;
typedef union _c_GW_Mmi_04_PAG_bufTag
{
  vuint8 _c[8];
  _c_GW_Mmi_04_PAG_msgType GW_Mmi_04_PAG;
} _c_GW_Mmi_04_PAG_buf;
typedef union _c_GW_Mmi_05_PAG_bufTag
{
  vuint8 _c[8];
  _c_GW_Mmi_05_PAG_msgType GW_Mmi_05_PAG;
} _c_GW_Mmi_05_PAG_buf;
typedef union _c_GW_Mmi_06_PAG_bufTag
{
  vuint8 _c[8];
  _c_GW_Mmi_06_PAG_msgType GW_Mmi_06_PAG;
} _c_GW_Mmi_06_PAG_buf;
typedef union _c_GW_Mmi_07_PAG_bufTag
{
  vuint8 _c[8];
  _c_GW_Mmi_07_PAG_msgType GW_Mmi_07_PAG;
} _c_GW_Mmi_07_PAG_buf;
typedef union _c_GW_Mmi_10_PAG_bufTag
{
  vuint8 _c[8];
  _c_GW_Mmi_10_PAG_msgType GW_Mmi_10_PAG;
} _c_GW_Mmi_10_PAG_buf;
typedef union _c_HVLM_05_bufTag
{
  vuint8 _c[7];
  _c_HVLM_05_msgType HVLM_05;
} _c_HVLM_05_buf;
typedef union _c_ISO_Info_El_Resp_bufTag
{
  vuint8 _c[8];
  _c_ISO_Info_El_Resp_msgType ISO_Info_El_Resp;
} _c_ISO_Info_El_Resp_buf;
typedef union _c_Klemmen_Status_01_bufTag
{
  vuint8 _c[3];
  _c_Klemmen_Status_01_msgType Klemmen_Status_01;
} _c_Klemmen_Status_01_buf;
typedef union _c_Klima_02_bufTag
{
  vuint8 _c[5];
  _c_Klima_02_msgType Klima_02;
} _c_Klima_02_buf;
typedef union _c_Klima_03_bufTag
{
  vuint8 _c[6];
  _c_Klima_03_msgType Klima_03;
} _c_Klima_03_buf;
typedef union _c_Kombi_02_bufTag
{
  vuint8 _c[8];
  _c_Kombi_02_msgType Kombi_02;
} _c_Kombi_02_buf;
typedef union _c_Kombi_09_PAG_bufTag
{
  vuint8 _c[8];
  _c_Kombi_09_PAG_msgType Kombi_09_PAG;
} _c_Kombi_09_PAG_buf;
typedef union _c_Kombi_10_PAG_bufTag
{
  vuint8 _c[5];
  _c_Kombi_10_PAG_msgType Kombi_10_PAG;
} _c_Kombi_10_PAG_buf;
typedef union _c_Kombi_11_PAG_bufTag
{
  vuint8 _c[6];
  _c_Kombi_11_PAG_msgType Kombi_11_PAG;
} _c_Kombi_11_PAG_buf;
typedef union _c_Kombi_13_PAG_bufTag
{
  vuint8 _c[7];
  _c_Kombi_13_PAG_msgType Kombi_13_PAG;
} _c_Kombi_13_PAG_buf;
typedef union _c_Kombi_14_PAG_bufTag
{
  vuint8 _c[8];
  _c_Kombi_14_PAG_msgType Kombi_14_PAG;
} _c_Kombi_14_PAG_buf;
typedef union _c_Kombi_16_PAG_bufTag
{
  vuint8 _c[8];
  _c_Kombi_16_PAG_msgType Kombi_16_PAG;
} _c_Kombi_16_PAG_buf;
typedef union _c_Kombi_17_PAG_bufTag
{
  vuint8 _c[8];
  _c_Kombi_17_PAG_msgType Kombi_17_PAG;
} _c_Kombi_17_PAG_buf;
typedef union _c_Kombi_EV_01_PAG_bufTag
{
  vuint8 _c[8];
  _c_Kombi_EV_01_PAG_msgType Kombi_EV_01_PAG;
} _c_Kombi_EV_01_PAG_buf;
typedef union _c_Kombi_18_PAG_bufTag
{
  vuint8 _c[8];
  _c_Kombi_18_PAG_msgType Kombi_18_PAG;
} _c_Kombi_18_PAG_buf;
typedef union _c_Kombi_18_PAG_m1_bufTag
{
  vuint8 _c[5];
  _c_Kombi_18_PAG_m1_msgType Kombi_18_PAG_m1;
} _c_Kombi_18_PAG_m1_buf;
typedef union _c_Kombi_18_PAG_m2_bufTag
{
  vuint8 _c[5];
  _c_Kombi_18_PAG_m2_msgType Kombi_18_PAG_m2;
} _c_Kombi_18_PAG_m2_buf;
typedef union _c_Kombi_18_PAG_m3_bufTag
{
  vuint8 _c[5];
  _c_Kombi_18_PAG_m3_msgType Kombi_18_PAG_m3;
} _c_Kombi_18_PAG_m3_buf;
typedef union _c_Kombi_18_PAG_m4_bufTag
{
  vuint8 _c[5];
  _c_Kombi_18_PAG_m4_msgType Kombi_18_PAG_m4;
} _c_Kombi_18_PAG_m4_buf;
typedef union _c_LAD_02_bufTag
{
  vuint8 _c[8];
  _c_LAD_02_msgType LAD_02;
} _c_LAD_02_buf;
typedef union _c_Lift_01_bufTag
{
  vuint8 _c[2];
  _c_Lift_01_msgType Lift_01;
} _c_Lift_01_buf;
typedef union _c_Mem_Kombi_01_PAG_bufTag
{
  vuint8 _c[8];
  _c_Mem_Kombi_01_PAG_msgType Mem_Kombi_01_PAG;
} _c_Mem_Kombi_01_PAG_buf;
typedef union _c_MFL_Tasten_Kon_01_bufTag
{
  vuint8 _c[4];
  _c_MFL_Tasten_Kon_01_msgType MFL_Tasten_Kon_01;
} _c_MFL_Tasten_Kon_01_buf;
typedef union _c_Motor_06_bufTag
{
  vuint8 _c[4];
  _c_Motor_06_msgType Motor_06;
} _c_Motor_06_buf;
typedef union _c_Motor_15_PAG_bufTag
{
  vuint8 _c[2];
  _c_Motor_15_PAG_msgType Motor_15_PAG;
} _c_Motor_15_PAG_buf;
typedef union _c_NMH_CDR_PCM_bufTag
{
  vuint8 _c[7];
  _c_NMH_CDR_PCM_msgType NMH_CDR_PCM;
} _c_NMH_CDR_PCM_buf;
typedef union _c_NPM_01_PAG_bufTag
{
  vuint8 _c[8];
  _c_NPM_01_PAG_msgType NPM_01_PAG;
} _c_NPM_01_PAG_buf;
typedef union _c_PCM_02_PAG_bufTag
{
  vuint8 _c[8];
  _c_PCM_02_PAG_msgType PCM_02_PAG;
} _c_PCM_02_PAG_buf;
typedef union _c_PCM_04_PAG_bufTag
{
  vuint8 _c[8];
  _c_PCM_04_PAG_msgType PCM_04_PAG;
} _c_PCM_04_PAG_buf;
typedef union _c_PCM_CDR_01_PAG_bufTag
{
  vuint8 _c[8];
  _c_PCM_CDR_01_PAG_msgType PCM_CDR_01_PAG;
} _c_PCM_CDR_01_PAG_buf;
typedef union _c_RDK_02_PAG_bufTag
{
  vuint8 _c[2];
  _c_RDK_02_PAG_msgType RDK_02_PAG;
} _c_RDK_02_PAG_buf;
typedef union _c_Systeminfo_01_bufTag
{
  vuint8 _c[2];
  _c_Systeminfo_01_msgType Systeminfo_01;
} _c_Systeminfo_01_buf;
typedef union _c_VIN_01_bufTag
{
  vuint8 _c[8];
  _c_VIN_01_msgType VIN_01;
} _c_VIN_01_buf;
typedef union _c_VIN_01_m0_bufTag
{
  vuint8 _c[7];
  _c_VIN_01_m0_msgType VIN_01_m0;
} _c_VIN_01_m0_buf;
typedef union _c_VIN_01_m1_bufTag
{
  vuint8 _c[7];
  _c_VIN_01_m1_msgType VIN_01_m1;
} _c_VIN_01_m1_buf;
typedef union _c_VIN_01_m2_bufTag
{
  vuint8 _c[7];
  _c_VIN_01_m2_msgType VIN_01_m2;
} _c_VIN_01_m2_buf;
typedef union _c_ADR_01_PAG_bufTag
{
  vuint8 _c[8];
  _c_ADR_01_PAG_msgType ADR_01_PAG;
} _c_ADR_01_PAG_buf;
typedef union _c_ADR_02_PAG_bufTag
{
  vuint8 _c[8];
  _c_ADR_02_PAG_msgType ADR_02_PAG;
} _c_ADR_02_PAG_buf;
typedef union _c_Klima_13_PAG_bufTag
{
  vuint8 _c[3];
  _c_Klima_13_PAG_msgType Klima_13_PAG;
} _c_Klima_13_PAG_buf;
typedef union _c_Miko_01_PAG_bufTag
{
  vuint8 _c[6];
  _c_Miko_01_PAG_msgType Miko_01_PAG;
} _c_Miko_01_PAG_buf;
typedef union _c_Motor_02_sek_bufTag
{
  vuint8 _c[3];
  _c_Motor_02_sek_msgType Motor_02_sek;
} _c_Motor_02_sek_buf;
typedef union _c_HVLM_07_PAG_bufTag
{
  vuint8 _c[5];
  _c_HVLM_07_PAG_msgType HVLM_07_PAG;
} _c_HVLM_07_PAG_buf;
typedef union _c_HVLM_07_PAG_m1_bufTag
{
  vuint8 _c[5];
  _c_HVLM_07_PAG_m1_msgType HVLM_07_PAG_m1;
} _c_HVLM_07_PAG_m1_buf;
typedef union _c_HVLM_07_PAG_m2_bufTag
{
  vuint8 _c[5];
  _c_HVLM_07_PAG_m2_msgType HVLM_07_PAG_m2;
} _c_HVLM_07_PAG_m2_buf;
typedef union _c_HVLM_07_PAG_m3_bufTag
{
  vuint8 _c[5];
  _c_HVLM_07_PAG_m3_msgType HVLM_07_PAG_m3;
} _c_HVLM_07_PAG_m3_buf;
typedef union _c_HVLM_07_PAG_m4_bufTag
{
  vuint8 _c[5];
  _c_HVLM_07_PAG_m4_msgType HVLM_07_PAG_m4;
} _c_HVLM_07_PAG_m4_buf;
typedef union _c_HVLM_07_PAG_m7_bufTag
{
  vuint8 _c[4];
  _c_HVLM_07_PAG_m7_msgType HVLM_07_PAG_m7;
} _c_HVLM_07_PAG_m7_buf;
typedef union _c_Kombi_19_PAG_bufTag
{
  vuint8 _c[3];
  _c_Kombi_19_PAG_msgType Kombi_19_PAG;
} _c_Kombi_19_PAG_buf;
typedef union _c_Motor_K_02_bufTag
{
  vuint8 _c[6];
  _c_Motor_K_02_msgType Motor_K_02;
} _c_Motor_K_02_buf;


/* -----------------------------------------------------------------------------
    &&&~ Message Buffers
 ----------------------------------------------------------------------------- */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BCM1_02_buf V_MEMRAM2 BCM1_02;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BCM2_03_PAG_buf V_MEMRAM2 BCM2_03_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BEM_02_buf V_MEMRAM2 BEM_02;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Diagnose_01_buf V_MEMRAM2 Diagnose_01;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Einheiten_01_buf V_MEMRAM2 Einheiten_01;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_ESP_01_buf V_MEMRAM2 ESP_01;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_ESP_02_buf V_MEMRAM2 ESP_02;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_ESP_10_buf V_MEMRAM2 ESP_10;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Gateway_01_buf V_MEMRAM2 Gateway_01;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Gateway_03_buf V_MEMRAM2 Gateway_03;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Getriebe_03_buf V_MEMRAM2 Getriebe_03;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_GW_Mmi_01_PAG_buf V_MEMRAM2 GW_Mmi_01_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_GW_Mmi_04_PAG_buf V_MEMRAM2 GW_Mmi_04_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_GW_Mmi_05_PAG_buf V_MEMRAM2 GW_Mmi_05_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_GW_Mmi_06_PAG_buf V_MEMRAM2 GW_Mmi_06_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_GW_Mmi_07_PAG_buf V_MEMRAM2 GW_Mmi_07_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_GW_Mmi_10_PAG_buf V_MEMRAM2 GW_Mmi_10_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_HVLM_05_buf V_MEMRAM2 HVLM_05;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_ISO_Info_El_Resp_buf V_MEMRAM2 ISO_Info_El_Resp;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Klemmen_Status_01_buf V_MEMRAM2 Klemmen_Status_01;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Klima_02_buf V_MEMRAM2 Klima_02;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Klima_03_buf V_MEMRAM2 Klima_03;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_02_buf V_MEMRAM2 Kombi_02;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_09_PAG_buf V_MEMRAM2 Kombi_09_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_10_PAG_buf V_MEMRAM2 Kombi_10_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_11_PAG_buf V_MEMRAM2 Kombi_11_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_13_PAG_buf V_MEMRAM2 Kombi_13_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_14_PAG_buf V_MEMRAM2 Kombi_14_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_16_PAG_buf V_MEMRAM2 Kombi_16_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_17_PAG_buf V_MEMRAM2 Kombi_17_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_EV_01_PAG_buf V_MEMRAM2 Kombi_EV_01_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_18_PAG_buf V_MEMRAM2 Kombi_18_PAG;
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_18_PAG_m1_buf V_MEMRAM2 Kombi_18_PAG_m1;
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_18_PAG_m2_buf V_MEMRAM2 Kombi_18_PAG_m2;
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_18_PAG_m3_buf V_MEMRAM2 Kombi_18_PAG_m3;
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_18_PAG_m4_buf V_MEMRAM2 Kombi_18_PAG_m4;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_LAD_02_buf V_MEMRAM2 LAD_02;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Lift_01_buf V_MEMRAM2 Lift_01;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mem_Kombi_01_PAG_buf V_MEMRAM2 Mem_Kombi_01_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_MFL_Tasten_Kon_01_buf V_MEMRAM2 MFL_Tasten_Kon_01;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Motor_06_buf V_MEMRAM2 Motor_06;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Motor_15_PAG_buf V_MEMRAM2 Motor_15_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_NMH_CDR_PCM_buf V_MEMRAM2 NMH_CDR_PCM;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_NPM_01_PAG_buf V_MEMRAM2 NPM_01_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PCM_02_PAG_buf V_MEMRAM2 PCM_02_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PCM_04_PAG_buf V_MEMRAM2 PCM_04_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_PCM_CDR_01_PAG_buf V_MEMRAM2 PCM_CDR_01_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_RDK_02_PAG_buf V_MEMRAM2 RDK_02_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Systeminfo_01_buf V_MEMRAM2 Systeminfo_01;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_VIN_01_buf V_MEMRAM2 VIN_01;
V_MEMRAM0 extern  V_MEMRAM1 _c_VIN_01_m0_buf V_MEMRAM2 VIN_01_m0;
V_MEMRAM0 extern  V_MEMRAM1 _c_VIN_01_m1_buf V_MEMRAM2 VIN_01_m1;
V_MEMRAM0 extern  V_MEMRAM1 _c_VIN_01_m2_buf V_MEMRAM2 VIN_01_m2;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_ADR_01_PAG_buf V_MEMRAM2 ADR_01_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_ADR_02_PAG_buf V_MEMRAM2 ADR_02_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Klima_13_PAG_buf V_MEMRAM2 Klima_13_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Miko_01_PAG_buf V_MEMRAM2 Miko_01_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Motor_02_sek_buf V_MEMRAM2 Motor_02_sek;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_HVLM_07_PAG_buf V_MEMRAM2 HVLM_07_PAG;
V_MEMRAM0 extern  V_MEMRAM1 _c_HVLM_07_PAG_m1_buf V_MEMRAM2 HVLM_07_PAG_m1;
V_MEMRAM0 extern  V_MEMRAM1 _c_HVLM_07_PAG_m2_buf V_MEMRAM2 HVLM_07_PAG_m2;
V_MEMRAM0 extern  V_MEMRAM1 _c_HVLM_07_PAG_m3_buf V_MEMRAM2 HVLM_07_PAG_m3;
V_MEMRAM0 extern  V_MEMRAM1 _c_HVLM_07_PAG_m4_buf V_MEMRAM2 HVLM_07_PAG_m4;
V_MEMRAM0 extern  V_MEMRAM1 _c_HVLM_07_PAG_m7_buf V_MEMRAM2 HVLM_07_PAG_m7;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Kombi_19_PAG_buf V_MEMRAM2 Kombi_19_PAG;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Motor_K_02_buf V_MEMRAM2 Motor_K_02;
/* RAM CATEGORY 2 END */






/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 88863978
      #error "The magic number of the generated file <F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\inc\drv_par.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 88863978
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __DRV_PAR_H__ */
