/* -----------------------------------------------------------------------------
  Filename:    nmh_cfg.h
  Description: Toolversion: 03.20.21.01.10.02.79.00.00.00
               
               Serial Number: CBD1100279
               Customer Info: Dr. Ing. h. c. F. Porsche AG
                              CBD / Porsche 2007+
                              Texas Instruments TMS470 / TMS470 R1SF55
                              Texas Instruments 4.6.6 Compiler
               
               
               Generator Fwk   : GENy 
               Generator Module: Nm_PwrTrain_Vag
               
               Configuration   : F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\cfg\Porsche_ADR.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470Cpu
                       Compiler:     TexasInstruments
                       Derivates:    TMS470R1
               
               Channel "Channel0":
                       Databasefile: F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\cfg\CAN_Matrix_Dashboard_2_11_0_X2_Release.dbc
                       Bussystem:    CAN
                       Manufacturer: Porsche AG
                       Node:         ADR_PAG_X2

  Generated by , 2012-02-15  08:51:09
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2010 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__NMH_CFG_H__)
#define __NMH_CFG_H__

#define NMHIGHDLL_VERSION                    0x0205
#define NMHIGHDLL_RELEASE_VERSION            0x01
#define kNmhNumberOfChannels                 1
/* Nm instance properties */
#define NM_TYPE_NMHIGH
#define kNmhNumberOfUsedTxCANObjects         kCanNumberOfUsedTxCANObjects
/* Support for indexed NM */
#define NMH_DISABLE_INDEXED_NM
/* NMH Multi ECU Support */
#define NMH_DISABLE_MULTI_ECU
/* Integration: Interrupt locking */
#define NmhIntInterruptDisable               CanInterruptDisable
#define NmhIntInterruptRestore               CanInterruptRestore
/* Timing parameters: NM algorithm */
#define kNmhCycleTime                        10
#define kNmhMsgCycleTime                     200
#define kNmhTimeoutTime                      1000
#define kNmhWaitBusSleepTime                 750
#define kNmhPrepareSleepTime                 500
#define kNmhMsgTimeout                       1000
#define kNmhRepeatMsgCounts                  5
/* Timing parameters: BusOffRecovery */
#define kNmhBusOffRecoveryTime1              50
#define kNmhBusOffRecoveryTime2              200
/* Misc parameters */
#define NMH_DISABLE_TESTDEBUG
#define NMH_DISABLE_TX_TIMEOUT_OBSERVE
#define NMH_DISABLE_NM_MSG_RX_IND_FCT
/* Switches for Callback functions */
#define NMH_ENABLE_CALLBACK_FCT
#define NMH_DISABLE_TX_OBSERVE_CALLBACK
#define NMH_DISABLE_RECEIVE_FCT_CALLBACK
#define NMH_DISABLE_CONF_FCT_CALLBACK
/* API types: core */
#define NMH_API_CALL_TYPE
#define NMH_API_CALLBACK_TYPE
#define NMH_INTERNAL_CALL_TYPE
/* API types: wrapper */
#define NMH_WRAPPER_API_CALL_TYPE            NMH_API_CALLBACK_TYPE
#define NMH_WRAPPER_API_CALLBACK_TYPE
#define NMH_WRAPPER_INTERNAL_CALL_TYPE
/* Nm channel properties */
#define NmhGetTransmitHandle()  (CanTransmitHandle) CanTxNMH_CDR_PCM
#define NmhGetNmMsgDataPtr()                 ((TxDataPtr) NMH_CDR_PCM._c)

/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 88863978
      #error "The magic number of the generated file <F:\projects\ADR-Porsche\Porsche_ADR_Development_trunk\MOD\MOD_CAN_GEN\inc\nmh_cfg.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 88863978
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __NMH_CFG_H__ */
