#ifndef PORT_CE_H_
#define PORT_CE_H_


// PORT A
#define PORT_NOTUSED_PIN0_GIOA	PIN0
#define PORT_NOTUSED_PIN1_GIOA	PIN1
#define PORT_CAN_ERROR			PIN2
#define PORT_CAN_INHIBIT		PIN3
#define PORT_NOTUSED_PIN4_GIOA  PIN4
#define PORT_IS_OMAP_SHUTDOWN	PIN5
#define PORT_NOTUSED_PIN6_GIOA	PIN6
#define PORT_NOTUSED_PIN7_GIOA	PIN7

//PORT B
#define PORT_FLASH_EN			PIN0
#define PORT_AUDIO_DIAG_EN		PIN1
#define PORT_NOTUSED_PIN2_GIOB	PIN2
#define PORT_CRADLE_WUP			PIN3
#define PORT_CAN_EN				PIN4
#define PORT_CAN_STB			PIN5
#define PORT_MUTE_ON			PIN6
#define PORT_OMAP_RESET         PIN7

// PORT C
#define PORT_OMAP_PWRON 		PIN0
#define USB_HOST1_VBUS_EN  		PIN1
#define USB_HOST2_VBUS_EN  		PIN2
#define PORT_LED_RED_ON_OFF			PIN3
#define PORT_LED_RED_TB			PIN4
#define PORT_LED_DIAG_EN		PIN5
#define PORT_CRADLE_ON_OFF			PIN6
#define PORT_CRADLE_TB			PIN7

// PORT D
#define PORT_MON_WATCHDOG		PIN0
#define PORT_U_GPS_EN			PIN1
#define PORT_MIC_EN             PIN2
#define PORT_MON_PWRHOLD		PIN3


#define HET_RESERVE_01 HET_PIN0
#define HET_RESERVE_02 HET_PIN1
#define HET_RESERVE_03 HET_PIN2
#define HET_RESERVE_04 HET_PIN3
#define HET_MUX_A0          HET_PIN4
#define HET_MUX_A1          HET_PIN5
#define HET_MUX_A2          HET_PIN6
#define HET_MUX_EN          HET_PIN7
#define HET_RESERVE_05      HET_PIN8
#define HET_PWM_FAN         HET_PIN9
#define HET_AUDIO_DIAG_EN   HET_PIN10
#define HET_DISP_BACKLIGHT_PWM HET_PIN11
#define HET_DISP_ON_OFF     HET_PIN12
#define HET_TMS470_AMP_WAKEUP HET_PIN13
#define HET_VERSION_LOW     HET_PIN14
#define HET_VERSION_HIGH    HET_PIN15
#define HET_CODE_DAB_SDARS  HET_PIN16
#define HET_MASTER_RESET    HET_PIN17
#define HET_TUNER_ENABLE    HET_PIN18
#define HET_GPIO1_TMS       HET_PIN19
#define HET_GPIO2_TMS       HET_PIN20
#define HET_TMS2OMAP_SPARE1 HET_PIN21
#define HET_TMS2OMAP_SPARE2 HET_PIN22
#define HET_U_FM1_EN        HET_PIN23
#define HET_U_FM2_EN        HET_PIN24
#define HET_SDARS_EN        HET_PIN25
#define HET_U_CAM_EN        HET_PIN26
#define HET_9V_ENABLE       HET_PIN27
#define HET_U_ANT_ON_EN     HET_PIN28
#define HET_USB_HOST1_PWR_EN HET_PIN29
#define HET_USB_HOST2_PWR_EN HET_PIN30
#define HET_SEL_U_DAB HET_PIN31

#endif /*PORT_CE_H_*/
